from __future__ import annotations

import os


LANGUAGE_CODES = ("en", "ko", "ja", "zh")

_LANGUAGE_ALIASES = {
    "": "en",
    "en": "en",
    "eng": "en",
    "english": "en",
    "ko": "ko",
    "kr": "ko",
    "kor": "ko",
    "korean": "ko",
    "한국어": "ko",
    "ja": "ja",
    "jp": "ja",
    "jpn": "ja",
    "japanese": "ja",
    "日本語": "ja",
    "zh": "zh",
    "cn": "zh",
    "zho": "zh",
    "chi": "zh",
    "chinese": "zh",
    "中文": "zh",
    "简体中文": "zh",
}

LANGUAGE_NAMES = {
    "en": "English",
    "ko": "한국어",
    "ja": "日本語",
    "zh": "中文",
}

MESSAGES = {
    "en": {
        "language_title": "Setup language",
        "language_intro": "Choose the language OMH should use for this terminal setup.",
        "menu_hint": "Use ↑/↓, Space/Enter, or a number. Colors are not required.",
        "recommended": "recommended",
        "select": "Select",
        "invalid_selection": "Invalid selection. Choose one of: {valid}.",
        "invalid_yes_no": "Please answer y or n.",
        "yes": "Yes",
        "no": "No",
        "yes_desc": "Apply this setup step.",
        "no_desc": "Skip this step for now.",
        "setup_title": "OMH setup",
        "setup_subtitle": "Connect OMH workflows to Hermes without changing how you normally work.",
        "install_subtitle": "Refresh the OMH workflow pack.",
        "wizard_subtitle": "Press Enter through the recommended choices for a safe first install. All OMH workflows stay available either way.",
        "hermes_home": "Hermes home",
        "hermes_config": "Hermes config",
        "managed_skills": "OMH workflows",
        "status_already_registered": "already registered",
        "status_will_register": "will connect OMH workflows",
        "status_will_create": "will create",
        "register_question": "Connect OMH workflows to this Hermes profile?",
        "register_note": "This lets Hermes find the OMH workflows installed on this machine.",
        "executor_title": "Default coding agent",
        "executor_intro_1": "Pick the coding agent Hermes should suggest first.",
        "executor_intro_2": "You can still change it per request; this only saves the first suggestion.",
        "executor_choose_label": "Ask every time",
        "executor_choose_desc": "Recommended. Hermes asks before using Codex, Claude Code, Hermes, or another coding agent.",
        "executor_codex_label": "Codex",
        "executor_codex_desc": "Use Codex as the default coding agent for implementation-shaped work.",
        "executor_claude_label": "Claude Code",
        "executor_claude_desc": "Prepare Claude Code-ready prompts when coding work is selected.",
        "executor_generic_label": "Other coding agent",
        "executor_generic_desc": "Prepare a portable prompt for another coding agent.",
        "executor_hermes_label": "Hermes",
        "executor_hermes_desc": "Keep small coding-like work in Hermes first; larger work can still use another agent.",
        "executor_runtime_label": "Oh-my runtime",
        "executor_runtime_desc": "Use an oh-my runtime profile when the user has one.",
        "invalid_executor": "Invalid default executor: {error}",
        "plugin_note": "The plugin exposes local status context to Hermes without changing workflow behavior by itself.",
        "mcp_question": "Prepare optional MCP bridge settings?",
        "mcp_note": "This only records the bridge preference; OMH does not claim MCP host load until a host reports it.",
        "scope_title": "Choose setup scope",
        "scope_intro_1": "User scope is best for a personal Hermes profile.",
        "scope_intro_2": "Project scope keeps OMH and Hermes config isolated inside the current repository.",
        "scope_user_label": "User scope",
        "scope_user_desc": "Use ~/.omh and ~/.hermes for this machine user.",
        "scope_project_label": "Project scope",
        "scope_project_desc": "Use ./.omh and ./.hermes so this repository has its own OMH setup.",
        "team_title": "Add an optional visible team role preset?",
        "team_intro_1": "These presets only add visible role names for Hermes collaboration.",
        "team_intro_2": "Skip now unless you want those roles shown in chat; every OMH workflow is still installed.",
        "team_none_label": "No extra team role preset now",
        "team_none_desc": "Recommended for first install. Core skills stay installed; other surfaces remain available through Hermes routing.",
        "advanced_title": "Advanced options",
        "advanced_question": "Show advanced options for tool bridges and visible team roles?",
        "advanced_note": "Skip this on a first install. You can add them later with setup flags.",
        "step_install_skills": "Installing OMH workflows",
        "step_register": "Connecting OMH to Hermes",
        "step_plugin": "Installing OMH status helper",
        "step_mcp": "Recording optional tool bridge preference",
        "step_team": "Activating visible team role preset",
        "step_preferences": "Saving coding request preference",
        "step_targets": "Checking Hermes profile",
        "done_skills_installed": "{count} workflow(s) ready",
        "done_skills_ready": "{count} workflow(s) ready",
        "done_profile_packs": "{count} profile pack(s) activated",
        "done_default_executor": "coding preference saved: {executor}",
        "done_mcp_bridge": "tool bridge preference: {status}",
        "done_target_topology": "{count} Hermes profile(s) detected",
        "target_recorded": "Hermes profile checked",
        "skip_by_flag": "skipped by {flag}",
        "setup_complete": "OMH setup complete.",
        "setup_preview_complete": "OMH setup preview complete.",
        "install_complete": "OMH {label} complete.",
        "install_preview_complete": "OMH {label} preview complete.",
        "summary": "Summary",
        "next": "Next",
        "setup_scope": "Install location: {scope}",
        "setup_scope_user": "this user account",
        "setup_scope_project": "this project folder",
        "setup_scope_custom": "custom paths",
        "setup_install_mode": "Workflow source: {mode}",
        "setup_install_mode_managed_skills": "OMH managed workflows",
        "setup_mcp_mode": "Advanced tool bridge: {mode}",
        "setup_mcp_mode_none": "not enabled",
        "setup_mcp_mode_bridge_requested": "preference recorded",
        "setup_status": "Status: {status}",
        "setup_status_configured": "ready; restart or reload Hermes to use OMH in chat",
        "setup_status_dry_run": "preview only; no files changed",
        "setup_status_skills_only": "workflows ready; Hermes connection skipped",
        "command_path_found": "Terminal command: omh found at {path}",
        "command_path_missing": "Terminal command: omh is not on PATH for this shell.",
        "command_path_missing_next": "Use the absolute command path printed by the installer, or add that directory to PATH.",
        "skills_line": "OMH workflows: {count} ready at {path}",
        "registration_configured": "Hermes connection: ready in {path}. Restart or reload Hermes Agent to see OMH in chat.",
        "registration_dry_run": "Hermes connection: preview only; no files changed.",
        "registration_skipped": "Hermes connection: skipped by --skip-apply.",
        "registration_unknown": "Hermes connection: {status}",
        "apply_line": "Hermes connection detail: {message}",
        "default_handoff": "Coding requests: {summary}",
        "setup_profile": "Advanced routing detail: {selected}",
        "target_topology": "Hermes profile check: {count} profile(s) detected.",
        "plugin_bridge": "OMH status helper: {status}",
        "team_activated": "Visible team preset: {count} profile pack(s) activated.",
        "team_none": "Visible team preset: none selected; OMH workflows are still available.",
        "setup_next_dry": "Rerun without `--dry-run` to install the workflows and connect them to Hermes.",
        "setup_next_reload": "Restart or reload Hermes Agent, then try this in Hermes chat:",
        "setup_next_prompt": "Ask Hermes: Use OMH to safely plan a feature for this repo.",
        "setup_next_verify": "If Hermes cannot see OMH yet, run `omh doctor` and restart or reload Hermes again.",
        "machine_readable": "For machine-readable output, rerun with `--json`.",
        "source": "Source: {source}",
        "source_builtin": "installed command package (builtin)",
        "release_channel": "Release channel: {channel}",
        "package_url": "Package URL: {url}",
        "recorded_package_url": "Recorded package URL: {url}",
        "release_version_change": "Release version: {change}",
        "release_source_ref_change": "Source ref: {change}",
        "release_update_status": "Release state: {status}",
        "command_package_updated": "Command package: updated by installer before this OMH setup/update run.",
        "command_package_unchanged": "Command package: unchanged; this command refreshed the OMH workflows from the currently installed OMH package.",
        "update_command_next": "To update the `omh` command itself, rerun the installer: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes/main/install.sh | sh",
        "state_log": "State log: {path} ({entry})",
        "install_next_dry": "Rerun without `--dry-run` to refresh the OMH workflows.",
        "install_next": "Run `omh setup` to connect OMH workflows to Hermes, or `omh doctor` to verify health.",
        "update_next": "Run `omh doctor` to verify health; run `omh setup` only if registration needs repair.",
        "doctor_complete": "OMH doctor complete.",
        "doctor_needs_attention": "OMH doctor needs attention.",
        "doctor_status": "Status: {status}",
        "doctor_status_ok": "ok",
        "doctor_status_needs_attention": "needs attention",
        "doctor_checks": "Checks: {passing}/{total} passing",
        "doctor_issue_counts": "Issues: {blocking} blocking, {warnings} warning(s)",
        "doctor_group_managed_skills": "Managed skills",
        "doctor_group_runtime": "Runtime state",
        "doctor_group_hermes_registration": "Hermes registration",
        "doctor_group_targets": "Hermes targets",
        "doctor_group_optional_surfaces": "Optional surfaces",
        "doctor_group_command": "Command availability",
        "doctor_group_status_ok": "ok",
        "doctor_group_status_warning": "warning",
        "doctor_group_status_needs_attention": "needs attention",
        "doctor_fix": "Fix",
        "doctor_boundary": "Boundary: restart or reload Hermes before treating chat visibility as observed.",
        "config_external_dir_already_present": "already configured",
        "config_created_skills_external_dirs": "Hermes can now find OMH workflows",
        "config_appended_skills_external_dirs": "Hermes can now find OMH workflows",
        "config_expanded_inline_external_dirs": "Hermes can now find OMH workflows",
        "config_inserted_skills_external_dirs": "Hermes can now find OMH workflows",
        "config_added_external_dir": "Hermes can now find OMH workflows",
        "config_external_dir_absent": "already removed",
        "config_removed_external_dir": "removed OMH skills directory",
        "uninstall_title": "OMH uninstall",
        "uninstall_subtitle": "Remove OMH-managed local state and Hermes integration files.",
        "uninstall_complete": "OMH uninstall complete.",
        "uninstall_preview_complete": "OMH uninstall preview complete.",
        "uninstall_scope_all": "full cleanup",
        "uninstall_scope_registration": "registration only",
        "uninstall_scope_files": "registration and managed ~/.omh files",
        "uninstall_config": "Hermes registration: {message}",
        "uninstall_removed": "Removed: {count} path(s)",
        "uninstall_would_remove": "Would remove: {count} path(s)",
        "uninstall_none": "Nothing to remove.",
        "uninstall_command_removed": "Command package: removed {count} install.sh-managed path(s).",
        "uninstall_command_would_remove": "Command package: would remove {count} install.sh-managed path(s).",
        "uninstall_command_kept": "Command package: not removed because this `omh` is not running from an install.sh-managed OMH venv.",
        "uninstall_command_still_available": "If `omh` still runs after uninstall, the command package is still on PATH; remove it with the installer-managed venv, pip, or pipx that installed it.",
        "scope": "Scope",
        "kept": "Kept",
    },
    "ko": {
        "language_title": "설치 언어",
        "language_intro": "이 터미널 설치에서 OMH가 사용할 언어를 선택합니다.",
        "menu_hint": "↑/↓, Space/Enter, 숫자로 선택할 수 있습니다. 색상 없이도 동작합니다.",
        "recommended": "추천",
        "select": "선택",
        "invalid_selection": "잘못된 선택입니다. 다음 중 하나를 선택하세요: {valid}.",
        "invalid_yes_no": "y 또는 n으로 답해주세요.",
        "yes": "예",
        "no": "아니요",
        "yes_desc": "이 설정 단계를 적용합니다.",
        "no_desc": "지금은 이 단계를 건너뜁니다.",
        "setup_title": "OMH 설정",
        "setup_subtitle": "평소 쓰는 Hermes 흐름은 그대로 두고 OMH 워크플로를 연결합니다.",
        "install_subtitle": "OMH 워크플로 팩을 갱신합니다.",
        "wizard_subtitle": "첫 설치라면 추천값에서 Enter만 눌러도 안전합니다. 어떤 선택을 해도 OMH 워크플로는 계속 사용할 수 있습니다.",
        "hermes_home": "Hermes 홈",
        "hermes_config": "Hermes 설정",
        "managed_skills": "OMH 워크플로",
        "status_already_registered": "이미 등록됨",
        "status_will_register": "OMH 워크플로 연결 예정",
        "status_will_create": "생성 예정",
        "register_question": "이 Hermes 프로필에 OMH 워크플로를 연결할까요?",
        "register_note": "Hermes가 이 기기에 설치된 OMH 워크플로를 찾을 수 있게 합니다.",
        "executor_title": "기본 코딩 에이전트",
        "executor_intro_1": "Hermes가 먼저 제안할 코딩 에이전트를 고릅니다.",
        "executor_intro_2": "요청마다 다시 바꿀 수 있고, 이 값은 첫 제안만 저장합니다.",
        "executor_choose_label": "매번 물어보기",
        "executor_choose_desc": "추천. Codex, Claude Code, Hermes, 기타 코딩 에이전트 중 무엇을 쓸지 먼저 묻습니다.",
        "executor_codex_label": "Codex",
        "executor_codex_desc": "구현형 작업의 기본 코딩 에이전트로 Codex를 사용합니다.",
        "executor_claude_label": "Claude Code",
        "executor_claude_desc": "코딩 작업이 선택되면 Claude Code에 넣기 쉬운 프롬프트를 준비합니다.",
        "executor_generic_label": "기타 코딩 에이전트",
        "executor_generic_desc": "다른 코딩 에이전트에도 줄 수 있는 프롬프트를 준비합니다.",
        "executor_hermes_label": "Hermes",
        "executor_hermes_desc": "작은 코딩 유사 작업은 먼저 Hermes 안에서 다룹니다.",
        "executor_runtime_label": "Oh-my 런타임",
        "executor_runtime_desc": "사용자가 oh-my 런타임을 쓰는 경우 그 프로필을 기본값으로 둡니다.",
        "invalid_executor": "기본 실행자 값이 올바르지 않습니다: {error}",
        "plugin_note": "플러그인은 워크플로 동작 자체를 바꾸지 않고 Hermes에 로컬 상태 맥락을 제공합니다.",
        "mcp_question": "선택형 MCP 브리지 설정을 준비할까요?",
        "mcp_note": "브리지 선호만 기록합니다. MCP 호스트가 보고하기 전까지 OMH는 로드됐다고 말하지 않습니다.",
        "scope_title": "설정 범위 선택",
        "scope_intro_1": "사용자 범위는 개인 Hermes 프로필에 가장 적합합니다.",
        "scope_intro_2": "프로젝트 범위는 현재 저장소 안에 OMH와 Hermes 설정을 격리합니다.",
        "scope_user_label": "사용자 범위",
        "scope_user_desc": "이 사용자/기기에서 ~/.omh 와 ~/.hermes 를 사용합니다.",
        "scope_project_label": "프로젝트 범위",
        "scope_project_desc": "이 저장소만의 OMH 설정을 위해 ./.omh 와 ./.hermes 를 사용합니다.",
        "team_title": "선택형 보이는 팀 역할 프리셋을 추가할까요?",
        "team_intro_1": "이 프리셋은 Hermes 협업에 보이는 역할 이름만 추가합니다.",
        "team_intro_2": "채팅에서 그 역할을 보이고 싶을 때만 선택하세요. 모든 OMH 워크플로는 계속 설치됩니다.",
        "team_none_label": "지금은 추가 팀 역할 프리셋 없음",
        "team_none_desc": "첫 설치에 추천합니다. 핵심 스킬은 설치되고, 나머지 surface는 Hermes 라우팅으로 사용할 수 있습니다.",
        "advanced_title": "고급 옵션",
        "advanced_question": "도구 브리지와 보이는 팀 역할 같은 고급 옵션을 볼까요?",
        "advanced_note": "첫 설치라면 건너뛰어도 됩니다. 나중에 setup 옵션으로 추가할 수 있습니다.",
        "step_install_skills": "OMH 워크플로 설치",
        "step_register": "Hermes에 OMH 연결",
        "step_plugin": "OMH 상태 도우미 설치",
        "step_mcp": "선택형 도구 브리지 선호 기록",
        "step_team": "보이는 팀 역할 프리셋 활성화",
        "step_preferences": "코딩 요청 기본값 저장",
        "step_targets": "Hermes 프로필 확인",
        "done_skills_installed": "{count}개 워크플로 준비 완료",
        "done_skills_ready": "{count}개 워크플로 준비 완료",
        "done_profile_packs": "{count}개 프로필 팩 활성화",
        "done_default_executor": "코딩 기본값 저장: {executor}",
        "done_mcp_bridge": "도구 브리지 선호: {status}",
        "done_target_topology": "{count}개 Hermes 프로필 감지",
        "target_recorded": "Hermes 프로필 확인 완료",
        "skip_by_flag": "{flag} 때문에 건너뜀",
        "setup_complete": "OMH 설정이 완료되었습니다.",
        "setup_preview_complete": "OMH 설정 미리보기가 완료되었습니다.",
        "install_complete": "OMH {label} 완료.",
        "install_preview_complete": "OMH {label} 미리보기 완료.",
        "summary": "요약",
        "next": "다음",
        "setup_scope": "설치 위치: {scope}",
        "setup_scope_user": "이 사용자 계정",
        "setup_scope_project": "이 프로젝트 폴더",
        "setup_scope_custom": "사용자 지정 경로",
        "setup_install_mode": "워크플로 소스: {mode}",
        "setup_install_mode_managed_skills": "OMH 관리 워크플로",
        "setup_mcp_mode": "고급 도구 브리지: {mode}",
        "setup_mcp_mode_none": "사용 안 함",
        "setup_mcp_mode_bridge_requested": "선호 기록됨",
        "setup_status": "상태: {status}",
        "setup_status_configured": "준비됨; Hermes를 재시작하거나 다시 불러오면 채팅에서 OMH를 쓸 수 있습니다",
        "setup_status_dry_run": "미리보기만 수행; 파일 변경 없음",
        "setup_status_skills_only": "워크플로 준비 완료; Hermes 연결은 건너뜀",
        "command_path_found": "터미널 명령어: omh가 {path}에서 발견되었습니다.",
        "command_path_missing": "터미널 명령어: 이 shell의 PATH에서 omh를 찾을 수 없습니다.",
        "command_path_missing_next": "설치기가 출력한 절대 경로를 사용하거나, 그 디렉터리를 PATH에 추가하세요.",
        "skills_line": "OMH 워크플로: {path}에 {count}개 준비됨",
        "registration_configured": "Hermes 연결: {path}에 준비됨. Hermes Agent를 재시작하거나 다시 불러오면 채팅에서 OMH가 보입니다.",
        "registration_dry_run": "Hermes 연결: 미리보기만 수행; 파일 변경 없음.",
        "registration_skipped": "Hermes 연결: --skip-apply로 건너뜀.",
        "registration_unknown": "Hermes 연결: {status}",
        "apply_line": "Hermes 연결 상세: {message}",
        "default_handoff": "코딩 요청: {summary}",
        "setup_profile": "고급 라우팅 상세: {selected}",
        "target_topology": "Hermes 프로필 확인: {count}개 프로필 감지.",
        "plugin_bridge": "OMH 상태 도우미: {status}",
        "team_activated": "보이는 팀 프리셋: {count}개 프로필 팩 활성화.",
        "team_none": "보이는 팀 프리셋: 선택 안 함. OMH 워크플로는 계속 사용할 수 있습니다.",
        "setup_next_dry": "`--dry-run` 없이 다시 실행하면 워크플로를 설치하고 Hermes에 연결합니다.",
        "setup_next_reload": "Hermes Agent를 재시작하거나 다시 불러온 뒤 Hermes 채팅에서 시도하세요:",
        "setup_next_prompt": "Hermes에게 말해보세요: OMH로 이 저장소에 기능을 안전하게 추가할 수 있게 정리해줘.",
        "setup_next_verify": "Hermes가 아직 OMH를 못 보면 `omh doctor`를 실행하고 Hermes를 다시 시작/불러오세요.",
        "machine_readable": "기계가 읽는 출력이 필요하면 `--json`으로 다시 실행하세요.",
        "source": "소스: {source}",
        "source_builtin": "설치된 명령 패키지(builtin)",
        "release_channel": "릴리즈 채널: {channel}",
        "package_url": "패키지 URL: {url}",
        "recorded_package_url": "기록된 패키지 URL: {url}",
        "release_version_change": "릴리즈 버전: {change}",
        "release_source_ref_change": "소스 ref: {change}",
        "release_update_status": "릴리즈 상태: {status}",
        "command_package_updated": "명령 패키지: 설치 스크립트가 이번 OMH setup/update 실행 전에 갱신했습니다.",
        "command_package_unchanged": "명령 패키지: 변경하지 않았습니다. 이 명령은 현재 설치된 OMH 패키지에서 OMH 워크플로만 갱신했습니다.",
        "update_command_next": "`omh` 명령 자체를 갱신하려면 설치 스크립트를 다시 실행하세요: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes/main/install.sh | sh",
        "state_log": "상태 로그: {path} ({entry})",
        "install_next_dry": "`--dry-run` 없이 다시 실행하면 OMH 워크플로를 갱신합니다.",
        "install_next": "`omh setup`으로 OMH 워크플로를 Hermes에 연결하거나 `omh doctor`로 상태를 확인하세요.",
        "update_next": "`omh doctor`로 상태를 확인하세요. 등록 복구가 필요할 때만 `omh setup`을 실행하세요.",
        "doctor_complete": "OMH doctor가 완료되었습니다.",
        "doctor_needs_attention": "OMH doctor에 확인이 필요합니다.",
        "doctor_status": "상태: {status}",
        "doctor_status_ok": "정상",
        "doctor_status_needs_attention": "확인 필요",
        "doctor_checks": "검사: {passing}/{total} 통과",
        "doctor_issue_counts": "이슈: 차단 {blocking}개, 경고 {warnings}개",
        "doctor_group_managed_skills": "관리 스킬",
        "doctor_group_runtime": "런타임 상태",
        "doctor_group_hermes_registration": "Hermes 등록",
        "doctor_group_targets": "Hermes 대상",
        "doctor_group_optional_surfaces": "선택형 표면",
        "doctor_group_command": "명령어 사용 가능성",
        "doctor_group_status_ok": "정상",
        "doctor_group_status_warning": "경고",
        "doctor_group_status_needs_attention": "확인 필요",
        "doctor_fix": "수정",
        "doctor_boundary": "경계: Hermes 채팅 노출을 관측된 것으로 보기 전에 Hermes를 재시작하거나 다시 불러오세요.",
        "config_external_dir_already_present": "이미 설정됨",
        "config_created_skills_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_appended_skills_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_expanded_inline_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_inserted_skills_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_added_external_dir": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_external_dir_absent": "이미 제거됨",
        "config_removed_external_dir": "OMH 스킬 디렉터리 제거",
        "uninstall_title": "OMH 삭제",
        "uninstall_subtitle": "OMH가 관리하는 로컬 상태와 Hermes 연동 파일을 제거합니다.",
        "uninstall_complete": "OMH 삭제가 완료되었습니다.",
        "uninstall_preview_complete": "OMH 삭제 미리보기가 완료되었습니다.",
        "uninstall_scope_all": "전체 정리",
        "uninstall_scope_registration": "등록만 해제",
        "uninstall_scope_files": "등록과 관리 ~/.omh 파일 삭제",
        "uninstall_config": "Hermes 등록: {message}",
        "uninstall_removed": "삭제됨: {count}개 경로",
        "uninstall_would_remove": "삭제 예정: {count}개 경로",
        "uninstall_none": "삭제할 항목이 없습니다.",
        "uninstall_command_removed": "명령 패키지: install.sh가 관리하는 {count}개 경로를 삭제했습니다.",
        "uninstall_command_would_remove": "명령 패키지: install.sh가 관리하는 {count}개 경로를 삭제할 예정입니다.",
        "uninstall_command_kept": "명령 패키지: 이 `omh`가 install.sh 관리 OMH venv에서 실행 중이 아니어서 삭제하지 않았습니다.",
        "uninstall_command_still_available": "uninstall 뒤에도 `omh`가 실행된다면 명령 패키지가 아직 PATH에 남아 있는 것입니다. 설치에 사용한 installer-managed venv, pip, 또는 pipx에서 제거하세요.",
        "scope": "범위",
        "kept": "유지됨",
    },
    "ja": {
        "language_title": "セットアップ言語",
        "language_intro": "このターミナルセットアップで OMH が使う言語を選びます。",
        "menu_hint": "↑/↓、Space/Enter、または数字で選択できます。色なしでも動作します。",
        "recommended": "推奨",
        "select": "選択",
        "invalid_selection": "無効な選択です。次から選んでください: {valid}.",
        "invalid_yes_no": "y または n で答えてください。",
        "yes": "はい",
        "no": "いいえ",
        "yes_desc": "このセットアップ手順を適用します。",
        "no_desc": "今回はこの手順をスキップします。",
        "setup_title": "OMH セットアップ",
        "setup_subtitle": "インストール済みの OMH ワークフローをこの Hermes プロファイルに接続します。",
        "install_subtitle": "OMH ワークフローパックを更新します。",
        "wizard_subtitle": "初回インストールなら推奨値のまま Enter で安全に進められます。どの選択でも OMH ワークフローは利用できます。",
        "hermes_home": "Hermes ホーム",
        "hermes_config": "Hermes 設定",
        "managed_skills": "OMH ワークフロー",
        "status_already_registered": "登録済み",
        "status_will_register": "OMH ワークフローを接続予定",
        "status_will_create": "作成予定",
        "register_question": "この Hermes プロファイルに OMH ワークフローを接続しますか?",
        "register_note": "Hermes がこのマシンにインストールされた OMH ワークフローを見つけられるようにします。",
        "executor_title": "既定のコーディングエージェント",
        "executor_intro_1": "Hermes が最初に提案するコーディングエージェントを選びます。",
        "executor_intro_2": "リクエストごとに変更できます。これは最初の提案だけを保存します。",
        "executor_choose_label": "毎回確認",
        "executor_choose_desc": "推奨。Codex、Claude Code、Hermes、その他のコーディングエージェントのどれを使うか確認します。",
        "executor_codex_label": "Codex",
        "executor_codex_desc": "実装系作業の既定コーディングエージェントとして Codex を使います。",
        "executor_claude_label": "Claude Code",
        "executor_claude_desc": "コーディング作業が選ばれたら Claude Code 向けプロンプトを準備します。",
        "executor_generic_label": "その他のコーディングエージェント",
        "executor_generic_desc": "別のコーディングエージェントに渡せるプロンプトを準備します。",
        "executor_hermes_label": "Hermes",
        "executor_hermes_desc": "小さなコーディングに近い作業はまず Hermes 内で扱います。",
        "executor_runtime_label": "Oh-my ランタイム",
        "executor_runtime_desc": "oh-my ランタイムを使う場合、そのプロファイルを既定にします。",
        "invalid_executor": "既定実行者が無効です: {error}",
        "plugin_note": "プラグインはワークフロー動作自体を変えずに、Hermes にローカル状態の文脈を渡します。",
        "mcp_question": "任意の MCP ブリッジ設定を準備しますか?",
        "mcp_note": "ブリッジ設定の希望だけを記録します。MCP ホストが報告するまで、OMH はロード済みとは主張しません。",
        "scope_title": "セットアップスコープを選択",
        "scope_intro_1": "ユーザースコープは個人の Hermes プロファイルに適しています。",
        "scope_intro_2": "プロジェクトスコープは現在のリポジトリ内に OMH と Hermes 設定を分離します。",
        "scope_user_label": "ユーザースコープ",
        "scope_user_desc": "このユーザー/マシンで ~/.omh と ~/.hermes を使います。",
        "scope_project_label": "プロジェクトスコープ",
        "scope_project_desc": "このリポジトリ専用に ./.omh と ./.hermes を使います。",
        "team_title": "表示用チームペルソナを今有効化しますか?",
        "team_intro_1": "これは Hermes 連携で見えるロール名だけを追加します。",
        "team_intro_2": "チャット上でそのロールを見せたい場合だけ選んでください。OMH ワークフローはすべてインストールされます。",
        "team_none_label": "今は追加チームペルソナなし",
        "team_none_desc": "初回インストールに推奨。主要スキルは入り、他の surface は Hermes ルーティングで利用できます。",
        "advanced_title": "詳細オプション",
        "advanced_question": "ツールブリッジや表示用チームロールなどの詳細オプションを表示しますか?",
        "advanced_note": "初回インストールではスキップして問題ありません。後から setup オプションで追加できます。",
        "step_install_skills": "OMH ワークフローをインストール",
        "step_register": "OMH を Hermes に接続",
        "step_plugin": "OMH ステータスヘルパーをインストール",
        "step_mcp": "任意のツールブリッジ設定を記録",
        "step_team": "表示用チームロールプリセットを有効化",
        "step_preferences": "コーディングリクエスト設定を保存",
        "step_targets": "Hermes プロファイルを確認",
        "done_skills_installed": "{count} 個のワークフローを準備しました",
        "done_skills_ready": "{count} 個のワークフローを準備しました",
        "done_profile_packs": "{count} 個のプロファイルパックを有効化しました",
        "done_default_executor": "コーディング設定を保存: {executor}",
        "done_mcp_bridge": "ツールブリッジ設定: {status}",
        "done_target_topology": "{count} 個の Hermes プロファイルを検出",
        "target_recorded": "Hermes プロファイルを確認しました",
        "skip_by_flag": "{flag} によりスキップ",
        "setup_complete": "OMH セットアップが完了しました。",
        "setup_preview_complete": "OMH セットアップのプレビューが完了しました。",
        "install_complete": "OMH {label} が完了しました。",
        "install_preview_complete": "OMH {label} のプレビューが完了しました。",
        "summary": "概要",
        "next": "次",
        "setup_scope": "インストール先: {scope}",
        "setup_scope_user": "このユーザーアカウント",
        "setup_scope_project": "このプロジェクトフォルダ",
        "setup_scope_custom": "カスタムパス",
        "setup_install_mode": "ワークフローソース: {mode}",
        "setup_install_mode_managed_skills": "OMH 管理ワークフロー",
        "setup_mcp_mode": "詳細ツールブリッジ: {mode}",
        "setup_mcp_mode_none": "無効",
        "setup_mcp_mode_bridge_requested": "設定を記録済み",
        "setup_status": "状態: {status}",
        "setup_status_configured": "準備完了。Hermes を再起動または再読み込みするとチャットで OMH を使えます",
        "setup_status_dry_run": "プレビューのみ。ファイルは変更していません",
        "setup_status_skills_only": "ワークフロー準備済み。Hermes 接続はスキップ",
        "command_path_found": "ターミナルコマンド: omh は {path} にあります",
        "command_path_missing": "ターミナルコマンド: この shell の PATH で omh が見つかりません。",
        "command_path_missing_next": "インストーラーが表示した絶対パスを使うか、そのディレクトリを PATH に追加してください。",
        "skills_line": "OMH ワークフロー: {path} に {count} 個を準備済み",
        "registration_configured": "Hermes 接続: {path} に準備済み。Hermes Agent を再起動または再読み込みするとチャットで OMH が見えます。",
        "registration_dry_run": "Hermes 接続: プレビューのみ。ファイルは変更していません。",
        "registration_skipped": "Hermes 接続: --skip-apply によりスキップ。",
        "registration_unknown": "Hermes 接続: {status}",
        "apply_line": "Hermes 接続詳細: {message}",
        "default_handoff": "コーディングリクエスト: {summary}",
        "setup_profile": "詳細ルーティング: {selected}",
        "target_topology": "Hermes プロファイル確認: {count} 個のプロファイルを検出。",
        "plugin_bridge": "OMH ステータスヘルパー: {status}",
        "team_activated": "チームペルソナ: {count} 個のプロファイルパックを有効化。",
        "team_none": "チームペルソナ: 未有効化。OMH ワークフローは引き続き利用できます。",
        "setup_next_dry": "`--dry-run` なしで再実行すると、ワークフローをインストールして Hermes に接続します。",
        "setup_next_reload": "Hermes Agent を再起動または再読み込みし、Hermes チャットで試してください:",
        "setup_next_prompt": "Ask Hermes: Use OMH to safely plan a feature for this repo.",
        "setup_next_verify": "Hermes がまだ OMH を見つけられない場合は `omh doctor` を実行し、Hermes を再起動または再読み込みしてください。",
        "machine_readable": "機械可読出力が必要な場合は `--json` を付けて再実行してください。",
        "source": "ソース: {source}",
        "source_builtin": "インストール済みコマンドパッケージ (builtin)",
        "release_channel": "リリースチャンネル: {channel}",
        "package_url": "パッケージ URL: {url}",
        "recorded_package_url": "記録されたパッケージ URL: {url}",
        "release_version_change": "リリースバージョン: {change}",
        "release_source_ref_change": "ソース ref: {change}",
        "release_update_status": "リリース状態: {status}",
        "command_package_updated": "コマンドパッケージ: インストーラーがこの OMH setup/update 実行前に更新しました。",
        "command_package_unchanged": "コマンドパッケージ: 変更していません。このコマンドは現在インストール済みの OMH パッケージから OMH ワークフローだけを更新しました。",
        "update_command_next": "`omh` コマンド自体を更新するにはインストーラーを再実行してください: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes/main/install.sh | sh",
        "state_log": "状態ログ: {path} ({entry})",
        "install_next_dry": "`--dry-run` なしで再実行すると OMH ワークフローを更新します。",
        "install_next": "`omh setup` で OMH ワークフローを Hermes に接続するか、`omh doctor` で状態を確認してください。",
        "update_next": "`omh doctor` で状態を確認してください。登録の修復が必要な場合だけ `omh setup` を実行してください。",
        "doctor_complete": "OMH doctor が完了しました。",
        "doctor_needs_attention": "OMH doctor は確認が必要です。",
        "doctor_status": "状態: {status}",
        "doctor_status_ok": "ok",
        "doctor_status_needs_attention": "要確認",
        "doctor_checks": "チェック: {passing}/{total} 合格",
        "doctor_issue_counts": "問題: ブロック {blocking} 件、警告 {warnings} 件",
        "doctor_group_managed_skills": "管理スキル",
        "doctor_group_runtime": "ランタイム状態",
        "doctor_group_hermes_registration": "Hermes 登録",
        "doctor_group_targets": "Hermes ターゲット",
        "doctor_group_optional_surfaces": "任意サーフェス",
        "doctor_group_command": "コマンド利用可否",
        "doctor_group_status_ok": "ok",
        "doctor_group_status_warning": "警告",
        "doctor_group_status_needs_attention": "要確認",
        "doctor_fix": "修正",
        "doctor_boundary": "境界: チャット表示を観測済みと扱う前に Hermes を再起動または再読み込みしてください。",
        "config_external_dir_already_present": "すでに設定済み",
        "config_created_skills_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_appended_skills_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_expanded_inline_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_inserted_skills_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_added_external_dir": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_external_dir_absent": "すでに削除済み",
        "config_removed_external_dir": "OMH スキルディレクトリを削除",
        "uninstall_title": "OMH アンインストール",
        "uninstall_subtitle": "OMH が管理するローカル状態と Hermes 連携ファイルを削除します。",
        "uninstall_complete": "OMH アンインストールが完了しました。",
        "uninstall_preview_complete": "OMH アンインストールのプレビューが完了しました。",
        "uninstall_scope_all": "完全クリーンアップ",
        "uninstall_scope_registration": "登録のみ解除",
        "uninstall_scope_files": "登録と管理 ~/.omh ファイルを削除",
        "uninstall_config": "Hermes 登録: {message}",
        "uninstall_removed": "削除済み: {count} パス",
        "uninstall_would_remove": "削除予定: {count} パス",
        "uninstall_none": "削除する項目はありません。",
        "uninstall_command_removed": "コマンドパッケージ: install.sh 管理の {count} パスを削除しました。",
        "uninstall_command_would_remove": "コマンドパッケージ: install.sh 管理の {count} パスを削除予定です。",
        "uninstall_command_kept": "コマンドパッケージ: この `omh` は install.sh 管理の OMH venv から実行されていないため削除しませんでした。",
        "uninstall_command_still_available": "uninstall 後も `omh` が動く場合、コマンドパッケージがまだ PATH に残っています。インストールに使った installer-managed venv、pip、または pipx から削除してください。",
        "scope": "範囲",
        "kept": "保持",
    },
    "zh": {
        "language_title": "设置语言",
        "language_intro": "选择 OMH 在本次终端设置中使用的语言。",
        "menu_hint": "可用 ↑/↓、Space/Enter 或数字选择。无颜色也可使用。",
        "recommended": "推荐",
        "select": "选择",
        "invalid_selection": "无效选择。请选择: {valid}.",
        "invalid_yes_no": "请回答 y 或 n。",
        "yes": "是",
        "no": "否",
        "yes_desc": "应用此设置步骤。",
        "no_desc": "暂时跳过此步骤。",
        "setup_title": "OMH 设置",
        "setup_subtitle": "将已安装的 OMH 工作流连接到此 Hermes 配置。",
        "install_subtitle": "刷新 OMH 工作流包。",
        "wizard_subtitle": "首次安装可直接按 Enter 使用推荐值。无论如何选择，OMH 工作流都会保持可用。",
        "hermes_home": "Hermes 主目录",
        "hermes_config": "Hermes 配置",
        "managed_skills": "OMH 工作流",
        "status_already_registered": "已注册",
        "status_will_register": "将连接 OMH 工作流",
        "status_will_create": "将创建",
        "register_question": "是否将 OMH 工作流连接到此 Hermes 配置?",
        "register_note": "这会让 Hermes 找到此机器上安装的 OMH 工作流。",
        "executor_title": "默认编码代理",
        "executor_intro_1": "选择 Hermes 默认优先建议的编码代理。",
        "executor_intro_2": "每次请求仍可更改；这里只保存首次建议。",
        "executor_choose_label": "每次询问",
        "executor_choose_desc": "推荐。先询问使用 Codex、Claude Code、Hermes，还是其他编码代理。",
        "executor_codex_label": "Codex",
        "executor_codex_desc": "将 Codex 作为实现类工作的默认编码代理。",
        "executor_claude_label": "Claude Code",
        "executor_claude_desc": "选择编码工作时准备 Claude Code 可用的提示词。",
        "executor_generic_label": "其他编码代理",
        "executor_generic_desc": "准备可交给其他编码代理的通用提示词。",
        "executor_hermes_label": "Hermes",
        "executor_hermes_desc": "小型类似编码的工作先留在 Hermes 内处理。",
        "executor_runtime_label": "Oh-my 运行时",
        "executor_runtime_desc": "用户使用 oh-my 运行时时，将该配置作为默认值。",
        "invalid_executor": "默认执行器无效: {error}",
        "plugin_note": "插件向 Hermes 提供本地状态上下文，但本身不会改变工作流行为。",
        "mcp_question": "是否准备可选 MCP 桥设置?",
        "mcp_note": "这里只记录桥接偏好；在 MCP host 报告前，OMH 不会声称已加载。",
        "scope_title": "选择设置范围",
        "scope_intro_1": "用户范围适合个人 Hermes 配置。",
        "scope_intro_2": "项目范围会把 OMH 和 Hermes 配置隔离在当前仓库内。",
        "scope_user_label": "用户范围",
        "scope_user_desc": "在此用户/机器上使用 ~/.omh 和 ~/.hermes。",
        "scope_project_label": "项目范围",
        "scope_project_desc": "为此仓库使用 ./.omh 和 ./.hermes。",
        "team_title": "现在添加可见团队角色预设吗?",
        "team_intro_1": "这些预设只添加 Hermes 协作中可见的角色名称。",
        "team_intro_2": "只有想在聊天里显示这些角色时才选择；所有 OMH 工作流仍会安装。",
        "team_none_label": "现在不添加团队角色预设",
        "team_none_desc": "首次安装推荐。核心技能会安装，其他 surface 仍可通过 Hermes 路由使用。",
        "advanced_title": "高级选项",
        "advanced_question": "显示工具桥和可见团队角色等高级选项吗?",
        "advanced_note": "首次安装可以跳过。以后可用 setup 选项添加。",
        "step_install_skills": "安装 OMH 工作流",
        "step_register": "将 OMH 连接到 Hermes",
        "step_plugin": "安装 OMH 状态助手",
        "step_mcp": "记录可选工具桥偏好",
        "step_team": "启用可见团队角色预设",
        "step_preferences": "保存编码请求偏好",
        "step_targets": "检查 Hermes 配置",
        "done_skills_installed": "已准备 {count} 个工作流",
        "done_skills_ready": "已准备 {count} 个工作流",
        "done_profile_packs": "已启用 {count} 个配置包",
        "done_default_executor": "编码偏好已保存: {executor}",
        "done_mcp_bridge": "工具桥偏好: {status}",
        "done_target_topology": "检测到 {count} 个 Hermes 配置",
        "target_recorded": "Hermes 配置已检查",
        "skip_by_flag": "因 {flag} 跳过",
        "setup_complete": "OMH 设置已完成。",
        "setup_preview_complete": "OMH 设置预览已完成。",
        "install_complete": "OMH {label} 已完成。",
        "install_preview_complete": "OMH {label} 预览已完成。",
        "summary": "摘要",
        "next": "下一步",
        "setup_scope": "安装位置: {scope}",
        "setup_scope_user": "此用户账户",
        "setup_scope_project": "此项目文件夹",
        "setup_scope_custom": "自定义路径",
        "setup_install_mode": "工作流来源: {mode}",
        "setup_install_mode_managed_skills": "OMH 托管工作流",
        "setup_mcp_mode": "高级工具桥: {mode}",
        "setup_mcp_mode_none": "未启用",
        "setup_mcp_mode_bridge_requested": "偏好已记录",
        "setup_status": "状态: {status}",
        "setup_status_configured": "已就绪；重启或重新加载 Hermes 后即可在聊天中使用 OMH",
        "setup_status_dry_run": "仅预览；未更改文件",
        "setup_status_skills_only": "工作流已就绪；已跳过 Hermes 连接",
        "command_path_found": "终端命令: 在 {path} 找到 omh",
        "command_path_missing": "终端命令: 此 shell 的 PATH 中找不到 omh。",
        "command_path_missing_next": "请使用安装器输出的绝对路径，或将该目录加入 PATH。",
        "skills_line": "OMH 工作流: {path} 中已准备 {count} 个",
        "registration_configured": "Hermes 连接: 已在 {path} 准备好。重启或重新加载 Hermes Agent 后即可在聊天中看到 OMH。",
        "registration_dry_run": "Hermes 连接: 仅预览；未更改文件。",
        "registration_skipped": "Hermes 连接: 因 --skip-apply 跳过。",
        "registration_unknown": "Hermes 连接: {status}",
        "apply_line": "Hermes 连接详情: {message}",
        "default_handoff": "编码请求: {summary}",
        "setup_profile": "高级路由详情: {selected}",
        "target_topology": "Hermes 配置检查: 检测到 {count} 个配置。",
        "plugin_bridge": "OMH 状态助手: {status}",
        "team_activated": "可见团队预设: 已启用 {count} 个配置包。",
        "team_none": "可见团队预设: 未选择；OMH 工作流仍可使用。",
        "setup_next_dry": "不带 `--dry-run` 重新运行即可安装工作流并连接到 Hermes。",
        "setup_next_reload": "重启或重新加载 Hermes Agent，然后在 Hermes 聊天中尝试:",
        "setup_next_prompt": "Ask Hermes: Use OMH to safely plan a feature for this repo.",
        "setup_next_verify": "如果 Hermes 还看不到 OMH，请运行 `omh doctor` 并再次重启或重新加载 Hermes。",
        "machine_readable": "如需机器可读输出，请使用 `--json` 重新运行。",
        "source": "来源: {source}",
        "source_builtin": "已安装命令包 (builtin)",
        "release_channel": "发布频道: {channel}",
        "package_url": "包 URL: {url}",
        "recorded_package_url": "已记录包 URL: {url}",
        "release_version_change": "发布版本: {change}",
        "release_source_ref_change": "来源 ref: {change}",
        "release_update_status": "发布状态: {status}",
        "command_package_updated": "命令包: 安装器已在本次 OMH setup/update 运行前更新。",
        "command_package_unchanged": "命令包: 未更改；此命令只从当前已安装的 OMH 包刷新 OMH 工作流。",
        "update_command_next": "要更新 `omh` 命令本身，请重新运行安装器: curl -fsSL https://raw.githubusercontent.com/rlaope/oh-my-hermes/main/install.sh | sh",
        "state_log": "状态日志: {path} ({entry})",
        "install_next_dry": "不带 `--dry-run` 重新运行即可刷新 OMH 工作流。",
        "install_next": "运行 `omh setup` 将 OMH 工作流连接到 Hermes，或运行 `omh doctor` 检查健康状态。",
        "update_next": "运行 `omh doctor` 检查健康状态；只有注册需要修复时才运行 `omh setup`。",
        "doctor_complete": "OMH doctor 完成。",
        "doctor_needs_attention": "OMH doctor 需要处理。",
        "doctor_status": "状态: {status}",
        "doctor_status_ok": "正常",
        "doctor_status_needs_attention": "需要处理",
        "doctor_checks": "检查: {passing}/{total} 通过",
        "doctor_issue_counts": "问题: {blocking} 个阻塞，{warnings} 个警告",
        "doctor_group_managed_skills": "托管技能",
        "doctor_group_runtime": "运行时状态",
        "doctor_group_hermes_registration": "Hermes 注册",
        "doctor_group_targets": "Hermes 目标",
        "doctor_group_optional_surfaces": "可选表面",
        "doctor_group_command": "命令可用性",
        "doctor_group_status_ok": "正常",
        "doctor_group_status_warning": "警告",
        "doctor_group_status_needs_attention": "需要处理",
        "doctor_fix": "修复",
        "doctor_boundary": "边界: 在把聊天可见性视为已观察之前，请重启或重新加载 Hermes。",
        "config_external_dir_already_present": "已配置",
        "config_created_skills_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_appended_skills_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_expanded_inline_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_inserted_skills_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_added_external_dir": "Hermes 现在可以找到 OMH 工作流",
        "config_external_dir_absent": "已移除",
        "config_removed_external_dir": "已移除 OMH 技能目录",
        "uninstall_title": "OMH 卸载",
        "uninstall_subtitle": "删除 OMH 管理的本地状态和 Hermes 集成文件。",
        "uninstall_complete": "OMH 卸载已完成。",
        "uninstall_preview_complete": "OMH 卸载预览已完成。",
        "uninstall_scope_all": "完整清理",
        "uninstall_scope_registration": "仅取消注册",
        "uninstall_scope_files": "取消注册并删除托管 ~/.omh 文件",
        "uninstall_config": "Hermes 注册: {message}",
        "uninstall_removed": "已删除: {count} 个路径",
        "uninstall_would_remove": "将删除: {count} 个路径",
        "uninstall_none": "没有需要删除的项目。",
        "uninstall_command_removed": "命令包: 已删除 {count} 个 install.sh 托管路径。",
        "uninstall_command_would_remove": "命令包: 将删除 {count} 个 install.sh 托管路径。",
        "uninstall_command_kept": "命令包: 当前 `omh` 不是从 install.sh 托管的 OMH venv 运行，因此未删除。",
        "uninstall_command_still_available": "如果 uninstall 后 `omh` 仍可运行，说明命令包仍在 PATH 中；请从安装它的 installer-managed venv、pip 或 pipx 中删除。",
        "scope": "范围",
        "kept": "保留",
    },
}


def normalize_language(value: str | None) -> str:
    key = str(value or "").strip().lower()
    language = _LANGUAGE_ALIASES.get(key)
    if language:
        return language
    valid = ", ".join(LANGUAGE_CODES)
    raise ValueError(f"unsupported language: {value}; expected one of {valid}")


def language_from_env(default: str = "en") -> str:
    return normalize_language(os.environ.get("OMH_LANG") or os.environ.get("OMH_LANGUAGE") or default)


def language_options() -> list[dict[str, str]]:
    return [
        {"choice": str(index), "value": code, "label": LANGUAGE_NAMES[code], "description": ""}
        for index, code in enumerate(LANGUAGE_CODES, start=1)
    ]


def tr(language: str, key: str, **kwargs: object) -> str:
    code = normalize_language(language)
    template = MESSAGES.get(code, {}).get(key) or MESSAGES["en"][key]
    return template.format(**kwargs)
