from __future__ import annotations

import os


LANGUAGE_CODES = ("en", "ko", "ja", "zh")

_LANGUAGE_ALIASES = {
    "": "en",
    "en": "en",
    "eng": "en",
    "english": "en",
    "ko": "ko",
    "kr": "ko",
    "kor": "ko",
    "korean": "ko",
    "한국어": "ko",
    "ja": "ja",
    "jp": "ja",
    "jpn": "ja",
    "japanese": "ja",
    "日本語": "ja",
    "zh": "zh",
    "cn": "zh",
    "zho": "zh",
    "chi": "zh",
    "chinese": "zh",
    "中文": "zh",
    "简体中文": "zh",
}

LANGUAGE_NAMES = {
    "en": "English",
    "ko": "한국어",
    "ja": "日本語",
    "zh": "中文",
}

MESSAGES = {
    "en": {
        "menu_hint": "Use ↑/↓, Space/Enter, or a number. Colors are not required.",
        "menu_hint_multi": "↑/↓ to move, Space or a number to tick, Enter when done. Colors are not required.",
        "recommended": "recommended",
        "select": "Select",
        "select_multi": "Numbers, comma-separated (Enter keeps the ticked ones)",
        "invalid_selection": "Invalid selection. Choose one of: {valid}.",
        "exclusive_selection": "`{label}` cannot be combined with the other choices. Pick it on its own, or leave it out.",
        "invalid_yes_no": "Please answer y or n.",
        "yes": "Yes",
        "no": "No",
        "yes_desc": "Apply this setup step.",
        "no_desc": "Skip this step for now.",
        "setup_title": "OMH setup",
        "setup_subtitle": "Connect OMH workflows to Hermes without changing how you normally work.",
        "install_subtitle": "Refresh the OMH workflow pack.",
        "wizard_subtitle": "Press Enter through the recommended choices for a safe first install. All OMH workflows stay available either way.",
        "tui_identity_prompt": "Use the OH-MY-HERMES themed modern TUI (default: sky-blue)?",
        "tui_identity_note": "Recommended. Sets display.interface=tui, an OMH theme, and display.sections collapsed (thinking, tools, subagents) so bare `omh` and `hermes` open the same branded HUD and a long run does not bury the conversation. Collapsed is not hidden: counts stay visible and a click expands. A section you already set is kept. Switch anytime with `omh theme use <name>`.",
        "maestro_delegation_prompt": "Set up coding delegation (maestro) for the detected {clis} CLI?",
        "maestro_delegation_note": "This only reads local PATH and auth-file presence -- a binary and auth file are prepared evidence, not run evidence, and no CLI is invoked. Run `omh coding executor-readiness --executor <profile>` later to confirm it observed.",
        "maestro_delegation_seeded": "Seeded an empty dispatch-model preference file at {path}.",
        "maestro_delegation_pointers": "Next: route models per work category with `omh coding category-maestro interview` (guided) or `omh coding category-maestro set <profile> <category> <model[:effort]>...` (scriptable); edit `~/.omh/routing/dispatch-models.json` for a per-owner default when no route resolves (opus is a common claude-code choice); run `omh coding executor-skills --profile <profile>` to see its discovered skills, and use the `ulw-maestro` skill to compose the handoff.",
        "maestro_category_prompt": "Walk the Maestro category -> model table now (interview)?",
        "model_chains_interview_prompt": "Walk the per-category model chains now (interview)?",
        "provider_entitlements_note": "Providers Hermes is already linked to (a `hermes auth` login, a `providers:` entry in config.yaml, an API-key name in .env) count on their own and arrive pre-ticked; a key exported only in this shell is offered pre-ticked too, but counts only once you record it. Your answers go to ~/.omh/routing/providers.json on top of that: a row you add or whose kind you change is recorded, a pre-ticked row you untick stops counting, and a subscription CLI can only be named here. Each model list is reordered so the models a counted provider serves come first; nothing is removed, and nothing is called to check.",
        "provider_entitlements_invalid": "The existing ~/.omh/routing/providers.json is not applied ({status}); answering again replaces it.",
        "provider_select_title": "Which AI services do you have an account, key, or login for?",
        "provider_select_intro_1": "Tick every one you can use. Enter accepts the ticked list.",
        "provider_select_intro_2": "Ticked ones were found on this machine, which is a guess and not proof of a working account -- untick anything you cannot really use.",
        "provider_detected_config": "found in your Hermes config",
        "provider_detected_env": "found: {name} is set here",
        "provider_detected_login": "found: logged in through hermes auth",
        "provider_recorded_before": "you recorded this last time",
        "provider_opengateway_desc": "OMH's own gateway; serves the Ultrafast models (opengateway.ai)",
        "provider_skip_label": "Skip -- leave everything as it is",
        "provider_skip_desc": "Nothing is saved: an earlier record stays as it is, and the providers linked to Hermes keep counting and reordering the model lists on their own. Rerun `omh setup` any time to answer.",
        "provider_entitlements_skipped": "Left provider settings alone; the providers linked to Hermes keep counting on their own, and an earlier record stays as it is.",
        "provider_kind_relay": "relays every model family",
        "provider_add_prompt": "Add another provider by name (Enter to skip)",
        "provider_add_rejected": "`{provider}` is already recorded or is not a plain identifier; skipped.",
        "claude_code_dispatch_kept": "Claude Code dispatch model already set in {path}; left as is.",
        "claude_code_dispatch_unreadable": "Could not seed the Claude Code dispatch model: {path} is not a readable omh_dispatch_model_preferences/v1 document; fix or remove it and rerun.",
        "provider_kind_title": "What kind of provider is `{provider}`?",
        "provider_kind_intro": "gateway, openrouter, and opencode relay every model family; any other vendor name serves only that vendor's models; unknown = treat as a gateway.",
        "subscription_cli_prompt": "Do you have a paid subscription on the `{cli}` CLI?",
        "subscription_cli_note": "Hermes itself cannot use a subscription -- it needs an API key -- so this only picks which model the `{cli}` CLI is asked for when OMH hands work to it. It never changes the models Hermes uses. (A Codex login is used by Hermes' own openai-codex provider, so tick that in the list above instead.)",
        "provider_entitlements_recorded": "Recorded provider entitlements at {path}; `omh model-chains show` prints the reordered chains.",
        "claude_code_dispatch_seeded": "Claude Code dispatch model set to {model} in {path} (edit the file to change it).",
        "maestro_category_note": "Per work category (ultrabrain, deep, quick, writing, ...) this decides which model each dispatched CLI unit runs. Enter keeps every current chain; skipping keeps the built-in defaults, and `omh coding category-maestro interview` runs the same walk later.",
        "model_chains_interview_note": "Per work category (ultrabrain, deep, quick, writing, ...) this decides which model Hermes delegates to first and the fall-through order behind it. Enter keeps every current chain; skipping keeps the shipped defaults, and `omh model-chains interview` runs the same walk later.",
        "hermes_home": "Hermes home",
        "hermes_config": "Hermes config",
        "managed_skills": "OMH workflows",
        "status_already_registered": "already registered",
        "status_will_register": "will connect OMH workflows",
        "status_will_create": "will create",
        "invalid_executor": "Invalid default executor: {error}",
        "plugin_note": "The plugin exposes local status context to Hermes without changing workflow behavior by itself.",
        "mcp_host_title": "MCP host",
        "mcp_host_intro": "Choose where OMH should write the local stdio MCP bridge config.",
        "mcp_host_generic_desc": "Only show the portable recipe; do not write a host config file.",
        "mcp_host_codex_desc": "Write the OMH MCP server entry for Codex config.",
        "mcp_host_claude_desc": "Write the OMH MCP server entry for Claude Code config.",
        "mcp_host_opencode_desc": "Write the OMH MCP server entry for OpenCode config.",
        "mcp_host_cursor_desc": "Write the OMH MCP server entry for Cursor config.",
        "scope_title": "Choose setup scope",
        "scope_intro_1": "User scope is best for a personal Hermes profile.",
        "scope_intro_2": "Project scope keeps OMH and Hermes config isolated inside the current repository.",
        "scope_user_label": "User scope",
        "scope_user_desc": "Use ~/.omh and ~/.hermes for this machine user.",
        "scope_project_label": "Project scope",
        "scope_project_desc": "Use ./.omh and ./.hermes so this repository has its own OMH setup.",
        "team_title": "Add an optional visible team role preset?",
        "team_intro_1": "These presets only add visible role names for Hermes collaboration.",
        "team_intro_2": "Skip now unless you want those roles shown in chat; every OMH workflow is still installed.",
        "team_none_label": "No extra team role preset now",
        "team_none_desc": "Recommended for first install. Core skills stay installed; other surfaces remain available through Hermes routing.",
        "advanced_title": "Advanced options",
        "github_star_thanks": "Thanks!",
        "github_star_dry_run": "Dry run only — GitHub star would be recorded here.",
        "github_star_failed": "Could not record the GitHub star: {reason}",
        "github_star_continue": "Continuing setup.",
        "step_install_skills": "Installing OMH workflows",
        "step_register": "Connecting OMH to Hermes",
        "step_plugin": "Installing OMH status helper",
        "step_menubar": "Starting OMH menu bar monitor",
        "step_mcp": "Recording optional tool bridge preference",
        "step_team": "Activating visible team role preset",
        "step_preferences": "Saving coding request preference",
        "step_targets": "Checking Hermes profile",
        "done_skills_installed": "{count} workflow(s) ready",
        "done_skills_ready": "{count} workflow(s) ready",
        "done_profile_packs": "{count} profile pack(s) activated",
        "done_default_executor": "coding preference saved: {executor}",
        "done_mcp_bridge": "tool bridge preference: {status}",
        "done_target_topology": "{count} Hermes profile(s) detected",
        "target_recorded": "Hermes profile checked",
        "model_setup_title": "Hermes model activation",
        "model_setup_scan": "Scanning local model metadata",
        "model_setup_truncated": "truncated: {reasons}",
        "model_setup_no_active": "No compatible recommendation was confirmed; setup completed without model aliases and the owner default remains active.",
        "model_setup_status": "Model activation status: {status}",
        "model_setup_chains_hint": "Per-category chains: `omh model-chains show` prints the current order; `omh model-chains interview` fine-tunes each category.",
        "model_setup_maestro_hint": "Maestro lane (dispatched codex/claude-code units): `omh coding category-maestro show` prints its category -> model table; `omh coding category-maestro interview` fine-tunes it.",
        "model_setup_next": "Model activation next action: {action}",
        "model_setup_confirm_prompt": "Confirm {model} is active now?",
        "model_setup_observed_note": "Discovery classified this candidate as {status}; observation is not confirmation.",
        "model_setup_preview_title": "Hermes model alias preview",
        "model_setup_collision_prompt": "{collision}. Replace this existing alias?",
        "model_setup_apply_prompt": "Apply the reviewed Hermes model-alias preview?",
        "skip_by_flag": "skipped by {flag}",
        "setup_complete": "OMH setup complete.",
        "setup_preview_complete": "OMH setup preview complete.",
        "install_complete": "OMH {label} complete.",
        "install_preview_complete": "OMH {label} preview complete.",
        "summary": "Summary",
        "next": "Next",
        "setup_scope": "Install location: {scope}",
        "setup_scope_user": "this user account",
        "setup_scope_project": "this project folder",
        "setup_scope_custom": "custom paths",
        "setup_install_mode": "Workflow source: {mode}",
        "setup_install_mode_managed_skills": "OMH managed workflows",
        "setup_mcp_mode": "Advanced tool bridge: {mode}",
        "setup_mcp_mode_none": "not enabled",
        "setup_mcp_mode_bridge_requested": "preference recorded",
        "setup_mcp_mode_host_config_written": "host config written",
        "setup_mcp_mode_host_config_unchanged": "host config already ready",
        "setup_mcp_mode_host_config_planned": "host config planned",
        "setup_status": "Status: {status}",
        "setup_status_configured": "ready; restart or reload Hermes to use OMH in chat",
        "setup_status_dry_run": "preview only; no files changed",
        "setup_status_skills_only": "workflows ready; Hermes connection skipped",
        "command_path_found": "Terminal command: omh found at {path}",
        "command_path_missing": "Terminal command: omh is not on PATH for this shell.",
        "command_path_missing_next": "Use the absolute command path printed by the installer, or add that directory to PATH.",
        "skills_line": "OMH workflows: {count} ready at {path}",
        "registration_configured": "Hermes connection: ready in {path}. Restart or reload Hermes Agent to see OMH in chat.",
        "registration_dry_run": "Hermes connection: preview only; no files changed.",
        "registration_skipped": "Hermes connection: skipped by --skip-apply.",
        "registration_unknown": "Hermes connection: {status}",
        "apply_line": "Hermes connection detail: {message}",
        "default_handoff": "Coding requests: {summary}",
        "default_handoff_pin_hint": "Tip: pin a durable owner anytime with `omh setup --default-executor <name>`.",
        "setup_profile": "Advanced routing detail: {selected}",
        "target_topology": "Hermes profile check: {count} profile(s) detected.",
        "setup_providers_line": "Model providers: {providers} count; each model list puts the models they serve first.",
        "setup_providers_line_one": "Model providers: {providers} counts; each model list puts the models it serves first.",
        "setup_providers_none": "Model providers: none linked to Hermes or recorded yet, so every model counts as served. Link one (`hermes auth`, a `providers:` entry) or run `omh setup` interactively to record one.",
        "setup_providers_invalid": "Model providers: {path} is ignored ({status}); its recorded kinds are dropped and any providers it excluded count again until it is repaired. Counting: {providers}.",
        "plugin_bridge": "OMH status helper: {status}",
        "memory_provider_on": "Memory: OMH remembers across sessions and tidies up on its own.",
        "memory_provider_other": "Memory: Hermes is using {provider}, so OMH memory stays off.",
        "menubar_helper": "OMH menu bar: {status}",
        "team_activated": "Visible team preset: {count} profile pack(s) activated.",
        "team_none": "Visible team preset: none selected; OMH workflows are still available.",
        "setup_next_dry": "Rerun without `--dry-run` to install the workflows and connect them to Hermes.",
        "setup_next_reload": "Restart or reload Hermes Agent, then try this in Hermes chat:",
        "setup_next_prompt": "Ask Hermes: I want to safely add a feature to this repo.",
        "setup_next_verify": "If Hermes cannot see OMH yet, run `omh doctor` and restart or reload Hermes again.",
        "hermes_profiles_synced": "Bot profiles: {summary}. Restart Hermes Desktop for bot chats to reload skills.",
        "hermes_profiles_uninstalled": "Bot profiles: {summary}. Restart Hermes Desktop so bot chats drop the removed skills.",
        "setup_next_chains": "Recommended: tune the per-category model chains — `omh model-chains show` prints the current state, `omh model-chains interview` walks each category.",
        "machine_readable": "For machine-readable output, rerun with `--json`.",
        "source": "Source: {source}",
        "source_builtin": "installed command package (builtin)",
        "release_channel": "Release channel: {channel}",
        "package_url": "Package URL: {url}",
        "recorded_package_url": "Recorded package URL: {url}",
        "release_version_change": "Release version: {change}",
        "release_source_ref_change": "Source ref: {change}",
        "release_update_status": "Release state: {status}",
        "command_package_update_line": "OMH command: {change} (updated)",
        "command_package_not_updated_line": "OMH command: not updated (workflows only)",
        "update_command_next": "To update the `omh` command itself, run: {command}",
        "state_log": "State log: {path} ({entry})",
        "skill_profile_retained_line": "Skill profile: core requested, but {count} full-only skill(s) are still installed and still cost per-turn context. Installs never delete skills; run `{command}` to shrink explicitly.",
        "install_next_dry": "Rerun without `--dry-run` to refresh the OMH workflows.",
        "install_next": "Run `omh setup` to connect OMH workflows to Hermes, or `omh doctor` to verify health.",
        "update_next": "Run `omh doctor` to verify health; run `omh setup` only if registration needs repair.",
        "tui_verdict_ready": "OMH TUI: ready. Restart any running Hermes session to apply; both `omh` and `hermes` now open the styled TUI.",
        "tui_verdict_blocked": "OMH TUI: this machine still shows stock Hermes until the items below are fixed:",
        "tui_verdict_unknown": "OMH TUI: no Hermes install found under the Hermes home; cannot judge the TUI from here.",
        "tui_verdict_next": "Fix now: run `{command}`, then restart Hermes.",
        "update_card_previous_release": "Previous release: {release}",
        "update_card_installed_release": "Installed release: {release}",
        "update_card_available_release": "Available release: {release}",
        "update_card_install_method": "Install method: {source}",
        "update_card_release_notes": "Release notes:",
        "update_card_release_preview": "Release preview:",
        "update_card_workflows_refreshed": "Workflows refreshed: {count}",
        "update_card_workflow_content_changed": "Workflow content: changed",
        "update_card_workflow_content_unchanged": "Workflow content: unchanged",
        "update_card_workflows_to_refresh": "Workflows to refresh: {count}",
        "update_card_command_updated": "Command package: updated",
        "update_card_command_unchanged": "Command package: unchanged (workflows only)",
        "update_card_command_preview": "Command package: unchanged (preview only)",
        "update_card_release_not_recorded": "not recorded",
        "update_card_title": "Oh-My-Hermes Update",
        "update_card_rollback_title": "Oh-My-Hermes Rollback",
        "update_card_restored_release": "Restored release: {release}",
        "update_rollback_complete": "OMH rollback complete: the known-good generation is active again.",
        "doctor_complete": "OMH doctor complete.",
        "doctor_needs_attention": "OMH doctor needs attention.",
        "doctor_status": "Status: {status}",
        "doctor_status_ok": "ok",
        "doctor_status_needs_attention": "needs attention",
        "doctor_checks": "Checks: {passing}/{total} passing",
        "doctor_issue_counts": "Issues: {blocking} blocking, {warnings} warning(s)",
        "doctor_build_identity": "Build identity: {identity}",
        "doctor_group_managed_skills": "Managed skills",
        "doctor_group_runtime": "Runtime state",
        "doctor_group_hermes_registration": "Hermes registration",
        "doctor_group_targets": "Hermes targets",
        "doctor_group_model_routing": "Model routing",
        "doctor_group_optional_surfaces": "Optional surfaces",
        "doctor_group_command": "Command availability",
        "doctor_group_status_ok": "ok",
        "doctor_group_status_warning": "warning",
        "doctor_group_status_needs_attention": "needs attention",
        "doctor_observation_boundaries": "Observation boundaries",
        "doctor_plugin_bridge_ready": "Plugin bridge: import/register smoke passed against OMH's fake context.",
        "doctor_plugin_bridge_needs_attention": "Plugin bridge: needs repair; run `omh setup`, then `omh doctor` again.",
        "doctor_plugin_bridge_not_installed": "Plugin bridge: not installed; OMH still works through Hermes skills.",
        "doctor_plugin_loader_observed": "Hermes loader: isolated real-loader registration observed.",
        "doctor_plugin_loader_not_observed": "Hermes loader: not observed; fake-context smoke is not host registration evidence.",
        "doctor_plugin_runtime_observed": "Hermes runtime: live plugin load/use observed by the host.",
        "doctor_plugin_runtime_historical": "Hermes runtime: only historical plugin activity is recorded; observe a fresh host event before claiming it is active now.",
        "doctor_plugin_runtime_not_observed": "Hermes runtime: not observed yet; restart or reload Hermes before claiming chat visibility or native plugin use.",
        "doctor_structural_search_present": "Structural search: ast-grep resolved on PATH; presence only, OMH did not execute it.",
        "doctor_structural_search_absent": "Structural search: ast-grep not on PATH; code exploration continues with grep/ripgrep.",
        "doctor_default_next_action": "Open Hermes Agent and try: Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "doctor_fix": "Fix",
        "doctor_boundary": "Boundary: restart or reload Hermes before treating chat visibility as observed.",
        "config_external_dir_already_present": "already configured",
        "config_created_skills_external_dirs": "Hermes can now find OMH workflows",
        "config_appended_skills_external_dirs": "Hermes can now find OMH workflows",
        "config_expanded_inline_external_dirs": "Hermes can now find OMH workflows",
        "config_inserted_skills_external_dirs": "Hermes can now find OMH workflows",
        "config_added_external_dir": "Hermes can now find OMH workflows",
        "config_external_dir_absent": "already removed",
        "config_removed_external_dir": "removed OMH skills directory",
        "uninstall_title": "OMH uninstall",
        "uninstall_subtitle": "Remove OMH-managed local state and Hermes integration files.",
        "uninstall_complete": "OMH uninstall complete.",
        "uninstall_preview_complete": "OMH uninstall preview complete.",
        "uninstall_scope_all": "full cleanup",
        "uninstall_scope_registration": "registration only",
        "uninstall_scope_files": "registration and managed ~/.omh files",
        "uninstall_config": "Hermes registration: {message}",
        "uninstall_config_reversed": "Config keys reversed: {keys}",
        "uninstall_config_would_reverse": "Config keys to reverse: {keys}",
        "uninstall_config_kept": "Config key kept: {config_key} ({detail})",
        "uninstall_config_partial": "Config key partly kept: {config_key} — your value(s) for {kept} stayed.",
        "uninstall_config_unrecorded": "Config key left in place: {config_key} — no record that OMH wrote it, and its value is also a valid user choice.",
        "uninstall_removed": "Removed: {count} path(s)",
        "uninstall_would_remove": "Would remove: {count} path(s)",
        "uninstall_none": "Nothing to remove.",
        "uninstall_command_removed": "Command package: removed {count} installer-managed path(s).",
        "uninstall_command_would_remove": "Command package: would remove {count} installer-managed path(s).",
        "uninstall_command_kept": "Command package: not removed because this `omh` is not running from an installer-managed OMH venv.",
        "uninstall_command_still_available": "If `omh` still runs after uninstall, the command package is still on PATH; remove it with the installer-managed venv, pip, or pipx that installed it.",
        "scope": "Scope",
        "kept": "Kept",
    },
    "ko": {
        "menu_hint": "↑/↓, Space/Enter, 숫자로 선택할 수 있습니다. 색상 없이도 동작합니다.",
        "menu_hint_multi": "↑/↓로 이동, Space나 숫자로 선택/해제, 끝나면 Enter. 색상 없이도 동작합니다.",
        "recommended": "추천",
        "select": "선택",
        "select_multi": "숫자를 쉼표로 구분해 입력하세요(Enter는 선택된 항목 유지)",
        "invalid_selection": "잘못된 선택입니다. 다음 중 하나를 선택하세요: {valid}.",
        "exclusive_selection": "`{label}`은 다른 항목과 함께 선택할 수 없습니다. 이 항목만 선택하거나 제외하세요.",
        "invalid_yes_no": "y 또는 n으로 답해주세요.",
        "yes": "예",
        "no": "아니요",
        "yes_desc": "이 설정 단계를 적용합니다.",
        "no_desc": "지금은 이 단계를 건너뜁니다.",
        "setup_title": "OMH 설정",
        "setup_subtitle": "평소 쓰는 Hermes 흐름은 그대로 두고 OMH 워크플로를 연결합니다.",
        "install_subtitle": "OMH 워크플로 팩을 갱신합니다.",
        "wizard_subtitle": "첫 설치라면 추천값에서 Enter만 눌러도 안전합니다. 어떤 선택을 해도 OMH 워크플로는 계속 사용할 수 있습니다.",
        "tui_identity_prompt": "OH-MY-HERMES 테마 modern TUI를 사용하시겠습니까? (기본값: 하늘색)",
        "tui_identity_note": "권장값입니다. display.interface=tui, OMH 테마, 그리고 display.sections를 collapsed(thinking, tools, subagents)로 설정해 `omh`와 `hermes`가 같은 브랜드 HUD를 열고 긴 실행에서도 대화가 묻히지 않게 합니다. collapsed는 hidden이 아니라 개수는 그대로 보이고 클릭하면 펼쳐집니다. 이미 지정한 섹션 값은 유지합니다. 테마는 언제든 `omh theme use <name>`으로 바꿀 수 있습니다.",
        "maestro_delegation_prompt": "감지된 {clis} CLI에 대해 코딩 위임(maestro)을 설정하시겠습니까?",
        "maestro_delegation_note": "로컬 PATH와 인증 파일 존재 여부만 확인합니다 -- 바이너리와 인증 파일은 준비된(prepared) 근거일 뿐 실행된(observed) 근거가 아니며, 어떤 CLI도 실행하지 않습니다. 이후 `omh coding executor-readiness --executor <profile>`을 실행해 관찰된 상태를 확인하세요.",
        "maestro_delegation_seeded": "{path}에 빈 dispatch-model 선호 파일을 생성했습니다.",
        "maestro_delegation_pointers": "다음 단계: 작업 카테고리별 모델 라우팅은 `omh coding category-maestro interview`(대화형) 또는 `omh coding category-maestro set <profile> <category> <model[:effort]>...`(스크립트)로 설정하세요. 라우트가 없을 때의 소유자별 기본 모델은 `~/.omh/routing/dispatch-models.json`을 직접 편집합니다(claude-code는 opus를 흔히 씁니다). `omh coding executor-skills --profile <profile>`로 발견된 스킬을 확인하고, 핸드오프 구성에는 `ulw-maestro` 스킬을 사용하세요.",
        "maestro_category_prompt": "지금 Maestro 카테고리 -> 모델 테이블을 설정하시겠습니까(인터뷰)?",
        "model_chains_interview_prompt": "지금 카테고리별 모델 체인을 설정하시겠습니까(인터뷰)?",
        "provider_entitlements_note": "Hermes에 이미 연결된 프로바이더(`hermes auth` 로그인, config.yaml의 `providers:` 항목, .env의 API 키 이름)는 답하지 않아도 그대로 집계되며 미리 선택된 채로 나타납니다. 이 셸에만 내보낸 키도 미리 선택된 채로 제안되지만, 기록해야 비로소 집계됩니다. 답변은 그 위에 ~/.omh/routing/providers.json으로 저장됩니다. 추가하거나 종류를 바꾼 행은 기록되고, 미리 선택된 행을 해제하면 집계에서 빠지며, 구독 CLI는 여기서만 지정할 수 있습니다. 각 모델 목록은 집계된 프로바이더가 서빙하는 모델이 앞에 오도록 재정렬됩니다. 항목이 삭제되지는 않으며, 확인을 위해 아무것도 호출하지 않습니다.",
        "provider_entitlements_invalid": "기존 ~/.omh/routing/providers.json은 적용되지 않습니다({status}). 다시 답하면 대체됩니다.",
        "provider_select_title": "계정, 키, 로그인을 보유한 AI 서비스는 무엇입니까?",
        "provider_select_intro_1": "사용할 수 있는 항목을 모두 선택하세요. Enter를 누르면 선택된 목록이 그대로 적용됩니다.",
        "provider_select_intro_2": "선택된 항목은 이 머신에서 발견된 것으로, 계정이 실제로 동작한다는 증거가 아닌 추정입니다. 실제로 쓸 수 없는 항목은 해제하세요.",
        "provider_detected_config": "Hermes 설정에서 발견",
        "provider_detected_env": "발견: {name}가 여기에 설정돼 있습니다",
        "provider_detected_login": "발견: hermes auth로 로그인돼 있습니다",
        "provider_recorded_before": "지난번에 기록한 항목",
        "provider_opengateway_desc": "OMH 자체 게이트웨이. Ultrafast 모델을 서빙합니다(opengateway.ai)",
        "provider_skip_label": "건너뛰기 -- 지금 설정을 그대로 두기",
        "provider_skip_desc": "아무것도 저장하지 않습니다. 이전 기록은 그대로 남고, Hermes에 연결된 프로바이더는 계속 집계되어 모델 목록을 스스로 재정렬합니다. 언제든 `omh setup`을 다시 실행해 답할 수 있습니다.",
        "provider_entitlements_skipped": "프로바이더 설정을 그대로 두었습니다. Hermes에 연결된 프로바이더는 계속 집계되며, 이전 기록도 그대로 남습니다.",
        "provider_kind_relay": "모든 모델 패밀리를 중계",
        "provider_add_prompt": "다른 프로바이더를 이름으로 추가하세요(Enter는 건너뛰기)",
        "provider_add_rejected": "`{provider}`는 이미 기록됐거나 단순 식별자가 아닙니다. 건너뜁니다.",
        "claude_code_dispatch_kept": "{path}에 Claude Code 디스패치 모델이 이미 설정돼 있어 그대로 둡니다.",
        "claude_code_dispatch_unreadable": "Claude Code 디스패치 모델을 시드하지 못했습니다: {path}가 읽을 수 있는 omh_dispatch_model_preferences/v1 문서가 아닙니다. 고치거나 삭제한 뒤 다시 실행하세요.",
        "provider_kind_title": "`{provider}`는 어떤 종류의 프로바이더입니까?",
        "provider_kind_intro": "gateway, openrouter, opencode는 모든 모델 패밀리를 중계하고, 그 밖의 벤더 이름은 해당 벤더 모델만 서빙하며, unknown은 gateway로 취급합니다.",
        "subscription_cli_prompt": "`{cli}` CLI에 유료 구독이 있습니까?",
        "subscription_cli_note": "Hermes 자체는 구독을 쓸 수 없고 API 키가 필요합니다. 그래서 이 답변은 OMH가 `{cli}` CLI에 작업을 넘길 때 요청할 모델만 정하며, Hermes가 쓰는 모델은 바꾸지 않습니다. (Codex 로그인은 Hermes의 openai-codex 프로바이더가 쓰므로 위 목록에서 선택하세요.)",
        "provider_entitlements_recorded": "{path}에 프로바이더 보유 정보를 기록했습니다. `omh model-chains show`로 재정렬된 체인을 확인하세요.",
        "claude_code_dispatch_seeded": "{path}의 Claude Code 디스패치 모델을 {model}로 설정했습니다(파일을 편집해 변경).",
        "maestro_category_note": "작업 카테고리(ultrabrain, deep, quick, writing, ...)별로 디스패치되는 CLI 유닛이 어떤 모델로 실행될지 결정합니다. Enter는 현재 체인을 유지하고, 건너뛰면 내장 기본값이 유지되며, 나중에 `omh coding category-maestro interview`로 같은 설정을 할 수 있습니다.",
        "model_chains_interview_note": "작업 카테고리(ultrabrain, deep, quick, writing, ...)별로 Hermes가 먼저 위임할 모델과 그 뒤의 폴백 순서를 결정합니다. Enter는 현재 체인을 유지하고, 건너뛰면 기본 체인이 유지되며, 나중에 `omh model-chains interview`로 같은 설정을 할 수 있습니다.",
        "hermes_home": "Hermes 홈",
        "hermes_config": "Hermes 설정",
        "managed_skills": "OMH 워크플로",
        "status_already_registered": "이미 등록됨",
        "status_will_register": "OMH 워크플로 연결 예정",
        "status_will_create": "생성 예정",
        "invalid_executor": "기본 실행자 값이 올바르지 않습니다: {error}",
        "plugin_note": "플러그인은 워크플로 동작 자체를 바꾸지 않고 Hermes에 로컬 상태 맥락을 제공합니다.",
        "mcp_host_title": "MCP 호스트",
        "mcp_host_intro": "OMH가 로컬 stdio MCP 브리지 설정을 어디에 쓸지 고릅니다.",
        "mcp_host_generic_desc": "이식 가능한 recipe만 보여주고 호스트 설정 파일은 쓰지 않습니다.",
        "mcp_host_codex_desc": "Codex 설정에 OMH MCP 서버 항목을 씁니다.",
        "mcp_host_claude_desc": "Claude Code 설정에 OMH MCP 서버 항목을 씁니다.",
        "mcp_host_opencode_desc": "OpenCode 설정에 OMH MCP 서버 항목을 씁니다.",
        "mcp_host_cursor_desc": "Cursor 설정에 OMH MCP 서버 항목을 씁니다.",
        "scope_title": "설정 범위 선택",
        "scope_intro_1": "사용자 범위는 개인 Hermes 프로필에 가장 적합합니다.",
        "scope_intro_2": "프로젝트 범위는 현재 저장소 안에 OMH와 Hermes 설정을 격리합니다.",
        "scope_user_label": "사용자 범위",
        "scope_user_desc": "이 사용자/기기에서 ~/.omh 와 ~/.hermes 를 사용합니다.",
        "scope_project_label": "프로젝트 범위",
        "scope_project_desc": "이 저장소만의 OMH 설정을 위해 ./.omh 와 ./.hermes 를 사용합니다.",
        "team_title": "선택형 보이는 팀 역할 프리셋을 추가할까요?",
        "team_intro_1": "이 프리셋은 Hermes 협업에 보이는 역할 이름만 추가합니다.",
        "team_intro_2": "채팅에서 그 역할을 보이고 싶을 때만 선택하세요. 모든 OMH 워크플로는 계속 설치됩니다.",
        "team_none_label": "지금은 추가 팀 역할 프리셋 없음",
        "team_none_desc": "첫 설치에 추천합니다. 핵심 스킬은 설치되고, 나머지 surface는 Hermes 라우팅으로 사용할 수 있습니다.",
        "advanced_title": "고급 옵션",
        "github_star_thanks": "고마워요!",
        "github_star_dry_run": "dry-run입니다 — 여기서는 GitHub star를 기록하지 않습니다.",
        "github_star_failed": "GitHub star를 기록하지 못했습니다: {reason}",
        "github_star_continue": "setup을 계속 진행합니다.",
        "step_install_skills": "OMH 워크플로 설치",
        "step_register": "Hermes에 OMH 연결",
        "step_plugin": "OMH 상태 도우미 설치",
        "step_menubar": "OMH 메뉴바 모니터 시작",
        "step_mcp": "선택형 도구 브리지 선호 기록",
        "step_team": "보이는 팀 역할 프리셋 활성화",
        "step_preferences": "코딩 요청 기본값 저장",
        "step_targets": "Hermes 프로필 확인",
        "done_skills_installed": "{count}개 워크플로 준비 완료",
        "done_skills_ready": "{count}개 워크플로 준비 완료",
        "done_profile_packs": "{count}개 프로필 팩 활성화",
        "done_default_executor": "코딩 기본값 저장: {executor}",
        "done_mcp_bridge": "도구 브리지 선호: {status}",
        "done_target_topology": "{count}개 Hermes 프로필 감지",
        "target_recorded": "Hermes 프로필 확인 완료",
        "model_setup_title": "Hermes 모델 활성화",
        "model_setup_scan": "로컬 모델 메타데이터 검사",
        "model_setup_truncated": "일부만 검사됨: {reasons}",
        "model_setup_no_active": "호환되는 추천 모델이 확인되지 않았습니다. 모델 별칭을 쓰지 않고 setup을 완료했으며 owner 기본 모델을 유지합니다.",
        "model_setup_status": "모델 활성화 상태: {status}",
        "model_setup_chains_hint": "카테고리별 체인: `omh model-chains show`로 현재 순서를 보고, `omh model-chains interview`로 카테고리별로 조정하세요.",
        "model_setup_maestro_hint": "Maestro 레인(디스패치되는 codex/claude-code 유닛): `omh coding category-maestro show`로 카테고리 -> 모델 테이블을 확인하고, `omh coding category-maestro interview`로 조정하세요.",
        "model_setup_next": "모델 활성화 다음 작업: {action}",
        "model_setup_confirm_prompt": "{model} 모델이 현재 활성 상태인지 확인할까요?",
        "model_setup_observed_note": "발견 결과는 이 후보를 {status}(으)로 분류했습니다. 관측 기록은 활성 확인이 아닙니다.",
        "model_setup_preview_title": "Hermes 모델 별칭 미리보기",
        "model_setup_collision_prompt": "{collision}. 이 기존 별칭을 바꿀까요?",
        "model_setup_apply_prompt": "검토한 Hermes 모델 별칭 미리보기를 적용할까요?",
        "skip_by_flag": "{flag} 때문에 건너뜀",
        "setup_complete": "OMH 설정이 완료되었습니다.",
        "setup_preview_complete": "OMH 설정 미리보기가 완료되었습니다.",
        "install_complete": "OMH {label} 완료.",
        "install_preview_complete": "OMH {label} 미리보기 완료.",
        "summary": "요약",
        "next": "다음",
        "setup_scope": "설치 위치: {scope}",
        "setup_scope_user": "이 사용자 계정",
        "setup_scope_project": "이 프로젝트 폴더",
        "setup_scope_custom": "사용자 지정 경로",
        "setup_install_mode": "워크플로 소스: {mode}",
        "setup_install_mode_managed_skills": "OMH 관리 워크플로",
        "setup_mcp_mode": "고급 도구 브리지: {mode}",
        "setup_mcp_mode_none": "사용 안 함",
        "setup_mcp_mode_bridge_requested": "선호 기록됨",
        "setup_mcp_mode_host_config_written": "호스트 설정 작성됨",
        "setup_mcp_mode_host_config_unchanged": "호스트 설정 이미 준비됨",
        "setup_mcp_mode_host_config_planned": "호스트 설정 예정",
        "setup_status": "상태: {status}",
        "setup_status_configured": "준비됨; Hermes를 재시작하거나 다시 불러오면 채팅에서 OMH를 쓸 수 있습니다",
        "setup_status_dry_run": "미리보기만 수행; 파일 변경 없음",
        "setup_status_skills_only": "워크플로 준비 완료; Hermes 연결은 건너뜀",
        "command_path_found": "터미널 명령어: omh가 {path}에서 발견되었습니다.",
        "command_path_missing": "터미널 명령어: 이 shell의 PATH에서 omh를 찾을 수 없습니다.",
        "command_path_missing_next": "설치기가 출력한 절대 경로를 사용하거나, 그 디렉터리를 PATH에 추가하세요.",
        "skills_line": "OMH 워크플로: {path}에 {count}개 준비됨",
        "registration_configured": "Hermes 연결: {path}에 준비됨. Hermes Agent를 재시작하거나 다시 불러오면 채팅에서 OMH가 보입니다.",
        "registration_dry_run": "Hermes 연결: 미리보기만 수행; 파일 변경 없음.",
        "registration_skipped": "Hermes 연결: --skip-apply로 건너뜀.",
        "registration_unknown": "Hermes 연결: {status}",
        "apply_line": "Hermes 연결 상세: {message}",
        "default_handoff": "코딩 요청: {summary}",
        "default_handoff_pin_hint": "팁: `omh setup --default-executor <이름>` 으로 언제든 기본 코딩 에이전트를 고정할 수 있습니다.",
        "setup_profile": "고급 라우팅 상세: {selected}",
        "target_topology": "Hermes 프로필 확인: {count}개 프로필 감지.",
        "setup_providers_line": "모델 프로바이더: {providers} 집계됨. 각 모델 목록은 이들이 서빙하는 모델을 앞에 둡니다.",
        "setup_providers_line_one": "모델 프로바이더: {providers} 집계됨. 각 모델 목록은 이 프로바이더가 서빙하는 모델을 앞에 둡니다.",
        "setup_providers_none": "모델 프로바이더: Hermes에 연결되거나 기록된 것이 아직 없어 모든 모델이 서빙 가능으로 집계됩니다. `hermes auth`나 `providers:` 항목으로 연결하거나 `omh setup`을 대화형으로 실행해 기록하세요.",
        "setup_providers_invalid": "모델 프로바이더: {path}은(는) 무시됩니다({status}). 복구할 때까지 기록된 종류는 버려지고, 제외했던 프로바이더가 있다면 다시 집계됩니다. 현재 집계: {providers}.",
        "plugin_bridge": "OMH 상태 도우미: {status}",
        "memory_provider_on": "기억: OMH가 세션을 넘겨 기억하고 알아서 정리합니다.",
        "memory_provider_other": "기억: Hermes가 {provider}을(를) 쓰고 있어 OMH 기억은 꺼져 있습니다.",
        "menubar_helper": "OMH 메뉴바: {status}",
        "team_activated": "보이는 팀 프리셋: {count}개 프로필 팩 활성화.",
        "team_none": "보이는 팀 프리셋: 선택 안 함. OMH 워크플로는 계속 사용할 수 있습니다.",
        "setup_next_dry": "`--dry-run` 없이 다시 실행하면 워크플로를 설치하고 Hermes에 연결합니다.",
        "setup_next_reload": "Hermes Agent를 재시작하거나 다시 불러온 뒤 Hermes 채팅에서 시도하세요:",
        "setup_next_prompt": "Hermes에게 말해보세요: 이 저장소에 기능을 안전하게 추가하고 싶어요.",
        "setup_next_verify": "Hermes가 아직 OMH를 못 보면 `omh doctor`를 실행하고 Hermes를 다시 시작/불러오세요.",
        "hermes_profiles_synced": "봇 프로필: {summary}. 봇 채팅이 스킬을 다시 읽으려면 Hermes Desktop을 재시작하세요.",
        "hermes_profiles_uninstalled": "봇 프로필: {summary}. 봇 채팅에 제거된 스킬을 반영하려면 Hermes Desktop을 재시작하세요.",
        "setup_next_chains": "권장: 카테고리별 모델 체인을 맞춰보세요 — `omh model-chains show`로 현재 상태를 확인하고 `omh model-chains interview`로 카테고리별로 설정합니다.",
        "machine_readable": "기계가 읽는 출력이 필요하면 `--json`으로 다시 실행하세요.",
        "source": "소스: {source}",
        "source_builtin": "설치된 명령 패키지(builtin)",
        "release_channel": "릴리즈 채널: {channel}",
        "package_url": "패키지 URL: {url}",
        "recorded_package_url": "기록된 패키지 URL: {url}",
        "release_version_change": "릴리즈 버전: {change}",
        "release_source_ref_change": "소스 ref: {change}",
        "release_update_status": "릴리즈 상태: {status}",
        "command_package_update_line": "OMH 명령: {change} (업데이트됨)",
        "command_package_not_updated_line": "OMH 명령: 업데이트 안 됨(워크플로만 갱신)",
        "update_command_next": "`omh` 명령 자체를 갱신하려면 실행하세요: {command}",
        "state_log": "상태 로그: {path} ({entry})",
        "skill_profile_retained_line": "스킬 프로필: core를 요청했지만 full 전용 스킬 {count}개가 아직 설치되어 있어 매 턴 컨텍스트 비용이 그대로 듭니다. 설치는 스킬을 삭제하지 않으므로, 줄이려면 `{command}`를 직접 실행하세요.",
        "install_next_dry": "`--dry-run` 없이 다시 실행하면 OMH 워크플로를 갱신합니다.",
        "install_next": "`omh setup`으로 OMH 워크플로를 Hermes에 연결하거나 `omh doctor`로 상태를 확인하세요.",
        "update_next": "`omh doctor`로 상태를 확인하세요. 등록 복구가 필요할 때만 `omh setup`을 실행하세요.",
        "tui_verdict_ready": "OMH TUI: 준비 완료. 실행 중인 Hermes 세션은 재시작해야 적용되며, 이제 `omh`와 `hermes` 모두 스타일 TUI를 엽니다.",
        "tui_verdict_blocked": "OMH TUI: 아래 항목을 해결하기 전까지는 순정 Hermes 화면이 나옵니다:",
        "tui_verdict_unknown": "OMH TUI: Hermes 설치를 찾지 못해 TUI 상태를 판정할 수 없습니다.",
        "tui_verdict_next": "지금 해결: `{command}` 실행 후 Hermes를 재시작하세요.",
        "update_card_previous_release": "이전 릴리즈: {release}",
        "update_card_installed_release": "설치된 릴리즈: {release}",
        "update_card_available_release": "사용 가능한 릴리즈: {release}",
        "update_card_install_method": "설치 방식: {source}",
        "update_card_release_notes": "릴리즈 노트:",
        "update_card_release_preview": "릴리즈 미리보기:",
        "update_card_workflows_refreshed": "워크플로 갱신: {count}개",
        "update_card_workflow_content_changed": "워크플로 내용: 변경됨",
        "update_card_workflow_content_unchanged": "워크플로 내용: 변경 없음",
        "update_card_workflows_to_refresh": "갱신할 워크플로: {count}개",
        "update_card_command_updated": "명령 패키지: 업데이트됨",
        "update_card_command_unchanged": "명령 패키지: 변경 없음(워크플로만 갱신)",
        "update_card_command_preview": "명령 패키지: 변경 없음(미리보기만 수행)",
        "update_card_release_not_recorded": "기록 없음",
        "update_card_title": "Oh-My-Hermes 업데이트",
        "update_card_rollback_title": "Oh-My-Hermes 롤백",
        "update_card_restored_release": "복원된 릴리즈: {release}",
        "update_rollback_complete": "OMH 롤백 완료: 정상 동작하던 세대가 다시 활성화되었습니다.",
        "doctor_complete": "OMH doctor가 완료되었습니다.",
        "doctor_needs_attention": "OMH doctor에 확인이 필요합니다.",
        "doctor_status": "상태: {status}",
        "doctor_status_ok": "정상",
        "doctor_status_needs_attention": "확인 필요",
        "doctor_checks": "검사: {passing}/{total} 통과",
        "doctor_issue_counts": "이슈: 차단 {blocking}개, 경고 {warnings}개",
        "doctor_build_identity": "빌드 식별: {identity}",
        "doctor_group_managed_skills": "관리 스킬",
        "doctor_group_runtime": "런타임 상태",
        "doctor_group_hermes_registration": "Hermes 등록",
        "doctor_group_targets": "Hermes 대상",
        "doctor_group_model_routing": "모델 라우팅",
        "doctor_group_optional_surfaces": "선택형 표면",
        "doctor_group_command": "명령어 사용 가능성",
        "doctor_group_status_ok": "정상",
        "doctor_group_status_warning": "경고",
        "doctor_group_status_needs_attention": "확인 필요",
        "doctor_observation_boundaries": "관측 경계",
        "doctor_plugin_bridge_ready": "플러그인 브리지: OMH 가짜 컨텍스트에서 import/register smoke 통과.",
        "doctor_plugin_bridge_needs_attention": "플러그인 브리지: 복구 필요; `omh setup` 후 `omh doctor`를 다시 실행하세요.",
        "doctor_plugin_bridge_not_installed": "플러그인 브리지: 설치되지 않음. OMH는 Hermes 스킬만으로도 계속 동작합니다.",
        "doctor_plugin_loader_observed": "Hermes 로더: 격리된 실제 로더 등록을 관측했습니다.",
        "doctor_plugin_loader_not_observed": "Hermes 로더: 미관측. 가짜 컨텍스트 smoke는 호스트 등록 증거가 아닙니다.",
        "doctor_plugin_runtime_observed": "Hermes 런타임: 호스트가 실시간 플러그인 로드/사용을 관측했습니다.",
        "doctor_plugin_runtime_historical": "Hermes 런타임: 과거 플러그인 활동만 기록되어 있습니다. 지금 활성 상태라고 말하려면 새 호스트 이벤트가 필요합니다.",
        "doctor_plugin_runtime_not_observed": "Hermes 런타임: 아직 관측 안 됨. 채팅 노출이나 네이티브 플러그인 사용을 주장하기 전에 Hermes를 재시작하거나 다시 불러오세요.",
        "doctor_structural_search_present": "구조 검색: ast-grep이 PATH에서 확인됨. 존재만 확인했으며 OMH가 실행하지는 않았습니다.",
        "doctor_structural_search_absent": "구조 검색: ast-grep이 PATH에 없음. 코드 탐색은 grep/ripgrep으로 계속됩니다.",
        "doctor_default_next_action": "Hermes Agent를 열고 시도하세요: Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "doctor_fix": "수정",
        "doctor_boundary": "경계: Hermes 채팅 노출을 관측된 것으로 보기 전에 Hermes를 재시작하거나 다시 불러오세요.",
        "config_external_dir_already_present": "이미 설정됨",
        "config_created_skills_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_appended_skills_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_expanded_inline_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_inserted_skills_external_dirs": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_added_external_dir": "Hermes가 OMH 워크플로를 찾을 수 있게 됨",
        "config_external_dir_absent": "이미 제거됨",
        "config_removed_external_dir": "OMH 스킬 디렉터리 제거",
        "uninstall_title": "OMH 삭제",
        "uninstall_subtitle": "OMH가 관리하는 로컬 상태와 Hermes 연동 파일을 제거합니다.",
        "uninstall_complete": "OMH 삭제가 완료되었습니다.",
        "uninstall_preview_complete": "OMH 삭제 미리보기가 완료되었습니다.",
        "uninstall_scope_all": "전체 정리",
        "uninstall_scope_registration": "등록만 해제",
        "uninstall_scope_files": "등록과 관리 ~/.omh 파일 삭제",
        "uninstall_config": "Hermes 등록: {message}",
        "uninstall_config_reversed": "되돌린 config 키: {keys}",
        "uninstall_config_would_reverse": "되돌릴 config 키: {keys}",
        "uninstall_config_kept": "유지한 config 키: {config_key} ({detail})",
        "uninstall_config_partial": "일부만 되돌린 config 키: {config_key} — {kept} 값은 그대로 두었습니다.",
        "uninstall_config_unrecorded": "그대로 둔 config 키: {config_key} — OMH가 썼다는 기록이 없고, 사용자가 직접 고른 값일 수도 있습니다.",
        "uninstall_removed": "삭제됨: {count}개 경로",
        "uninstall_would_remove": "삭제 예정: {count}개 경로",
        "uninstall_none": "삭제할 항목이 없습니다.",
        "uninstall_command_removed": "명령 패키지: 설치 관리자가 관리하는 {count}개 경로를 삭제했습니다.",
        "uninstall_command_would_remove": "명령 패키지: 설치 관리자가 관리하는 {count}개 경로를 삭제할 예정입니다.",
        "uninstall_command_kept": "명령 패키지: 이 `omh`가 설치 관리자가 관리하는 OMH venv에서 실행 중이 아니어서 삭제하지 않았습니다.",
        "uninstall_command_still_available": "uninstall 뒤에도 `omh`가 실행된다면 명령 패키지가 아직 PATH에 남아 있는 것입니다. 설치에 사용한 installer-managed venv, pip, 또는 pipx에서 제거하세요.",
        "scope": "범위",
        "kept": "유지됨",
    },
    "ja": {
        "menu_hint": "↑/↓、Space/Enter、または数字で選択できます。色なしでも動作します。",
        "menu_hint_multi": "↑/↓ で移動、Space か数字でチェック、終わったら Enter。色なしでも動作します。",
        "recommended": "推奨",
        "select": "選択",
        "select_multi": "番号をカンマ区切りで入力（Enter はチェック済みを維持）",
        "invalid_selection": "無効な選択です。次から選んでください: {valid}.",
        "exclusive_selection": "`{label}` は他の項目と一緒に選べません。単独で選ぶか、外してください。",
        "invalid_yes_no": "y または n で答えてください。",
        "yes": "はい",
        "no": "いいえ",
        "yes_desc": "このセットアップ手順を適用します。",
        "no_desc": "今回はこの手順をスキップします。",
        "setup_title": "OMH セットアップ",
        "setup_subtitle": "インストール済みの OMH ワークフローをこの Hermes プロファイルに接続します。",
        "install_subtitle": "OMH ワークフローパックを更新します。",
        "wizard_subtitle": "初回インストールなら推奨値のまま Enter で安全に進められます。どの選択でも OMH ワークフローは利用できます。",
        "tui_identity_prompt": "OH-MY-HERMES テーマの modern TUI を使用しますか？（既定: 空色）",
        "tui_identity_note": "推奨です。display.interface=tui、OMH テーマ、および display.sections を collapsed（thinking, tools, subagents）に設定し、`omh` と `hermes` で同じブランド HUD を開き、長い実行でも会話が埋もれないようにします。collapsed は hidden ではなく、件数は表示されたままでクリックで展開できます。すでに設定済みのセクションはそのまま保持されます。テーマは `omh theme use <name>` でいつでも変更できます。",
        "maestro_delegation_prompt": "検出された {clis} CLI 向けにコーディング委任（maestro）を設定しますか？",
        "maestro_delegation_note": "ローカルの PATH と認証ファイルの有無だけを確認します -- バイナリと認証ファイルは prepared（準備済み）な根拠であり observed（観測済み）な根拠ではなく、どの CLI も実行しません。後で `omh coding executor-readiness --executor <profile>` を実行すると観測済みの状態を確認できます。",
        "maestro_delegation_seeded": "{path} に空の dispatch-model 設定ファイルを作成しました。",
        "maestro_delegation_pointers": "次のステップ: 作業カテゴリごとのモデルルーティングは `omh coding category-maestro interview`（対話式）または `omh coding category-maestro set <profile> <category> <model[:effort]>...`（スクリプト）で設定してください。ルートが解決しない場合のオーナーごとの既定モデルは `~/.omh/routing/dispatch-models.json` を直接編集します（claude-code では opus がよく使われます）。`omh coding executor-skills --profile <profile>` で検出済みスキルを確認し、ハンドオフの構成には `ulw-maestro` スキルを使ってください。",
        "maestro_category_prompt": "今すぐ Maestro のカテゴリ -> モデル表を設定しますか（インタビュー）？",
        "model_chains_interview_prompt": "今すぐカテゴリ別のモデルチェーンを設定しますか（インタビュー）？",
        "provider_entitlements_note": "Hermes にすでに連携済みのプロバイダー（`hermes auth` ログイン、config.yaml の `providers:` 項目、.env の API キー名）は答えなくてもそのまま集計され、チェック済みで表示されます。このシェルにだけエクスポートしたキーもチェック済みで提示されますが、記録して初めて集計されます。回答はその上に ~/.omh/routing/providers.json として保存されます。追加した行や種類を変えた行は記録され、チェック済みの行を外すと集計から外れ、サブスクリプション CLI はここでしか指定できません。各モデル一覧は、集計されたプロバイダーが提供するモデルが先頭に来るよう並べ替えられます。項目は削除されず、確認のために何も呼び出しません。",
        "provider_entitlements_invalid": "既存の ~/.omh/routing/providers.json は適用されません（{status}）。再度回答すると置き換えられます。",
        "provider_select_title": "アカウント・キー・ログインを持っている AI サービスはどれですか？",
        "provider_select_intro_1": "使えるものをすべてチェックしてください。Enter でチェック済みの一覧が確定します。",
        "provider_select_intro_2": "チェック済みはこのマシンで見つかったもので、アカウントが実際に動く証拠ではなく推測です。実際に使えないものは外してください。",
        "provider_detected_config": "Hermes の設定で発見",
        "provider_detected_env": "発見: {name} がここに設定されています",
        "provider_detected_login": "発見: hermes auth でログイン済みです",
        "provider_recorded_before": "前回記録した項目",
        "provider_opengateway_desc": "OMH 自身のゲートウェイ。Ultrafast モデルを提供します（opengateway.ai）",
        "provider_skip_label": "スキップ -- 今の設定をそのままにする",
        "provider_skip_desc": "何も保存しません。以前の記録はそのまま残り、Hermes に連携済みのプロバイダーは引き続き集計されてモデル一覧を自動で並べ替えます。いつでも `omh setup` を再実行して答えられます。",
        "provider_entitlements_skipped": "プロバイダー設定はそのままにしました。Hermes に連携済みのプロバイダーは引き続き集計され、以前の記録もそのまま残ります。",
        "provider_kind_relay": "すべてのモデルファミリーを中継",
        "provider_add_prompt": "他のプロバイダーを名前で追加（Enter でスキップ）",
        "provider_add_rejected": "`{provider}` はすでに記録済みか、単純な識別子ではありません。スキップします。",
        "claude_code_dispatch_kept": "{path} に Claude Code のディスパッチモデルが既に設定されているため、そのままにします。",
        "claude_code_dispatch_unreadable": "Claude Code のディスパッチモデルを設定できませんでした: {path} は読み取れる omh_dispatch_model_preferences/v1 文書ではありません。修正または削除して再実行してください。",
        "provider_kind_title": "`{provider}` はどの種類のプロバイダーですか？",
        "provider_kind_intro": "gateway、openrouter、opencode はすべてのモデルファミリーを中継し、その他のベンダー名はそのベンダーのモデルのみを提供し、unknown は gateway として扱います。",
        "subscription_cli_prompt": "`{cli}` CLI の有料サブスクリプションはありますか？",
        "subscription_cli_note": "Hermes 自体はサブスクリプションを使えず API キーが必要です。そのためこの回答は、OMH が `{cli}` CLI に作業を渡すときに要求するモデルを決めるだけで、Hermes が使うモデルは変えません。（Codex のログインは Hermes の openai-codex プロバイダーが使うため、上の一覧でチェックしてください。）",
        "provider_entitlements_recorded": "{path} にプロバイダー保有情報を記録しました。`omh model-chains show` で並べ替え後のチェーンを確認できます。",
        "claude_code_dispatch_seeded": "{path} の Claude Code ディスパッチモデルを {model} に設定しました（変更はファイルを編集）。",
        "maestro_category_note": "作業カテゴリ（ultrabrain、deep、quick、writing など）ごとに、ディスパッチされる CLI ユニットがどのモデルで実行されるかを決めます。Enter は現在のチェーンを維持し、スキップすれば組み込みの既定値のままです。後から `omh coding category-maestro interview` で同じ設定ができます。",
        "model_chains_interview_note": "作業カテゴリ（ultrabrain、deep、quick、writing など）ごとに、Hermes が最初に委譲するモデルとその後のフォールバック順を決めます。Enter は現在のチェーンを維持し、スキップすれば出荷時の既定チェーンのままです。後から `omh model-chains interview` で同じ設定ができます。",
        "hermes_home": "Hermes ホーム",
        "hermes_config": "Hermes 設定",
        "managed_skills": "OMH ワークフロー",
        "status_already_registered": "登録済み",
        "status_will_register": "OMH ワークフローを接続予定",
        "status_will_create": "作成予定",
        "invalid_executor": "既定実行者が無効です: {error}",
        "plugin_note": "プラグインはワークフロー動作自体を変えずに、Hermes にローカル状態の文脈を渡します。",
        "mcp_host_title": "MCP ホスト",
        "mcp_host_intro": "OMH がローカル stdio MCP ブリッジ設定を書き込む先を選びます。",
        "mcp_host_generic_desc": "ポータブルなレシピだけを表示し、ホスト設定ファイルは書き込みません。",
        "mcp_host_codex_desc": "Codex 設定に OMH MCP サーバー項目を書き込みます。",
        "mcp_host_claude_desc": "Claude Code 設定に OMH MCP サーバー項目を書き込みます。",
        "mcp_host_opencode_desc": "OpenCode 設定に OMH MCP サーバー項目を書き込みます。",
        "mcp_host_cursor_desc": "Cursor 設定に OMH MCP サーバー項目を書き込みます。",
        "scope_title": "セットアップスコープを選択",
        "scope_intro_1": "ユーザースコープは個人の Hermes プロファイルに適しています。",
        "scope_intro_2": "プロジェクトスコープは現在のリポジトリ内に OMH と Hermes 設定を分離します。",
        "scope_user_label": "ユーザースコープ",
        "scope_user_desc": "このユーザー/マシンで ~/.omh と ~/.hermes を使います。",
        "scope_project_label": "プロジェクトスコープ",
        "scope_project_desc": "このリポジトリ専用に ./.omh と ./.hermes を使います。",
        "team_title": "表示用チームペルソナを今有効化しますか?",
        "team_intro_1": "これは Hermes 連携で見えるロール名だけを追加します。",
        "team_intro_2": "チャット上でそのロールを見せたい場合だけ選んでください。OMH ワークフローはすべてインストールされます。",
        "team_none_label": "今は追加チームペルソナなし",
        "team_none_desc": "初回インストールに推奨。主要スキルは入り、他の surface は Hermes ルーティングで利用できます。",
        "advanced_title": "詳細オプション",
        "github_star_thanks": "ありがとうございます!",
        "github_star_dry_run": "dry-run のため、ここでは GitHub star を記録しません。",
        "github_star_failed": "GitHub star を記録できませんでした: {reason}",
        "github_star_continue": "セットアップを続行します。",
        "step_install_skills": "OMH ワークフローをインストール",
        "step_register": "OMH を Hermes に接続",
        "step_plugin": "OMH ステータスヘルパーをインストール",
        "step_menubar": "OMH メニューバーモニターを起動",
        "step_mcp": "任意のツールブリッジ設定を記録",
        "step_team": "表示用チームロールプリセットを有効化",
        "step_preferences": "コーディングリクエスト設定を保存",
        "step_targets": "Hermes プロファイルを確認",
        "done_skills_installed": "{count} 個のワークフローを準備しました",
        "done_skills_ready": "{count} 個のワークフローを準備しました",
        "done_profile_packs": "{count} 個のプロファイルパックを有効化しました",
        "done_default_executor": "コーディング設定を保存: {executor}",
        "done_mcp_bridge": "ツールブリッジ設定: {status}",
        "done_target_topology": "{count} 個の Hermes プロファイルを検出",
        "target_recorded": "Hermes プロファイルを確認しました",
        "model_setup_title": "Hermes モデルの有効化",
        "model_setup_scan": "ローカルモデルのメタデータを検査中",
        "model_setup_truncated": "検査が途中で終了: {reasons}",
        "model_setup_no_active": "互換性のある推奨モデルは確認されませんでした。モデルエイリアスを書き込まずに setup を完了し、owner のデフォルトモデルを維持します。",
        "model_setup_status": "モデル有効化ステータス: {status}",
        "model_setup_chains_hint": "カテゴリ別チェーン: `omh model-chains show` で現在の順序を確認し、`omh model-chains interview` でカテゴリごとに調整できます。",
        "model_setup_maestro_hint": "Maestro レーン（ディスパッチされる codex/claude-code ユニット）: `omh coding category-maestro show` でカテゴリ -> モデル表を確認し、`omh coding category-maestro interview` で調整できます。",
        "model_setup_next": "モデル有効化の次の操作: {action}",
        "model_setup_confirm_prompt": "{model} が現在有効であることを確認しますか?",
        "model_setup_observed_note": "検出結果はこの候補を {status} と分類しました。観測記録は有効性の確認ではありません。",
        "model_setup_preview_title": "Hermes モデルエイリアスのプレビュー",
        "model_setup_collision_prompt": "{collision}。この既存エイリアスを置き換えますか?",
        "model_setup_apply_prompt": "確認した Hermes モデルエイリアスのプレビューを適用しますか?",
        "skip_by_flag": "{flag} によりスキップ",
        "setup_complete": "OMH セットアップが完了しました。",
        "setup_preview_complete": "OMH セットアップのプレビューが完了しました。",
        "install_complete": "OMH {label} が完了しました。",
        "install_preview_complete": "OMH {label} のプレビューが完了しました。",
        "summary": "概要",
        "next": "次",
        "setup_scope": "インストール先: {scope}",
        "setup_scope_user": "このユーザーアカウント",
        "setup_scope_project": "このプロジェクトフォルダ",
        "setup_scope_custom": "カスタムパス",
        "setup_install_mode": "ワークフローソース: {mode}",
        "setup_install_mode_managed_skills": "OMH 管理ワークフロー",
        "setup_mcp_mode": "詳細ツールブリッジ: {mode}",
        "setup_mcp_mode_none": "無効",
        "setup_mcp_mode_bridge_requested": "設定を記録済み",
        "setup_mcp_mode_host_config_written": "ホスト設定を書き込み済み",
        "setup_mcp_mode_host_config_unchanged": "ホスト設定は準備済み",
        "setup_mcp_mode_host_config_planned": "ホスト設定を予定",
        "setup_status": "状態: {status}",
        "setup_status_configured": "準備完了。Hermes を再起動または再読み込みするとチャットで OMH を使えます",
        "setup_status_dry_run": "プレビューのみ。ファイルは変更していません",
        "setup_status_skills_only": "ワークフロー準備済み。Hermes 接続はスキップ",
        "command_path_found": "ターミナルコマンド: omh は {path} にあります",
        "command_path_missing": "ターミナルコマンド: この shell の PATH で omh が見つかりません。",
        "command_path_missing_next": "インストーラーが表示した絶対パスを使うか、そのディレクトリを PATH に追加してください。",
        "skills_line": "OMH ワークフロー: {path} に {count} 個を準備済み",
        "registration_configured": "Hermes 接続: {path} に準備済み。Hermes Agent を再起動または再読み込みするとチャットで OMH が見えます。",
        "registration_dry_run": "Hermes 接続: プレビューのみ。ファイルは変更していません。",
        "registration_skipped": "Hermes 接続: --skip-apply によりスキップ。",
        "registration_unknown": "Hermes 接続: {status}",
        "apply_line": "Hermes 接続詳細: {message}",
        "default_handoff": "コーディングリクエスト: {summary}",
        "default_handoff_pin_hint": "ヒント: `omh setup --default-executor <name>` でいつでも既定のコーディングエージェントを固定できます。",
        "setup_profile": "詳細ルーティング: {selected}",
        "target_topology": "Hermes プロファイル確認: {count} 個のプロファイルを検出。",
        "setup_providers_line": "モデルプロバイダー: {providers} を集計。各モデル一覧はこれらが提供するモデルを先頭に置きます。",
        "setup_providers_line_one": "モデルプロバイダー: {providers} を集計。各モデル一覧はこのプロバイダーが提供するモデルを先頭に置きます。",
        "setup_providers_none": "モデルプロバイダー: Hermes に連携済みまたは記録済みのものがまだないため、すべてのモデルが提供可能として集計されます。`hermes auth` や `providers:` 項目で連携するか、`omh setup` を対話式に実行して記録してください。",
        "setup_providers_invalid": "モデルプロバイダー: {path} は無視されます（{status}）。修復するまで、記録された種類は捨てられ、除外していたプロバイダーがあれば再び集計されます。現在の集計: {providers}。",
        "plugin_bridge": "OMH ステータスヘルパー: {status}",
        "memory_provider_on": "記憶: OMH がセッションをまたいで記憶し、自動で整理します。",
        "memory_provider_other": "記憶: Hermes が {provider} を使用中のため、OMH の記憶は無効です。",
        "menubar_helper": "OMH メニューバー: {status}",
        "team_activated": "チームペルソナ: {count} 個のプロファイルパックを有効化。",
        "team_none": "チームペルソナ: 未有効化。OMH ワークフローは引き続き利用できます。",
        "setup_next_dry": "`--dry-run` なしで再実行すると、ワークフローをインストールして Hermes に接続します。",
        "setup_next_reload": "Hermes Agent を再起動または再読み込みし、Hermes チャットで試してください:",
        "setup_next_prompt": "Ask Hermes: I want to safely add a feature to this repo.",
        "setup_next_verify": "Hermes がまだ OMH を見つけられない場合は `omh doctor` を実行し、Hermes を再起動または再読み込みしてください。",
        "hermes_profiles_synced": "Bot プロファイル: {summary}。Bot チャットにスキルを再読み込みさせるには Hermes Desktop を再起動してください。",
        "hermes_profiles_uninstalled": "Bot プロファイル: {summary}。Bot チャットに削除を反映させるには Hermes Desktop を再起動してください。",
        "setup_next_chains": "おすすめ: カテゴリ別モデルチェーンを調整しましょう — `omh model-chains show` で現在の状態を確認し、`omh model-chains interview` でカテゴリごとに設定できます。",
        "machine_readable": "機械可読出力が必要な場合は `--json` を付けて再実行してください。",
        "source": "ソース: {source}",
        "source_builtin": "インストール済みコマンドパッケージ (builtin)",
        "release_channel": "リリースチャンネル: {channel}",
        "package_url": "パッケージ URL: {url}",
        "recorded_package_url": "記録されたパッケージ URL: {url}",
        "release_version_change": "リリースバージョン: {change}",
        "release_source_ref_change": "ソース ref: {change}",
        "release_update_status": "リリース状態: {status}",
        "command_package_update_line": "OMH コマンド: {change} (更新済み)",
        "command_package_not_updated_line": "OMH コマンド: 未更新 (ワークフローのみ)",
        "update_command_next": "`omh` コマンド自体を更新するには実行してください: {command}",
        "state_log": "状態ログ: {path} ({entry})",
        "skill_profile_retained_line": "スキルプロファイル: core を指定しましたが、full 専用スキルが {count} 個インストールされたままで、毎ターンのコンテキスト費用がかかります。インストールはスキルを削除しないため、縮小するには `{command}` を明示的に実行してください。",
        "install_next_dry": "`--dry-run` なしで再実行すると OMH ワークフローを更新します。",
        "install_next": "`omh setup` で OMH ワークフローを Hermes に接続するか、`omh doctor` で状態を確認してください。",
        "update_next": "`omh doctor` で状態を確認してください。登録の修復が必要な場合だけ `omh setup` を実行してください。",
        "tui_verdict_ready": "OMH TUI: 準備完了。実行中の Hermes セッションは再起動で反映され、`omh` と `hermes` の両方がスタイル付き TUI を開きます。",
        "tui_verdict_blocked": "OMH TUI: 以下を解決するまでは標準の Hermes 画面のままです:",
        "tui_verdict_unknown": "OMH TUI: Hermes のインストールが見つからず、TUI の状態を判定できません。",
        "tui_verdict_next": "今すぐ対応: `{command}` を実行して Hermes を再起動してください。",
        "update_card_previous_release": "前回のリリース: {release}",
        "update_card_installed_release": "インストール済みリリース: {release}",
        "update_card_available_release": "利用可能なリリース: {release}",
        "update_card_install_method": "インストール方法: {source}",
        "update_card_release_notes": "リリースノート:",
        "update_card_release_preview": "リリースプレビュー:",
        "update_card_workflows_refreshed": "更新済みワークフロー: {count}",
        "update_card_workflow_content_changed": "ワークフロー内容: 変更あり",
        "update_card_workflow_content_unchanged": "ワークフロー内容: 変更なし",
        "update_card_workflows_to_refresh": "更新するワークフロー: {count}",
        "update_card_command_updated": "コマンドパッケージ: 更新済み",
        "update_card_command_unchanged": "コマンドパッケージ: 変更なし（ワークフローのみ更新）",
        "update_card_command_preview": "コマンドパッケージ: 変更なし（プレビューのみ）",
        "update_card_release_not_recorded": "記録なし",
        "update_card_title": "Oh-My-Hermes アップデート",
        "update_card_rollback_title": "Oh-My-Hermes ロールバック",
        "update_card_restored_release": "復元されたリリース: {release}",
        "update_rollback_complete": "OMH ロールバック完了: 正常だった世代が再び有効になりました。",
        "doctor_complete": "OMH doctor が完了しました。",
        "doctor_needs_attention": "OMH doctor は確認が必要です。",
        "doctor_status": "状態: {status}",
        "doctor_status_ok": "ok",
        "doctor_status_needs_attention": "要確認",
        "doctor_checks": "チェック: {passing}/{total} 合格",
        "doctor_issue_counts": "問題: ブロック {blocking} 件、警告 {warnings} 件",
        "doctor_build_identity": "ビルド識別: {identity}",
        "doctor_group_managed_skills": "管理スキル",
        "doctor_group_runtime": "ランタイム状態",
        "doctor_group_hermes_registration": "Hermes 登録",
        "doctor_group_targets": "Hermes ターゲット",
        "doctor_group_model_routing": "モデルルーティング",
        "doctor_group_optional_surfaces": "任意サーフェス",
        "doctor_group_command": "コマンド利用可否",
        "doctor_group_status_ok": "ok",
        "doctor_group_status_warning": "警告",
        "doctor_group_status_needs_attention": "要確認",
        "doctor_observation_boundaries": "観測境界",
        "doctor_plugin_bridge_ready": "プラグインブリッジ: OMH の偽コンテキストで import/register smoke に合格。",
        "doctor_plugin_bridge_needs_attention": "プラグインブリッジ: 修復が必要です。`omh setup` の後に `omh doctor` を再実行してください。",
        "doctor_plugin_bridge_not_installed": "プラグインブリッジ: 未インストール。OMH は Hermes スキルだけでも動作します。",
        "doctor_plugin_loader_observed": "Hermes ローダー: 隔離した実ローダーで登録を観測しました。",
        "doctor_plugin_loader_not_observed": "Hermes ローダー: 未観測。偽コンテキストの smoke はホスト登録の証拠ではありません。",
        "doctor_plugin_runtime_observed": "Hermes ランタイム: ホストによるライブプラグイン読み込み/使用を観測済み。",
        "doctor_plugin_runtime_historical": "Hermes ランタイム: 過去のプラグイン活動のみ記録されています。現在アクティブと主張する前に新しいホストイベントを観測してください。",
        "doctor_plugin_runtime_not_observed": "Hermes ランタイム: まだ未観測です。チャット表示やネイティブプラグイン使用を主張する前に Hermes を再起動または再読み込みしてください。",
        "doctor_structural_search_present": "構造検索: ast-grep を PATH 上で確認しました。存在確認のみで、OMH は実行していません。",
        "doctor_structural_search_absent": "構造検索: ast-grep は PATH にありません。コード探索は grep/ripgrep で継続します。",
        "doctor_default_next_action": "Hermes Agent を開いて試してください: Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "doctor_fix": "修正",
        "doctor_boundary": "境界: チャット表示を観測済みと扱う前に Hermes を再起動または再読み込みしてください。",
        "config_external_dir_already_present": "すでに設定済み",
        "config_created_skills_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_appended_skills_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_expanded_inline_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_inserted_skills_external_dirs": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_added_external_dir": "Hermes が OMH ワークフローを見つけられるようになりました",
        "config_external_dir_absent": "すでに削除済み",
        "config_removed_external_dir": "OMH スキルディレクトリを削除",
        "uninstall_title": "OMH アンインストール",
        "uninstall_subtitle": "OMH が管理するローカル状態と Hermes 連携ファイルを削除します。",
        "uninstall_complete": "OMH アンインストールが完了しました。",
        "uninstall_preview_complete": "OMH アンインストールのプレビューが完了しました。",
        "uninstall_scope_all": "完全クリーンアップ",
        "uninstall_scope_registration": "登録のみ解除",
        "uninstall_scope_files": "登録と管理 ~/.omh ファイルを削除",
        "uninstall_config": "Hermes 登録: {message}",
        "uninstall_config_reversed": "元に戻した config キー: {keys}",
        "uninstall_config_would_reverse": "元に戻す予定の config キー: {keys}",
        "uninstall_config_kept": "保持した config キー: {config_key} ({detail})",
        "uninstall_config_partial": "一部だけ戻した config キー: {config_key} — {kept} の値はそのままにしました。",
        "uninstall_config_unrecorded": "そのまま残した config キー: {config_key} — OMH が書いた記録がなく、ユーザー自身の選択でもありうる値です。",
        "uninstall_removed": "削除済み: {count} パス",
        "uninstall_would_remove": "削除予定: {count} パス",
        "uninstall_none": "削除する項目はありません。",
        "uninstall_command_removed": "コマンドパッケージ: インストーラー管理の {count} パスを削除しました。",
        "uninstall_command_would_remove": "コマンドパッケージ: インストーラー管理の {count} パスを削除予定です。",
        "uninstall_command_kept": "コマンドパッケージ: この `omh` はインストーラー管理の OMH venv から実行されていないため削除しませんでした。",
        "uninstall_command_still_available": "uninstall 後も `omh` が動く場合、コマンドパッケージがまだ PATH に残っています。インストールに使った installer-managed venv、pip、または pipx から削除してください。",
        "scope": "範囲",
        "kept": "保持",
    },
    "zh": {
        "menu_hint": "可用 ↑/↓、Space/Enter 或数字选择。无颜色也可使用。",
        "menu_hint_multi": "↑/↓ 移动，Space 或数字勾选，完成后按 Enter。无颜色也可使用。",
        "recommended": "推荐",
        "select": "选择",
        "select_multi": "输入编号，用逗号分隔（Enter 保留已勾选项）",
        "invalid_selection": "无效选择。请选择: {valid}.",
        "exclusive_selection": "`{label}` 不能与其他项同时选择。请单独选它，或者不选它。",
        "invalid_yes_no": "请回答 y 或 n。",
        "yes": "是",
        "no": "否",
        "yes_desc": "应用此设置步骤。",
        "no_desc": "暂时跳过此步骤。",
        "setup_title": "OMH 设置",
        "setup_subtitle": "将已安装的 OMH 工作流连接到此 Hermes 配置。",
        "install_subtitle": "刷新 OMH 工作流包。",
        "wizard_subtitle": "首次安装可直接按 Enter 使用推荐值。无论如何选择，OMH 工作流都会保持可用。",
        "tui_identity_prompt": "使用 OH-MY-HERMES 主题的 modern TUI 吗？（默认：天蓝色）",
        "tui_identity_note": "推荐。设置 display.interface=tui、一个 OMH 主题，以及 display.sections 为 collapsed（thinking、tools、subagents），让 `omh` 与 `hermes` 打开同一个品牌 HUD，并且长时间运行时对话不会被淹没。collapsed 不是 hidden：计数仍然可见，点击即可展开。你已经设置过的分区会保留。随时可用 `omh theme use <name>` 切换主题。",
        "maestro_delegation_prompt": "要为检测到的 {clis} CLI 设置编码委派（maestro）吗？",
        "maestro_delegation_note": "仅读取本地 PATH 与认证文件是否存在——二进制文件和认证文件只是已准备（prepared）的证据，而非已观察（observed）的证据，此过程不会调用任何 CLI。之后运行 `omh coding executor-readiness --executor <profile>` 可确认已观察的状态。",
        "maestro_delegation_seeded": "已在 {path} 生成一个空的 dispatch-model 偏好文件。",
        "maestro_delegation_pointers": "后续步骤：按工作类别路由模型请使用 `omh coding category-maestro interview`（交互式）或 `omh coding category-maestro set <profile> <category> <model[:effort]>...`（脚本化）。当没有路由解析时的每所有者默认模型，请直接编辑 `~/.omh/routing/dispatch-models.json`（claude-code 常用 opus）。运行 `omh coding executor-skills --profile <profile>` 查看已发现的技能，并使用 `ulw-maestro` 技能来编排交接提示。",
        "maestro_category_prompt": "现在就配置 Maestro 的类别 -> 模型表吗（交互式）？",
        "model_chains_interview_prompt": "现在就配置按类别的模型链吗（交互式）？",
        "provider_entitlements_note": "Hermes 已关联的提供商（`hermes auth` 登录、config.yaml 中的 `providers:` 条目、.env 中的 API 密钥名）不需回答就会被计入，并以已勾选状态出现。仅在当前 shell 中导出的密钥也会以已勾选状态出现，但只有记录后才会被计入。你的回答会在此基础上保存到 ~/.omh/routing/providers.json：新增或改了种类的行会被记录，取消勾选的预选行将不再计入，订阅 CLI 只能在这里指定。每个模型列表都会重新排序，让被计入的提供商能提供的模型排在前面；不会删除任何条目，也不会为核实而调用任何服务。",
        "provider_entitlements_invalid": "现有的 ~/.omh/routing/providers.json 未被应用（{status}）；重新回答将替换它。",
        "provider_select_title": "你拥有账户、密钥或登录的 AI 服务有哪些？",
        "provider_select_intro_1": "勾选你能使用的所有项。按 Enter 即确认已勾选的列表。",
        "provider_select_intro_2": "已勾选的是在这台机器上发现的，属于推测而非账户可用的证据——把你实际用不了的取消勾选。",
        "provider_detected_config": "在你的 Hermes 配置中发现",
        "provider_detected_env": "发现：这里设置了 {name}",
        "provider_detected_login": "发现：已通过 hermes auth 登录",
        "provider_recorded_before": "上次记录过的项",
        "provider_opengateway_desc": "OMH 自己的网关；提供 Ultrafast 模型（opengateway.ai）",
        "provider_skip_label": "跳过 -- 保持现在的设置不变",
        "provider_skip_desc": "不会保存任何内容：之前的记录原样保留，Hermes 已关联的提供商会继续被计入并自行重排模型列表。你可以随时重新运行 `omh setup` 来回答。",
        "provider_entitlements_skipped": "已保持提供商设置不变；Hermes 已关联的提供商继续被计入，之前的记录原样保留。",
        "provider_kind_relay": "中转所有模型系列",
        "provider_add_prompt": "按名称添加其他提供商（按 Enter 跳过）",
        "provider_add_rejected": "`{provider}` 已记录或不是简单标识符；已跳过。",
        "claude_code_dispatch_kept": "{path} 中已设置 Claude Code 派发模型；保持不变。",
        "claude_code_dispatch_unreadable": "无法写入 Claude Code 派发模型：{path} 不是可读取的 omh_dispatch_model_preferences/v1 文档；请修复或删除后重新运行。",
        "provider_kind_title": "`{provider}` 是哪种提供商？",
        "provider_kind_intro": "gateway、openrouter 和 opencode 中转所有模型系列；其他厂商名仅提供该厂商的模型；unknown 按 gateway 处理。",
        "subscription_cli_prompt": "你在 `{cli}` CLI 上有付费订阅吗？",
        "subscription_cli_note": "Hermes 本身无法使用订阅，它需要 API 密钥；因此此回答只决定 OMH 把工作交给 `{cli}` CLI 时请求哪个模型，不会改变 Hermes 使用的模型。（Codex 登录由 Hermes 自己的 openai-codex 提供商使用，请在上面的列表中勾选。）",
        "provider_entitlements_recorded": "已在 {path} 记录提供商持有信息；运行 `omh model-chains show` 查看重排后的链。",
        "claude_code_dispatch_seeded": "已将 {path} 中的 Claude Code 派发模型设为 {model}（编辑该文件可更改）。",
        "maestro_category_note": "按工作类别（ultrabrain、deep、quick、writing 等）决定被派发的 CLI 单元用哪个模型运行。按 Enter 保留当前链；跳过则保留内置默认值，之后也可以随时运行 `omh coding category-maestro interview` 完成同样的配置。",
        "model_chains_interview_note": "按工作类别（ultrabrain、deep、quick、writing 等）决定 Hermes 首先委派哪个模型，以及其后的回退顺序。按 Enter 保留当前链；跳过则保留出厂默认链，之后也可以随时运行 `omh model-chains interview` 完成同样的配置。",
        "hermes_home": "Hermes 主目录",
        "hermes_config": "Hermes 配置",
        "managed_skills": "OMH 工作流",
        "status_already_registered": "已注册",
        "status_will_register": "将连接 OMH 工作流",
        "status_will_create": "将创建",
        "invalid_executor": "默认执行器无效: {error}",
        "plugin_note": "插件向 Hermes 提供本地状态上下文，但本身不会改变工作流行为。",
        "mcp_host_title": "MCP host",
        "mcp_host_intro": "选择 OMH 应写入本地 stdio MCP 桥配置的位置。",
        "mcp_host_generic_desc": "只显示可移植 recipe，不写入 host 配置文件。",
        "mcp_host_codex_desc": "向 Codex 配置写入 OMH MCP server 条目。",
        "mcp_host_claude_desc": "向 Claude Code 配置写入 OMH MCP server 条目。",
        "mcp_host_opencode_desc": "向 OpenCode 配置写入 OMH MCP server 条目。",
        "mcp_host_cursor_desc": "向 Cursor 配置写入 OMH MCP server 条目。",
        "scope_title": "选择设置范围",
        "scope_intro_1": "用户范围适合个人 Hermes 配置。",
        "scope_intro_2": "项目范围会把 OMH 和 Hermes 配置隔离在当前仓库内。",
        "scope_user_label": "用户范围",
        "scope_user_desc": "在此用户/机器上使用 ~/.omh 和 ~/.hermes。",
        "scope_project_label": "项目范围",
        "scope_project_desc": "为此仓库使用 ./.omh 和 ./.hermes。",
        "team_title": "现在添加可见团队角色预设吗?",
        "team_intro_1": "这些预设只添加 Hermes 协作中可见的角色名称。",
        "team_intro_2": "只有想在聊天里显示这些角色时才选择；所有 OMH 工作流仍会安装。",
        "team_none_label": "现在不添加团队角色预设",
        "team_none_desc": "首次安装推荐。核心技能会安装，其他 surface 仍可通过 Hermes 路由使用。",
        "advanced_title": "高级选项",
        "github_star_thanks": "谢谢!",
        "github_star_dry_run": "dry-run 模式 — 此处不会记录 GitHub star。",
        "github_star_failed": "未能记录 GitHub star: {reason}",
        "github_star_continue": "继续 setup。",
        "step_install_skills": "安装 OMH 工作流",
        "step_register": "将 OMH 连接到 Hermes",
        "step_plugin": "安装 OMH 状态助手",
        "step_menubar": "启动 OMH 菜单栏监视器",
        "step_mcp": "记录可选工具桥偏好",
        "step_team": "启用可见团队角色预设",
        "step_preferences": "保存编码请求偏好",
        "step_targets": "检查 Hermes 配置",
        "done_skills_installed": "已准备 {count} 个工作流",
        "done_skills_ready": "已准备 {count} 个工作流",
        "done_profile_packs": "已启用 {count} 个配置包",
        "done_default_executor": "编码偏好已保存: {executor}",
        "done_mcp_bridge": "工具桥偏好: {status}",
        "done_target_topology": "检测到 {count} 个 Hermes 配置",
        "target_recorded": "Hermes 配置已检查",
        "model_setup_title": "Hermes 模型激活",
        "model_setup_scan": "正在扫描本地模型元数据",
        "model_setup_truncated": "扫描被截断: {reasons}",
        "model_setup_no_active": "没有确认到兼容的推荐模型；setup 未写入模型别名并已完成，同时保留 owner 的默认模型。",
        "model_setup_status": "模型激活状态: {status}",
        "model_setup_chains_hint": "按类别的链: 用 `omh model-chains show` 查看当前顺序，用 `omh model-chains interview` 按类别调整。",
        "model_setup_maestro_hint": "Maestro 通道（被派发的 codex/claude-code 单元）：用 `omh coding category-maestro show` 查看类别 -> 模型表，用 `omh coding category-maestro interview` 进行调整。",
        "model_setup_next": "模型激活下一步: {action}",
        "model_setup_confirm_prompt": "确认 {model} 当前处于激活状态吗?",
        "model_setup_observed_note": "发现结果将此候选项分类为 {status}；观察记录不等于激活确认。",
        "model_setup_preview_title": "Hermes 模型别名预览",
        "model_setup_collision_prompt": "{collision}。替换这个现有别名吗?",
        "model_setup_apply_prompt": "应用已审阅的 Hermes 模型别名预览吗?",
        "skip_by_flag": "因 {flag} 跳过",
        "setup_complete": "OMH 设置已完成。",
        "setup_preview_complete": "OMH 设置预览已完成。",
        "install_complete": "OMH {label} 已完成。",
        "install_preview_complete": "OMH {label} 预览已完成。",
        "summary": "摘要",
        "next": "下一步",
        "setup_scope": "安装位置: {scope}",
        "setup_scope_user": "此用户账户",
        "setup_scope_project": "此项目文件夹",
        "setup_scope_custom": "自定义路径",
        "setup_install_mode": "工作流来源: {mode}",
        "setup_install_mode_managed_skills": "OMH 托管工作流",
        "setup_mcp_mode": "高级工具桥: {mode}",
        "setup_mcp_mode_none": "未启用",
        "setup_mcp_mode_bridge_requested": "偏好已记录",
        "setup_mcp_mode_host_config_written": "已写入 host 配置",
        "setup_mcp_mode_host_config_unchanged": "host 配置已就绪",
        "setup_mcp_mode_host_config_planned": "将写入 host 配置",
        "setup_status": "状态: {status}",
        "setup_status_configured": "已就绪；重启或重新加载 Hermes 后即可在聊天中使用 OMH",
        "setup_status_dry_run": "仅预览；未更改文件",
        "setup_status_skills_only": "工作流已就绪；已跳过 Hermes 连接",
        "command_path_found": "终端命令: 在 {path} 找到 omh",
        "command_path_missing": "终端命令: 此 shell 的 PATH 中找不到 omh。",
        "command_path_missing_next": "请使用安装器输出的绝对路径，或将该目录加入 PATH。",
        "skills_line": "OMH 工作流: {path} 中已准备 {count} 个",
        "registration_configured": "Hermes 连接: 已在 {path} 准备好。重启或重新加载 Hermes Agent 后即可在聊天中看到 OMH。",
        "registration_dry_run": "Hermes 连接: 仅预览；未更改文件。",
        "registration_skipped": "Hermes 连接: 因 --skip-apply 跳过。",
        "registration_unknown": "Hermes 连接: {status}",
        "apply_line": "Hermes 连接详情: {message}",
        "default_handoff": "编码请求: {summary}",
        "default_handoff_pin_hint": "提示: 随时可用 `omh setup --default-executor <name>` 固定默认编码代理。",
        "setup_profile": "高级路由详情: {selected}",
        "target_topology": "Hermes 配置检查: 检测到 {count} 个配置。",
        "setup_providers_line": "模型提供商: 已计入 {providers}；每个模型列表都把它们能提供的模型排在前面。",
        "setup_providers_line_one": "模型提供商: 已计入 {providers}；每个模型列表都把它能提供的模型排在前面。",
        "setup_providers_none": "模型提供商: 尚无 Hermes 已关联或已记录的提供商，因此所有模型都计为可提供。用 `hermes auth` 或 `providers:` 条目关联一个，或交互式运行 `omh setup` 记录一个。",
        "setup_providers_invalid": "模型提供商: {path} 被忽略（{status}）；修复之前，其记录的种类被丢弃，它曾排除的提供商（如有）会重新计入。当前计入: {providers}。",
        "plugin_bridge": "OMH 状态助手: {status}",
        "memory_provider_on": "记忆: OMH 会跨会话记忆并自动整理。",
        "memory_provider_other": "记忆: Hermes 正在使用 {provider}, OMH 记忆保持关闭。",
        "menubar_helper": "OMH 菜单栏: {status}",
        "team_activated": "可见团队预设: 已启用 {count} 个配置包。",
        "team_none": "可见团队预设: 未选择；OMH 工作流仍可使用。",
        "setup_next_dry": "不带 `--dry-run` 重新运行即可安装工作流并连接到 Hermes。",
        "setup_next_reload": "重启或重新加载 Hermes Agent，然后在 Hermes 聊天中尝试:",
        "setup_next_prompt": "Ask Hermes: I want to safely add a feature to this repo.",
        "setup_next_verify": "如果 Hermes 还看不到 OMH，请运行 `omh doctor` 并再次重启或重新加载 Hermes。",
        "hermes_profiles_synced": "Bot 配置文件: {summary}。重启 Hermes Desktop 后 Bot 聊天才会重新加载技能。",
        "hermes_profiles_uninstalled": "Bot 配置文件: {summary}。重启 Hermes Desktop 后 Bot 聊天才会反映已移除的技能。",
        "setup_next_chains": "推荐: 调整按类别的模型链 — 用 `omh model-chains show` 查看当前状态，用 `omh model-chains interview` 逐类别设置。",
        "machine_readable": "如需机器可读输出，请使用 `--json` 重新运行。",
        "source": "来源: {source}",
        "source_builtin": "已安装命令包 (builtin)",
        "release_channel": "发布频道: {channel}",
        "package_url": "包 URL: {url}",
        "recorded_package_url": "已记录包 URL: {url}",
        "release_version_change": "发布版本: {change}",
        "release_source_ref_change": "来源 ref: {change}",
        "release_update_status": "发布状态: {status}",
        "command_package_update_line": "OMH 命令: {change} (已更新)",
        "command_package_not_updated_line": "OMH 命令: 未更新（仅刷新工作流）",
        "update_command_next": "要更新 `omh` 命令本身，请运行: {command}",
        "state_log": "状态日志: {path} ({entry})",
        "skill_profile_retained_line": "技能配置：请求的是 core，但仍安装着 {count} 个 full 专属技能，每轮上下文开销依旧存在。安装流程从不删除技能；如需缩减，请显式运行 `{command}`。",
        "install_next_dry": "不带 `--dry-run` 重新运行即可刷新 OMH 工作流。",
        "install_next": "运行 `omh setup` 将 OMH 工作流连接到 Hermes，或运行 `omh doctor` 检查健康状态。",
        "update_next": "运行 `omh doctor` 检查健康状态；只有注册需要修复时才运行 `omh setup`。",
        "tui_verdict_ready": "OMH TUI: 已就绪。正在运行的 Hermes 会话需重启后生效；`omh` 和 `hermes` 都会打开风格化 TUI。",
        "tui_verdict_blocked": "OMH TUI: 在解决以下事项之前仍会显示原生 Hermes 界面:",
        "tui_verdict_unknown": "OMH TUI: 未找到 Hermes 安装，无法判定 TUI 状态。",
        "tui_verdict_next": "立即处理: 运行 `{command}` 后重启 Hermes。",
        "update_card_previous_release": "上一版本: {release}",
        "update_card_installed_release": "已安装版本: {release}",
        "update_card_available_release": "可用版本: {release}",
        "update_card_install_method": "安装方式: {source}",
        "update_card_release_notes": "发布说明:",
        "update_card_release_preview": "发布预览:",
        "update_card_workflows_refreshed": "已刷新工作流: {count}",
        "update_card_workflow_content_changed": "工作流内容: 已变更",
        "update_card_workflow_content_unchanged": "工作流内容: 无变更",
        "update_card_workflows_to_refresh": "待刷新工作流: {count}",
        "update_card_command_updated": "命令包: 已更新",
        "update_card_command_unchanged": "命令包: 未变更（仅刷新工作流）",
        "update_card_command_preview": "命令包: 未变更（仅预览）",
        "update_card_release_not_recorded": "未记录",
        "update_card_title": "Oh-My-Hermes 更新",
        "update_card_rollback_title": "Oh-My-Hermes 回滚",
        "update_card_restored_release": "已恢复版本: {release}",
        "update_rollback_complete": "OMH 回滚完成: 已知正常的版本已重新启用。",
        "doctor_complete": "OMH doctor 完成。",
        "doctor_needs_attention": "OMH doctor 需要处理。",
        "doctor_status": "状态: {status}",
        "doctor_status_ok": "正常",
        "doctor_status_needs_attention": "需要处理",
        "doctor_checks": "检查: {passing}/{total} 通过",
        "doctor_issue_counts": "问题: {blocking} 个阻塞，{warnings} 个警告",
        "doctor_build_identity": "构建标识: {identity}",
        "doctor_group_managed_skills": "托管技能",
        "doctor_group_runtime": "运行时状态",
        "doctor_group_hermes_registration": "Hermes 注册",
        "doctor_group_targets": "Hermes 目标",
        "doctor_group_model_routing": "模型路由",
        "doctor_group_optional_surfaces": "可选表面",
        "doctor_group_command": "命令可用性",
        "doctor_group_status_ok": "正常",
        "doctor_group_status_warning": "警告",
        "doctor_group_status_needs_attention": "需要处理",
        "doctor_observation_boundaries": "观察边界",
        "doctor_plugin_bridge_ready": "插件桥: 已在 OMH 模拟上下文中通过 import/register smoke。",
        "doctor_plugin_bridge_needs_attention": "插件桥: 需要修复；运行 `omh setup` 后再运行 `omh doctor`。",
        "doctor_plugin_bridge_not_installed": "插件桥: 未安装；OMH 仍可通过 Hermes skills 工作。",
        "doctor_plugin_loader_observed": "Hermes 加载器: 已在隔离的真实加载器中观察到注册。",
        "doctor_plugin_loader_not_observed": "Hermes 加载器: 尚未观察到；模拟上下文 smoke 不是主机注册证据。",
        "doctor_plugin_runtime_observed": "Hermes 运行时: 主机已观察到实时插件加载/使用。",
        "doctor_plugin_runtime_historical": "Hermes 运行时: 仅记录了历史插件活动；在声明当前活跃前需要新的主机事件。",
        "doctor_plugin_runtime_not_observed": "Hermes 运行时: 尚未观察到；在声明聊天可见性或原生插件使用前，请重启或重新加载 Hermes。",
        "doctor_structural_search_present": "结构检索: 已在 PATH 上解析到 ast-grep；仅确认存在，OMH 未执行它。",
        "doctor_structural_search_absent": "结构检索: PATH 上没有 ast-grep；代码探索继续使用 grep/ripgrep。",
        "doctor_default_next_action": "打开 Hermes Agent 并尝试: Use OMH request-to-handoff for: I want to safely add a feature to this repo.",
        "doctor_fix": "修复",
        "doctor_boundary": "边界: 在把聊天可见性视为已观察之前，请重启或重新加载 Hermes。",
        "config_external_dir_already_present": "已配置",
        "config_created_skills_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_appended_skills_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_expanded_inline_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_inserted_skills_external_dirs": "Hermes 现在可以找到 OMH 工作流",
        "config_added_external_dir": "Hermes 现在可以找到 OMH 工作流",
        "config_external_dir_absent": "已移除",
        "config_removed_external_dir": "已移除 OMH 技能目录",
        "uninstall_title": "OMH 卸载",
        "uninstall_subtitle": "删除 OMH 管理的本地状态和 Hermes 集成文件。",
        "uninstall_complete": "OMH 卸载已完成。",
        "uninstall_preview_complete": "OMH 卸载预览已完成。",
        "uninstall_scope_all": "完整清理",
        "uninstall_scope_registration": "仅取消注册",
        "uninstall_scope_files": "取消注册并删除托管 ~/.omh 文件",
        "uninstall_config": "Hermes 注册: {message}",
        "uninstall_config_reversed": "已还原的 config 键: {keys}",
        "uninstall_config_would_reverse": "将还原的 config 键: {keys}",
        "uninstall_config_kept": "保留的 config 键: {config_key} ({detail})",
        "uninstall_config_partial": "部分还原的 config 键: {config_key} — {kept} 的值保持不变。",
        "uninstall_config_unrecorded": "原样保留的 config 键: {config_key} — 没有 OMH 写入的记录，该值也可能是用户自己的选择。",
        "uninstall_removed": "已删除: {count} 个路径",
        "uninstall_would_remove": "将删除: {count} 个路径",
        "uninstall_none": "没有需要删除的项目。",
        "uninstall_command_removed": "命令包: 已删除 {count} 个安装器托管路径。",
        "uninstall_command_would_remove": "命令包: 将删除 {count} 个安装器托管路径。",
        "uninstall_command_kept": "命令包: 当前 `omh` 不是从安装器托管的 OMH venv 运行，因此未删除。",
        "uninstall_command_still_available": "如果 uninstall 后 `omh` 仍可运行，说明命令包仍在 PATH 中；请从安装它的 installer-managed venv、pip 或 pipx 中删除。",
        "scope": "范围",
        "kept": "保留",
    },
}


def normalize_language(value: str | None) -> str:
    key = str(value or "").strip().lower()
    language = _LANGUAGE_ALIASES.get(key)
    if language:
        return language
    valid = ", ".join(LANGUAGE_CODES)
    raise ValueError(f"unsupported language: {value}; expected one of {valid}")


def language_from_env(default: str = "en") -> str:
    return normalize_language(os.environ.get("OMH_LANG") or os.environ.get("OMH_LANGUAGE") or default)


def language_options() -> list[dict[str, str]]:
    return [
        {"choice": str(index), "value": code, "label": LANGUAGE_NAMES[code], "description": ""}
        for index, code in enumerate(LANGUAGE_CODES, start=1)
    ]


def tr(language: str, key: str, **kwargs: object) -> str:
    code = normalize_language(language)
    template = MESSAGES.get(code, {}).get(key) or MESSAGES["en"][key]
    return template.format(**kwargs)
