# Generated by omh docs agent-skills; edit the catalog/producer, not this file.
# Source inventory SHA256: a480269d40c088aabb7a04690e1f726c90f483da9303e55938ffa394dbd3b2fd
param([switch]$User)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
if ($args.Count) { throw 'Usage: install.ps1 [-User]' }
$base = (Get-Location).ProviderPath
if ($User) {
    $base = $env:USERPROFILE
    if (-not $base) { $base = $env:HOME }
    if (-not $base) { throw 'User profile is required for -User' }
    $target = Join-Path $base '.agents/skills'
} else {
    $target = Join-Path $base '.agents/skills'
}
$source = Join-Path (Split-Path -Parent $PSScriptRoot) 'agent-skills'
$checksums = @'
352bd6fdb8cca6582273af306752547a53074a2c30a3593f0b548e9abfc10b05  omh-accessibility-audit/SKILL.md
cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469  omh-accessibility-audit/references/a11y-rules.md
5fde1ca41603683627819f43ddd8df06c87ca5b6a9bad431a0fe884011831061  omh-adversarial-consensus/SKILL.md
e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89  omh-adversarial-consensus/references/consensus-protocol.md
a9415ef0cd4c6dd009c92ab7118fab54f9328d03cc45bf75a8c7178eb392c571  omh-agent-debug/SKILL.md
402cdc3b0c53ac6ef3293094d193def768f001431caf51e93802e1662f7d4633  omh-agent-ops-review/SKILL.md
d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291  omh-agent-ops-review/references/instrumentation-ladder.md
a87547c00d37c43787b77c22798c78045c7fe1d0420ffaea742d1e39fcbfa8e0  omh-ai-slop-cleaner/SKILL.md
d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d  omh-ai-slop-cleaner/references/cleanup-passes.md
efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5  omh-ai-slop-cleaner/references/prose-lexicon.md
0a7eeed8200a5bd3cf4e3d06de0b0862d24715743ad569fe3e25b30e9975e3f7  omh-apple-design/SKILL.md
09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26  omh-apple-design/references/materials-and-accessibility.md
4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0  omh-apple-design/references/platform-foundations.md
835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd  omh-apple-design/references/product-visual-production.md
c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604  omh-apple-design/references/review-playbook.md
81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e  omh-apple-design/references/web-production-libraries.md
705162d7ce2808865024c7deaa6e7ded1fa458c245f6d655ec30ef5e25f17ea4  omh-application-threat-model/SKILL.md
ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e  omh-application-threat-model/references/threat-model-method.md
e1c016d1e8a128373bee50b88a68b0faa379e307afa2715c546d726011531651  omh-apps/SKILL.md
5cec8b3013111ffde4200553cd749aa409a24d5a80f20c117045a71224575563  omh-ask/SKILL.md
e8ddee4019ebc0c120fd1f8d45edf475ce2066dc58ab065572bb1a9307b9ffe5  omh-award-bar-score/SKILL.md
3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50  omh-award-bar-score/references/award-judging-model.md
9f67dd3d6433010c97eaf396013a7eb34d969adf8a43d01657bc181f23b39856  omh-backend/SKILL.md
843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9  omh-backend/references/consumer-impact.md
e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054  omh-backend/references/schema-migration.md
984cd9cb634b88a505cbd76214e281b2e22edf3d75fc6a3b9a0a88fcc4a265f5  omh-backend/references/service-contract.md
92f8c34187d81b3148a553b4dc5cb5d781419dbec7e35f1ef9e97dc7be84dc4a  omh-build-failure-triage/SKILL.md
7e5928b17366210edf348d5afd400187a63a8234d9fe1fdb08a4d9454abcd774  omh-cancel/SKILL.md
2ceaf0ba1475c9d9af35ebc748ea16927c0f9263d243db639f30e192d411bf33  omh-code-review/SKILL.md
6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424  omh-code-review/references/review-dispatch.md
fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f  omh-code-review/references/review-lenses.md
9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db  omh-code-review/references/review-response.md
99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be  omh-code-review/references/smell-baseline.md
fbd6a4c190ea821c0ab94cc1db2292e90506cb9fc71b1aa6521352862eff223b  omh-codebase-onboarding/SKILL.md
0352727bff65ee5661ce0cf36f4b3ab3df3822eae8644fdf11b6a82ea9a0ce81  omh-codebase-uml/SKILL.md
d3c0d3be01719f0d23208e41d49518c4d580faa28e3db32a6aa2e25a16c970bd  omh-codegraph-refresh/SKILL.md
7cdff2704582aa93fafbfc9f38b09cf0c83106ecdf187a191ee08aaba61b2d69  omh-content-operator/SKILL.md
03ef1999388fe0da1c79247fd118bab52a44252b557a36c876e3590b3b77d36a  omh-context-budget-review/SKILL.md
bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590  omh-context-budget-review/references/cache-placement.md
72467a1db8717c2c5e9e1bf20f1a70345ac8843e3e1a3537a2fc5db04e5e0a43  omh-cto-loop/SKILL.md
103030f8165fa0467dc8de7a211808ec9c49cc74ab5a852d323172c7f956ca35  omh-curriculum-design/SKILL.md
5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b  omh-curriculum-design/references/procedure.md
5f0a0f031eb84240cc6347316ab63bb9a10d8cdeffc82a9b2319c93f2e6e6942  omh-data-analysis/SKILL.md
c92aa4c2973bad0340c8f2cec78042ff4d8002d36a62c91b0f78025458136ed7  omh-decide/SKILL.md
5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae  omh-decide/references/capacity-planning.md
4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d  omh-decide/references/decision-records.md
bfb8f16761fc2fc21871ef24c9408ac141fcf38a35742a6c78b07e4825c09f6a  omh-decision-prototype/SKILL.md
53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88  omh-decision-prototype/references/procedure.md
913f3e27ae3f508d52f37c25868b80a5105a1cf8806686cf52f63132128477f7  omh-decision-recall/SKILL.md
7f3305d7e2a3b628711c05a426aaa3c22658948591aa4ad126ec965228b65ed5  omh-deliverable-package/SKILL.md
80f89d366ce37cf7bac493c0335bafc686353df446f546ada16ef795767f7625  omh-deploy-and-monitor/SKILL.md
3615dd7e7d1cba751efe8eb19a8537e171fc632de3cd63398ab790cbc0d74f0e  omh-design-orchestration/SKILL.md
07224925ff6f2aca2fbffc4c98d2b24254d5cb5eec7ce7e0448d86dc39f26371  omh-design-quality-gate/SKILL.md
7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae  omh-design-quality-gate/references/design-critique-rubric.md
47d36b28f42c7d83d32c4f7bbb2ae7db3a534c19949c11221473803638b95d6d  omh-docs/SKILL.md
0fc2370d9dbd3dc61170ecaab74b857d9ce8bc3aa6735f84f3a6562542e03213  omh-external-connector-readiness/SKILL.md
b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3  omh-external-connector-readiness/references/memory-provider-trial.md
5d51ca9a0b78a902fbb4d5d2230be273e71d52a449f51584a9d23a0e80a52475  omh-failure-signal-audit/SKILL.md
30b5a57eced19a7132a1ff1d1b2a98c674f0439510292092cff88070323f6b17  omh-feedback-triage/SKILL.md
33465192387107a1a6ff8634b003110bf87fa87f77db96a5d7ac02575bb3619d  omh-files/SKILL.md
03a72fe91f34e7f1629324e763ebdf75cbf89ba6d552676ba08b8bb4f14370de  omh-finance-analysis/SKILL.md
0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c  omh-finance-analysis/references/procedure.md
dcdc20d6d0d32c62388b6558518943254cbda21b26440579e21c989e764b3aa2  omh-frontend-refactor/SKILL.md
ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f  omh-frontend-refactor/references/refactor-passes.md
04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4  omh-frontend-refactor/references/state-discipline.md
bf8aa2381ba6b51fea1e12131bffa5bf77dd9ec4e64173a39b94025a1fcc164c  omh-frontend/SKILL.md
5ed9f05a8eb6d5c8ae839313f9adbae7c18b15940777645924fdb2670b64a60c  omh-frontend/references/design-system-contract.md
b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf  omh-frontend/references/reference-token-extraction.md
ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09  omh-frontend/references/screenshot-loop.md
605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245  omh-frontend/references/scroll-motion-libraries.md
2d4552c2ae32e0e1a18517d3faf74c016cdc1c946263201118cd27ccfb2a68d7  omh-frontend/references/taste-foundations.md
13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e  omh-frontend/references/tui-craft.md
7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b  omh-frontend/references/web-vitals-budgets.md
45674d33d9babd26cde42fd25089e8fb28bb760031536e0cb419cd0bf5e0bbef  omh-github-event-ops/SKILL.md
6d9cd15ce05a2fa363d84e90d2d67273c7f44ca279bb27913d26eba1fc6bf997  omh-github-issue-intake/SKILL.md
639b9741d44088c85d537de05b043c69491b34c7bca27dfcd2a2c1bb9163f4d2  omh-harness-session-inventory/SKILL.md
1794a7628adab7e53628b716406e453bb54b7c3beb7e2a9e3d2680e9ae14fe49  omh-idea-to-deploy/SKILL.md
dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7  omh-idea-to-deploy/references/project-bootstrap.md
2e6be617f68557de53ec3545273324d6a951bbd12068deb62fb6ba184005e8fa  omh-image-cards/SKILL.md
195333cfa972158d97aaef6d26a8fe978fab7762e4c629f6f8e5459b4befda11  omh-inference-serving/SKILL.md
31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0  omh-inference-serving/references/serving-bench.md
da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e  omh-inference-serving/references/serving-runbooks.md
e634f25e8c8127238cceff1451f9e63a0fe728522a9f2661cf16d0b40993b2e8  omh-instinct-ledger/SKILL.md
c479d49564032fee7a1f0ebf59f179ccf91f8e68e20465fc73bed674c1fb8bfc  omh-jit-learn/SKILL.md
5af45e06f2c32de0a782efc8f39aead53386263e9ecdfcd56d1c63804735c615  omh-legal-compliance-review/SKILL.md
a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1  omh-legal-compliance-review/references/negotiation-preparation.md
670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58  omh-legal-compliance-review/references/procedure.md
5f57de1e990136cbc5ea23a7b2f47bd3601f2a071a066d69f46e981f02aa2345  omh-lifecycle-growth/SKILL.md
7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de  omh-lifecycle-growth/references/procedure.md
60e97036049971e300cab7b8bf461fee7a6682d55f8f6c741567b5d7b97d76bc  omh-live-incident-response/SKILL.md
8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7  omh-live-incident-response/references/incident-command-method.md
8a342f6178e10475919bceb6724fe7a377c6978fc8dfd0fce762bca2d6d3a08a  omh-live-info/SKILL.md
805862c95964e9a37c3b1305dc108337539c8b3b89d69e64f134d385f2223be3  omh-llm-app-dev/SKILL.md
35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149  omh-llm-app-dev/references/build-rails.md
959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd  omh-llm-app-dev/references/eval-harness.md
e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca  omh-llm-app-dev/references/public-board.md
7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816  omh-llm-app-dev/references/stateful-contracts.md
b34b22c357d106d036bb17477f24211f86fa4cfc72a0e6a8f95c12ec7e42ba63  omh-localization-review/SKILL.md
96d9a4a7de46f68e49cf112fa6cadb9b8feb55c0e5c470d49a0520af1074de6c  omh-materials-package/SKILL.md
ae8d1e09012c22c226327cc984a45c548d16adf7349d3b7c4898a46d153b303c  omh-media-input/SKILL.md
8c5e782cfcb86deeb3e4acad3f5afe0e23926f6be4d14981672e673359943aee  omh-meeting-brief/SKILL.md
65031ba4ad0bd5ac5407eb55094fe1780d7244dc7ef490b18ed5699df8132f28  omh-memory-new/SKILL.md
7b14d5ac72900fee0ff7e6fab1845b65d45e4452078e87d3073dc1cbcc533f30  omh-native-debugging/SKILL.md
3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d  omh-native-debugging/references/native-debug-loop.md
afcf84009038ea5164e92534bc0087ffbf25991203fad956bad992eb0e9b1379  omh-operating-rhythm/SKILL.md
bb519d4783bdd0a1cbf1409c5144703a145f3185519e62d6b853219099c97cd4  omh-ops-observability-card/SKILL.md
c5dece95ad42fbfa81291d0f7a11037391be339d3a3d3282fba7cba0d469b532  omh-ops-review/SKILL.md
06a38802ce7008a51a46a8a0b2db7bf078caaacfc82bce2a28d753f7c075794d  omh-paper-learning/SKILL.md
5d33fc10c45c53089b4cddd92a0308651ae2416510245a51ec7f0c1297f097ad  omh-people-ops/SKILL.md
cd5ac7d183d14cd30b4cf8df32de8ffb0c7b0d06efca7f141a2e80cfbbaaaec2  omh-physical-device-readiness/SKILL.md
11b3ce3a68b1942125f86e35e488659d272b8a1c3ab6a57aa9fa017adf2cb24f  omh-plan/SKILL.md
577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da  omh-plan/references/project-constitution.md
fdba4b4b12e083f8a2d493cf57d8a435dc722ecdc2ee556a3850a13bf6f79ccd  omh-product-brief/SKILL.md
e827fadf56437016fb69516db1b903b7c830c3c57ebb250113384ecd7986bb41  omh-product-discovery-validation/SKILL.md
c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a  omh-product-discovery-validation/references/procedure.md
5547ba0eb3674741c8fc949ef7a1b13b5c3f1d968c1605a63393a71cd29daa3f  omh-production-audit/SKILL.md
9fb1ff6f17175c7ce7dfa3c4686acbe2a3e0ff87d9a560265f02be25119ef4ae  omh-provider-profile-posture/SKILL.md
d14d24391366ccd6ef0765d9229d831a8ee3049c3ed0ff6e442299b71c514f2a  omh-refactor-plan/SKILL.md
b754550de95896a85e541b5e8f7d46a45696dfa1f73afe57bf7de4df114ebac0  omh-refactor-plan/references/dependency-upgrade.md
492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035  omh-refactor-plan/references/refactor-phases.md
323407ddfc6847cf7864007c0f1778a5c368e4a84e331f6d8835a9515d3f269a  omh-reliability-review/SKILL.md
edf909644bf7457f4e23e2abdae670962222318840d0816fae2d5c8adf40b113  omh-report-package/SKILL.md
c5065935f12982a6adcadc7df3d53443b6e2f65b18b4359d60fc7dc497cfb12f  omh-research-brief/SKILL.md
91b289b2d37a9b66427fc253d8ef33a62ac62a25f9183748d996a004da80c6c8  omh-rules-distill/SKILL.md
f760415398b0d1d449e93387967d67677a40e6a05a8ffbea67b2678dcdb2a0ea  omh-run-efficiency/SKILL.md
63e8a8f117ede0c98f5d9029c64a930576c49ec5856fefbae0c0804877746930  omh-running-work-board/SKILL.md
7e165afd692559138257a4a07c6f23fc77e221769f2baf3774b2802e81628019  omh-rust/SKILL.md
7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844  omh-rust/references/rust-discipline.md
b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768  omh-rust/references/ub-escalation.md
b20b85d5b77ce91c4145d52bb4ecc96884721e9fd98c8b2d79a2000099711add  omh-sales-development/SKILL.md
0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70  omh-sales-development/references/procedure.md
de2e6755a1eb3acd20732e2ea61586bbd1511850daa8a2fe12a25f4ced353096  omh-sales-pipeline-review/SKILL.md
ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138  omh-sales-pipeline-review/references/procedure.md
c53feb8af2439b38c437b8d41a523dcb5552a286309dd401af4986148b30698e  omh-security-safety-review/SKILL.md
2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065  omh-security-safety-review/references/credential-rotation.md
227476bbc5de7375fec53846883a55cbe5465ce49a47db562eda18984475c1de  omh-skill-health/SKILL.md
9ea99eb5bed0256800e44041b216c605f073f6c4d7b221ae896d8bc9f6efe154  omh-skill-scout/SKILL.md
dee9bc54b388d99d2bab6f1da1c9528541d702f22ad31e9aad21b16b22825f19  omh-source-finder/SKILL.md
2541228dac4007e0c4f9b866a7180e2167ee180dafa37f80e055eee21e2b7fee  omh-support-operations/SKILL.md
6a9142b2b96b8ef6e6a02d771b66b8d4e5f4009a98c318f391f0118d35a4b946  omh-tech-debt-audit/SKILL.md
7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75  omh-tech-debt-audit/references/debt-dimensions.md
8641a0b19298f4d81ab86d70d746c2aba74485c162abe330e1f06edaa5c1bc47  omh-terminal/SKILL.md
13a192a9b5aa4d481dade7b19be9afdf6e053cfe51011649dff6fbd58a97f913  omh-toolbelt-readiness/SKILL.md
d9d66e26c328cf6b6667ae259025f184b4950da74d29cde4140e68b0149abdd8  omh-verification-gate/SKILL.md
91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad  omh-verification-gate/references/generated-artifact-provenance.md
91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19  omh-verification-gate/references/requirement-coverage-map.md
071db3172d349f376edddcfaa9bbd16a7b91fe218be25006f115f965a79e66a4  omh-visual-qa/SKILL.md
7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759  omh-visual-qa/references/visual-verdict-contract.md
a78951eaf35a967bfd3089b1d10bfcd24954e1187e1a8228b6a6492798243c00  omh-voice-input/SKILL.md
bb2ac57ec2fcea70579487248a19a8d9f062077a7630f1599d7a9a704ad66150  omh-web-research/SKILL.md
4065fe72ca7077e9cb79528203bace0a3115e4b3d389d202b5649f9924da0a51  omh-wiki/SKILL.md
6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c  omh-wiki/references/wiki-blueprint.md
656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528  omh-wiki/references/wiki-operations.md
f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e  omh-wiki/references/wiki-patterns.md
000dd0823a29400b857135ea394292de9a77302651e8d77bfe6494b354b5bf3e  omh-workspace-audit/SKILL.md
b1542959647255da3e8169854c761bb59f4fc7388447d8ae86a1c900112ab316  ulw-context/SKILL.md
122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df  ulw-context/references/decision-frontier.md
0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45  ulw-context/references/project-terms.md
871b91e100e61c49de23205a8ecdb690649820f301f66f297a95cc2bda59900d  ulw-interview/SKILL.md
af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a  ulw-interview/references/ambiguity-taxonomy.md
4eca60ba2e8584a6735d5227b3c6eb2b483f86afdac6f19f7e0a0fc0bbcfe5cf  ulw-loop/SKILL.md
e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f  ulw-loop/references/goal-constraint-discipline.md
1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb  ulw-loop/references/measured-loop-discipline.md
545b4e9dd8d858e8ebabb3df10fd5053301a2705ae1c9e73f47d0bd3ab817b0a  ulw-perf/SKILL.md
3b5a48ff022414dd94ee705905d929ccad9bc4045f0e081d8711144b129bef33  ulw-plan/SKILL.md
6a9649053365cf696209a4a37581682b61499578d69cb7ab0cc17b16ea2f47ce  ulw-qa/SKILL.md
5c8e9f57b68651a244d4965960112cef71772440f396e27e2bc35aa3b7f4f0a2  ulw-research/SKILL.md
466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac  ulw-research/references/briefing-format.md
6893ae72e7d2a42733ab30852328acfb0ff39b8db3cec4894e88d38ea2f9aff1  ulw-work/SKILL.md
b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac  ulw-work/references/dependency-topology.md
'@
$entries = @($checksums.Split("`n") | ForEach-Object {
    $parts = $_.TrimEnd("`r") -split '  ', 2
    [PSCustomObject]@{ Path = $parts[1]; Hash = $parts[0] }
})
function Assert-NoLink([string]$Path, [string]$Boundary) {
    $current = $Path
    while ($current -and $current -ne $Boundary) {
        if (Test-Path -LiteralPath $current) {
            $item = Get-Item -Force -LiteralPath $current
            if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                throw "Reparse-point path: $current"
            }
        }
        $current = Split-Path -Parent $current
    }
}
Assert-NoLink $source (Split-Path -Parent $source)
$items = @(Get-ChildItem -Force -Recurse -LiteralPath $source)
foreach ($item in $items) {
    if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
        throw "Reparse-point source: $($item.FullName)"
    }
}
$sourceFiles = @($items | Where-Object { -not $_.PSIsContainer })
if ($sourceFiles.Count -ne $entries.Count) { throw 'Source file inventory mismatch' }
function Assert-Digests([string]$Root) {
    foreach ($entry in $entries) {
        $path = Join-Path $Root $entry.Path
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Missing skill: $path" }
        if ((Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant() -cne $entry.Hash) {
            throw "Skill digest mismatch: $path"
        }
    }
}
Assert-Digests $source
# Preflight the receipt as well as every copied file before any write.
foreach ($relative in (@($entries.Path) + '.omh-agent-skills-manifest.json')) {
    $path = Join-Path $target $relative
    Assert-NoLink $path $base
    if ((Test-Path -LiteralPath $path) -and -not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Not a file: $path"
    }
}
foreach ($entry in $entries) {
    $path = Join-Path $target $entry.Path
    [IO.Directory]::CreateDirectory((Split-Path -Parent $path)) | Out-Null
    [IO.File]::Copy((Join-Path $source $entry.Path), $path, $true)
}
Assert-Digests $target
$receipt = @'
{
  "catalog_revision": "173c707c7bc6fc59e1f583805192b3410fc91077550acfe873db69b0fd855cc7",
  "files": {
    "omh-accessibility-audit/SKILL.md": "352bd6fdb8cca6582273af306752547a53074a2c30a3593f0b548e9abfc10b05",
    "omh-accessibility-audit/references/a11y-rules.md": "cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469",
    "omh-adversarial-consensus/SKILL.md": "5fde1ca41603683627819f43ddd8df06c87ca5b6a9bad431a0fe884011831061",
    "omh-adversarial-consensus/references/consensus-protocol.md": "e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89",
    "omh-agent-debug/SKILL.md": "a9415ef0cd4c6dd009c92ab7118fab54f9328d03cc45bf75a8c7178eb392c571",
    "omh-agent-ops-review/SKILL.md": "402cdc3b0c53ac6ef3293094d193def768f001431caf51e93802e1662f7d4633",
    "omh-agent-ops-review/references/instrumentation-ladder.md": "d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291",
    "omh-ai-slop-cleaner/SKILL.md": "a87547c00d37c43787b77c22798c78045c7fe1d0420ffaea742d1e39fcbfa8e0",
    "omh-ai-slop-cleaner/references/cleanup-passes.md": "d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d",
    "omh-ai-slop-cleaner/references/prose-lexicon.md": "efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5",
    "omh-apple-design/SKILL.md": "0a7eeed8200a5bd3cf4e3d06de0b0862d24715743ad569fe3e25b30e9975e3f7",
    "omh-apple-design/references/materials-and-accessibility.md": "09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26",
    "omh-apple-design/references/platform-foundations.md": "4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0",
    "omh-apple-design/references/product-visual-production.md": "835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd",
    "omh-apple-design/references/review-playbook.md": "c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604",
    "omh-apple-design/references/web-production-libraries.md": "81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e",
    "omh-application-threat-model/SKILL.md": "705162d7ce2808865024c7deaa6e7ded1fa458c245f6d655ec30ef5e25f17ea4",
    "omh-application-threat-model/references/threat-model-method.md": "ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e",
    "omh-apps/SKILL.md": "e1c016d1e8a128373bee50b88a68b0faa379e307afa2715c546d726011531651",
    "omh-ask/SKILL.md": "5cec8b3013111ffde4200553cd749aa409a24d5a80f20c117045a71224575563",
    "omh-award-bar-score/SKILL.md": "e8ddee4019ebc0c120fd1f8d45edf475ce2066dc58ab065572bb1a9307b9ffe5",
    "omh-award-bar-score/references/award-judging-model.md": "3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50",
    "omh-backend/SKILL.md": "9f67dd3d6433010c97eaf396013a7eb34d969adf8a43d01657bc181f23b39856",
    "omh-backend/references/consumer-impact.md": "843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9",
    "omh-backend/references/schema-migration.md": "e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054",
    "omh-backend/references/service-contract.md": "984cd9cb634b88a505cbd76214e281b2e22edf3d75fc6a3b9a0a88fcc4a265f5",
    "omh-build-failure-triage/SKILL.md": "92f8c34187d81b3148a553b4dc5cb5d781419dbec7e35f1ef9e97dc7be84dc4a",
    "omh-cancel/SKILL.md": "7e5928b17366210edf348d5afd400187a63a8234d9fe1fdb08a4d9454abcd774",
    "omh-code-review/SKILL.md": "2ceaf0ba1475c9d9af35ebc748ea16927c0f9263d243db639f30e192d411bf33",
    "omh-code-review/references/review-dispatch.md": "6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424",
    "omh-code-review/references/review-lenses.md": "fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f",
    "omh-code-review/references/review-response.md": "9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db",
    "omh-code-review/references/smell-baseline.md": "99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be",
    "omh-codebase-onboarding/SKILL.md": "fbd6a4c190ea821c0ab94cc1db2292e90506cb9fc71b1aa6521352862eff223b",
    "omh-codebase-uml/SKILL.md": "0352727bff65ee5661ce0cf36f4b3ab3df3822eae8644fdf11b6a82ea9a0ce81",
    "omh-codegraph-refresh/SKILL.md": "d3c0d3be01719f0d23208e41d49518c4d580faa28e3db32a6aa2e25a16c970bd",
    "omh-content-operator/SKILL.md": "7cdff2704582aa93fafbfc9f38b09cf0c83106ecdf187a191ee08aaba61b2d69",
    "omh-context-budget-review/SKILL.md": "03ef1999388fe0da1c79247fd118bab52a44252b557a36c876e3590b3b77d36a",
    "omh-context-budget-review/references/cache-placement.md": "bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590",
    "omh-cto-loop/SKILL.md": "72467a1db8717c2c5e9e1bf20f1a70345ac8843e3e1a3537a2fc5db04e5e0a43",
    "omh-curriculum-design/SKILL.md": "103030f8165fa0467dc8de7a211808ec9c49cc74ab5a852d323172c7f956ca35",
    "omh-curriculum-design/references/procedure.md": "5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b",
    "omh-data-analysis/SKILL.md": "5f0a0f031eb84240cc6347316ab63bb9a10d8cdeffc82a9b2319c93f2e6e6942",
    "omh-decide/SKILL.md": "c92aa4c2973bad0340c8f2cec78042ff4d8002d36a62c91b0f78025458136ed7",
    "omh-decide/references/capacity-planning.md": "5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae",
    "omh-decide/references/decision-records.md": "4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d",
    "omh-decision-prototype/SKILL.md": "bfb8f16761fc2fc21871ef24c9408ac141fcf38a35742a6c78b07e4825c09f6a",
    "omh-decision-prototype/references/procedure.md": "53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88",
    "omh-decision-recall/SKILL.md": "913f3e27ae3f508d52f37c25868b80a5105a1cf8806686cf52f63132128477f7",
    "omh-deliverable-package/SKILL.md": "7f3305d7e2a3b628711c05a426aaa3c22658948591aa4ad126ec965228b65ed5",
    "omh-deploy-and-monitor/SKILL.md": "80f89d366ce37cf7bac493c0335bafc686353df446f546ada16ef795767f7625",
    "omh-design-orchestration/SKILL.md": "3615dd7e7d1cba751efe8eb19a8537e171fc632de3cd63398ab790cbc0d74f0e",
    "omh-design-quality-gate/SKILL.md": "07224925ff6f2aca2fbffc4c98d2b24254d5cb5eec7ce7e0448d86dc39f26371",
    "omh-design-quality-gate/references/design-critique-rubric.md": "7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae",
    "omh-docs/SKILL.md": "47d36b28f42c7d83d32c4f7bbb2ae7db3a534c19949c11221473803638b95d6d",
    "omh-external-connector-readiness/SKILL.md": "0fc2370d9dbd3dc61170ecaab74b857d9ce8bc3aa6735f84f3a6562542e03213",
    "omh-external-connector-readiness/references/memory-provider-trial.md": "b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3",
    "omh-failure-signal-audit/SKILL.md": "5d51ca9a0b78a902fbb4d5d2230be273e71d52a449f51584a9d23a0e80a52475",
    "omh-feedback-triage/SKILL.md": "30b5a57eced19a7132a1ff1d1b2a98c674f0439510292092cff88070323f6b17",
    "omh-files/SKILL.md": "33465192387107a1a6ff8634b003110bf87fa87f77db96a5d7ac02575bb3619d",
    "omh-finance-analysis/SKILL.md": "03a72fe91f34e7f1629324e763ebdf75cbf89ba6d552676ba08b8bb4f14370de",
    "omh-finance-analysis/references/procedure.md": "0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c",
    "omh-frontend-refactor/SKILL.md": "dcdc20d6d0d32c62388b6558518943254cbda21b26440579e21c989e764b3aa2",
    "omh-frontend-refactor/references/refactor-passes.md": "ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f",
    "omh-frontend-refactor/references/state-discipline.md": "04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4",
    "omh-frontend/SKILL.md": "bf8aa2381ba6b51fea1e12131bffa5bf77dd9ec4e64173a39b94025a1fcc164c",
    "omh-frontend/references/design-system-contract.md": "5ed9f05a8eb6d5c8ae839313f9adbae7c18b15940777645924fdb2670b64a60c",
    "omh-frontend/references/reference-token-extraction.md": "b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf",
    "omh-frontend/references/screenshot-loop.md": "ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09",
    "omh-frontend/references/scroll-motion-libraries.md": "605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245",
    "omh-frontend/references/taste-foundations.md": "2d4552c2ae32e0e1a18517d3faf74c016cdc1c946263201118cd27ccfb2a68d7",
    "omh-frontend/references/tui-craft.md": "13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e",
    "omh-frontend/references/web-vitals-budgets.md": "7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b",
    "omh-github-event-ops/SKILL.md": "45674d33d9babd26cde42fd25089e8fb28bb760031536e0cb419cd0bf5e0bbef",
    "omh-github-issue-intake/SKILL.md": "6d9cd15ce05a2fa363d84e90d2d67273c7f44ca279bb27913d26eba1fc6bf997",
    "omh-harness-session-inventory/SKILL.md": "639b9741d44088c85d537de05b043c69491b34c7bca27dfcd2a2c1bb9163f4d2",
    "omh-idea-to-deploy/SKILL.md": "1794a7628adab7e53628b716406e453bb54b7c3beb7e2a9e3d2680e9ae14fe49",
    "omh-idea-to-deploy/references/project-bootstrap.md": "dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7",
    "omh-image-cards/SKILL.md": "2e6be617f68557de53ec3545273324d6a951bbd12068deb62fb6ba184005e8fa",
    "omh-inference-serving/SKILL.md": "195333cfa972158d97aaef6d26a8fe978fab7762e4c629f6f8e5459b4befda11",
    "omh-inference-serving/references/serving-bench.md": "31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0",
    "omh-inference-serving/references/serving-runbooks.md": "da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e",
    "omh-instinct-ledger/SKILL.md": "e634f25e8c8127238cceff1451f9e63a0fe728522a9f2661cf16d0b40993b2e8",
    "omh-jit-learn/SKILL.md": "c479d49564032fee7a1f0ebf59f179ccf91f8e68e20465fc73bed674c1fb8bfc",
    "omh-legal-compliance-review/SKILL.md": "5af45e06f2c32de0a782efc8f39aead53386263e9ecdfcd56d1c63804735c615",
    "omh-legal-compliance-review/references/negotiation-preparation.md": "a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1",
    "omh-legal-compliance-review/references/procedure.md": "670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58",
    "omh-lifecycle-growth/SKILL.md": "5f57de1e990136cbc5ea23a7b2f47bd3601f2a071a066d69f46e981f02aa2345",
    "omh-lifecycle-growth/references/procedure.md": "7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de",
    "omh-live-incident-response/SKILL.md": "60e97036049971e300cab7b8bf461fee7a6682d55f8f6c741567b5d7b97d76bc",
    "omh-live-incident-response/references/incident-command-method.md": "8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7",
    "omh-live-info/SKILL.md": "8a342f6178e10475919bceb6724fe7a377c6978fc8dfd0fce762bca2d6d3a08a",
    "omh-llm-app-dev/SKILL.md": "805862c95964e9a37c3b1305dc108337539c8b3b89d69e64f134d385f2223be3",
    "omh-llm-app-dev/references/build-rails.md": "35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149",
    "omh-llm-app-dev/references/eval-harness.md": "959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd",
    "omh-llm-app-dev/references/public-board.md": "e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca",
    "omh-llm-app-dev/references/stateful-contracts.md": "7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816",
    "omh-localization-review/SKILL.md": "b34b22c357d106d036bb17477f24211f86fa4cfc72a0e6a8f95c12ec7e42ba63",
    "omh-materials-package/SKILL.md": "96d9a4a7de46f68e49cf112fa6cadb9b8feb55c0e5c470d49a0520af1074de6c",
    "omh-media-input/SKILL.md": "ae8d1e09012c22c226327cc984a45c548d16adf7349d3b7c4898a46d153b303c",
    "omh-meeting-brief/SKILL.md": "8c5e782cfcb86deeb3e4acad3f5afe0e23926f6be4d14981672e673359943aee",
    "omh-memory-new/SKILL.md": "65031ba4ad0bd5ac5407eb55094fe1780d7244dc7ef490b18ed5699df8132f28",
    "omh-native-debugging/SKILL.md": "7b14d5ac72900fee0ff7e6fab1845b65d45e4452078e87d3073dc1cbcc533f30",
    "omh-native-debugging/references/native-debug-loop.md": "3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d",
    "omh-operating-rhythm/SKILL.md": "afcf84009038ea5164e92534bc0087ffbf25991203fad956bad992eb0e9b1379",
    "omh-ops-observability-card/SKILL.md": "bb519d4783bdd0a1cbf1409c5144703a145f3185519e62d6b853219099c97cd4",
    "omh-ops-review/SKILL.md": "c5dece95ad42fbfa81291d0f7a11037391be339d3a3d3282fba7cba0d469b532",
    "omh-paper-learning/SKILL.md": "06a38802ce7008a51a46a8a0b2db7bf078caaacfc82bce2a28d753f7c075794d",
    "omh-people-ops/SKILL.md": "5d33fc10c45c53089b4cddd92a0308651ae2416510245a51ec7f0c1297f097ad",
    "omh-physical-device-readiness/SKILL.md": "cd5ac7d183d14cd30b4cf8df32de8ffb0c7b0d06efca7f141a2e80cfbbaaaec2",
    "omh-plan/SKILL.md": "11b3ce3a68b1942125f86e35e488659d272b8a1c3ab6a57aa9fa017adf2cb24f",
    "omh-plan/references/project-constitution.md": "577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da",
    "omh-product-brief/SKILL.md": "fdba4b4b12e083f8a2d493cf57d8a435dc722ecdc2ee556a3850a13bf6f79ccd",
    "omh-product-discovery-validation/SKILL.md": "e827fadf56437016fb69516db1b903b7c830c3c57ebb250113384ecd7986bb41",
    "omh-product-discovery-validation/references/procedure.md": "c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a",
    "omh-production-audit/SKILL.md": "5547ba0eb3674741c8fc949ef7a1b13b5c3f1d968c1605a63393a71cd29daa3f",
    "omh-provider-profile-posture/SKILL.md": "9fb1ff6f17175c7ce7dfa3c4686acbe2a3e0ff87d9a560265f02be25119ef4ae",
    "omh-refactor-plan/SKILL.md": "d14d24391366ccd6ef0765d9229d831a8ee3049c3ed0ff6e442299b71c514f2a",
    "omh-refactor-plan/references/dependency-upgrade.md": "b754550de95896a85e541b5e8f7d46a45696dfa1f73afe57bf7de4df114ebac0",
    "omh-refactor-plan/references/refactor-phases.md": "492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035",
    "omh-reliability-review/SKILL.md": "323407ddfc6847cf7864007c0f1778a5c368e4a84e331f6d8835a9515d3f269a",
    "omh-report-package/SKILL.md": "edf909644bf7457f4e23e2abdae670962222318840d0816fae2d5c8adf40b113",
    "omh-research-brief/SKILL.md": "c5065935f12982a6adcadc7df3d53443b6e2f65b18b4359d60fc7dc497cfb12f",
    "omh-rules-distill/SKILL.md": "91b289b2d37a9b66427fc253d8ef33a62ac62a25f9183748d996a004da80c6c8",
    "omh-run-efficiency/SKILL.md": "f760415398b0d1d449e93387967d67677a40e6a05a8ffbea67b2678dcdb2a0ea",
    "omh-running-work-board/SKILL.md": "63e8a8f117ede0c98f5d9029c64a930576c49ec5856fefbae0c0804877746930",
    "omh-rust/SKILL.md": "7e165afd692559138257a4a07c6f23fc77e221769f2baf3774b2802e81628019",
    "omh-rust/references/rust-discipline.md": "7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844",
    "omh-rust/references/ub-escalation.md": "b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768",
    "omh-sales-development/SKILL.md": "b20b85d5b77ce91c4145d52bb4ecc96884721e9fd98c8b2d79a2000099711add",
    "omh-sales-development/references/procedure.md": "0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70",
    "omh-sales-pipeline-review/SKILL.md": "de2e6755a1eb3acd20732e2ea61586bbd1511850daa8a2fe12a25f4ced353096",
    "omh-sales-pipeline-review/references/procedure.md": "ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138",
    "omh-security-safety-review/SKILL.md": "c53feb8af2439b38c437b8d41a523dcb5552a286309dd401af4986148b30698e",
    "omh-security-safety-review/references/credential-rotation.md": "2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065",
    "omh-skill-health/SKILL.md": "227476bbc5de7375fec53846883a55cbe5465ce49a47db562eda18984475c1de",
    "omh-skill-scout/SKILL.md": "9ea99eb5bed0256800e44041b216c605f073f6c4d7b221ae896d8bc9f6efe154",
    "omh-source-finder/SKILL.md": "dee9bc54b388d99d2bab6f1da1c9528541d702f22ad31e9aad21b16b22825f19",
    "omh-support-operations/SKILL.md": "2541228dac4007e0c4f9b866a7180e2167ee180dafa37f80e055eee21e2b7fee",
    "omh-tech-debt-audit/SKILL.md": "6a9142b2b96b8ef6e6a02d771b66b8d4e5f4009a98c318f391f0118d35a4b946",
    "omh-tech-debt-audit/references/debt-dimensions.md": "7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75",
    "omh-terminal/SKILL.md": "8641a0b19298f4d81ab86d70d746c2aba74485c162abe330e1f06edaa5c1bc47",
    "omh-toolbelt-readiness/SKILL.md": "13a192a9b5aa4d481dade7b19be9afdf6e053cfe51011649dff6fbd58a97f913",
    "omh-verification-gate/SKILL.md": "d9d66e26c328cf6b6667ae259025f184b4950da74d29cde4140e68b0149abdd8",
    "omh-verification-gate/references/generated-artifact-provenance.md": "91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad",
    "omh-verification-gate/references/requirement-coverage-map.md": "91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19",
    "omh-visual-qa/SKILL.md": "071db3172d349f376edddcfaa9bbd16a7b91fe218be25006f115f965a79e66a4",
    "omh-visual-qa/references/visual-verdict-contract.md": "7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759",
    "omh-voice-input/SKILL.md": "a78951eaf35a967bfd3089b1d10bfcd24954e1187e1a8228b6a6492798243c00",
    "omh-web-research/SKILL.md": "bb2ac57ec2fcea70579487248a19a8d9f062077a7630f1599d7a9a704ad66150",
    "omh-wiki/SKILL.md": "4065fe72ca7077e9cb79528203bace0a3115e4b3d389d202b5649f9924da0a51",
    "omh-wiki/references/wiki-blueprint.md": "6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c",
    "omh-wiki/references/wiki-operations.md": "656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528",
    "omh-wiki/references/wiki-patterns.md": "f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e",
    "omh-workspace-audit/SKILL.md": "000dd0823a29400b857135ea394292de9a77302651e8d77bfe6494b354b5bf3e",
    "ulw-context/SKILL.md": "b1542959647255da3e8169854c761bb59f4fc7388447d8ae86a1c900112ab316",
    "ulw-context/references/decision-frontier.md": "122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df",
    "ulw-context/references/project-terms.md": "0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45",
    "ulw-interview/SKILL.md": "871b91e100e61c49de23205a8ecdb690649820f301f66f297a95cc2bda59900d",
    "ulw-interview/references/ambiguity-taxonomy.md": "af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a",
    "ulw-loop/SKILL.md": "4eca60ba2e8584a6735d5227b3c6eb2b483f86afdac6f19f7e0a0fc0bbcfe5cf",
    "ulw-loop/references/goal-constraint-discipline.md": "e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f",
    "ulw-loop/references/measured-loop-discipline.md": "1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb",
    "ulw-perf/SKILL.md": "545b4e9dd8d858e8ebabb3df10fd5053301a2705ae1c9e73f47d0bd3ab817b0a",
    "ulw-plan/SKILL.md": "3b5a48ff022414dd94ee705905d929ccad9bc4045f0e081d8711144b129bef33",
    "ulw-qa/SKILL.md": "6a9649053365cf696209a4a37581682b61499578d69cb7ab0cc17b16ea2f47ce",
    "ulw-research/SKILL.md": "5c8e9f57b68651a244d4965960112cef71772440f396e27e2bc35aa3b7f4f0a2",
    "ulw-research/references/briefing-format.md": "466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac",
    "ulw-work/SKILL.md": "6893ae72e7d2a42733ab30852328acfb0ff39b8db3cec4894e88d38ea2f9aff1",
    "ulw-work/references/dependency-topology.md": "b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac"
  },
  "schema_version": "omh_agent_skills_projection/v1",
  "target_dirs": [
    "."
  ]
}
'@
# Match the CLI's UTF-8 without BOM and LF bytes even on Windows PowerShell 5.1.
[IO.File]::WriteAllText((Join-Path $target '.omh-agent-skills-manifest.json'),
    $receipt.Replace("`r`n", "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Installed opencode skills in $target"
@'
omh-accessibility-audit
omh-adversarial-consensus
omh-agent-debug
omh-agent-ops-review
omh-ai-slop-cleaner
omh-apple-design
omh-application-threat-model
omh-apps
omh-ask
omh-award-bar-score
omh-backend
omh-build-failure-triage
omh-cancel
omh-code-review
omh-codebase-onboarding
omh-codebase-uml
omh-codegraph-refresh
omh-content-operator
omh-context-budget-review
omh-cto-loop
omh-curriculum-design
omh-data-analysis
omh-decide
omh-decision-prototype
omh-decision-recall
omh-deliverable-package
omh-deploy-and-monitor
omh-design-orchestration
omh-design-quality-gate
omh-docs
omh-external-connector-readiness
omh-failure-signal-audit
omh-feedback-triage
omh-files
omh-finance-analysis
omh-frontend
omh-frontend-refactor
omh-github-event-ops
omh-github-issue-intake
omh-harness-session-inventory
omh-idea-to-deploy
omh-image-cards
omh-inference-serving
omh-instinct-ledger
omh-jit-learn
omh-legal-compliance-review
omh-lifecycle-growth
omh-live-incident-response
omh-live-info
omh-llm-app-dev
omh-localization-review
omh-materials-package
omh-media-input
omh-meeting-brief
omh-memory-new
omh-native-debugging
omh-operating-rhythm
omh-ops-observability-card
omh-ops-review
omh-paper-learning
omh-people-ops
omh-physical-device-readiness
omh-plan
omh-product-brief
omh-product-discovery-validation
omh-production-audit
omh-provider-profile-posture
omh-refactor-plan
omh-reliability-review
omh-report-package
omh-research-brief
omh-rules-distill
omh-run-efficiency
omh-running-work-board
omh-rust
omh-sales-development
omh-sales-pipeline-review
omh-security-safety-review
omh-skill-health
omh-skill-scout
omh-source-finder
omh-support-operations
omh-tech-debt-audit
omh-terminal
omh-toolbelt-readiness
omh-verification-gate
omh-visual-qa
omh-voice-input
omh-web-research
omh-wiki
omh-workspace-audit
ulw-context
ulw-interview
ulw-loop
ulw-perf
ulw-plan
ulw-qa
ulw-research
ulw-work
'@ -split "`n"
