from __future__ import annotations

from ..coding.orchestration_vocabulary import CHOOSE_EXECUTOR_REASON


NEXT_ACTION_LABELS: dict[str, str] = {
    "answer_clarification": "asking the needed clarification",
    "answer_directly": "answering directly in chat",
    "answer_file_lookup": "answering as a file or text lookup",
    "ask_one_clarification": "asking one clarification",
    "ask_clarification": "asking one clarification",
    "ask_goal_boundary": "asking for the loop boundary",
    "assess_loopability": "checking whether the goal is loopable",
    "audit_plugin_risk": "auditing one explicit local plugin directory",
    "audit_prompt_compatibility": "auditing explicitly supplied prompt compatibility",
    "audit_learning_readiness": "reviewing workflow learning readiness",
    "cancel": "cancelling the active workflow state",
    "check_install_or_setup_health": "checking install and setup health",
    "choose_executor": CHOOSE_EXECUTOR_REASON,
    "choose_skill": "opening the workflow picker",
    "clarify_or_route": "checking the best workflow or clarification",
    "classify_signal_and_prepare_investigation": "classifying the signal and preparing investigation steps",
    "confirm_risky_action": "asking for one answer on the risky action",
    "dispatch_to_workflow": "opening the selected workflow",
    "dispatch_to_executor": "dispatching to the selected coding agent",
    "gather_source_backed_evidence": "gathering source-backed evidence",
    "open_picker_or_clarify": "opening the picker or asking one clarification",
    "prepare_agent_board_card": "preparing an agent board card",
    "prepare_agent_debug": "preparing an agent debug report",
    "prepare_agent_evaluation": "preparing an agent evaluation",
    "prepare_agent_ops_review": "preparing an agent-ops review",
    "prepare_behavior_lock_and_refactor_scope": "preparing behavior locks and refactor scope",
    "prepare_coding_handoff": "preparing a coding handoff",
    "prepare_coding_runtime_handoff": "preparing a coding runtime handoff",
    "prepare_compatible_route_handoff": "preparing the compatible coding route the request asked for",
    "prepare_named_executor_handoff": "preparing the handoff for the coding agent the request named",
    "prepare_recorded_owner_handoff": "preparing the handoff for the recorded coding owner",
    "prepare_codebase_onboarding": "preparing a codebase onboarding pack",
    "prepare_codegraph_refresh": "preparing a codegraph refresh",
    "prepare_inference_serving": "preparing the model-serving process",
    "prepare_award_bar_score": "scoring the surface against the award bar",
    "prepare_tech_debt_audit": "preparing the tech-debt ledger",
    "prepare_refactor_plan": "preparing a phased refactor plan",
    "prepare_codebase_uml": "drawing the codebase diagram",
    "prepare_context_budget_review": "preparing a context budget review",
    "prepare_deliverable_package": "preparing a deliverable package",
    "prepare_deploy_monitor_plan": "preparing a deploy-and-monitor plan",
    "prepare_design_quality_gate": "preparing a design quality gate",
    "prepare_design_orchestration": "preparing a design orchestration contract",
    "prepare_executor_runtime_readiness": "checking coding-agent readiness",
    "prepare_failure_signal_audit": "preparing a failure signal audit",
    "prepare_finance_analysis": "preparing a finance analysis",
    "prepare_people_ops_brief": "preparing a people-operations brief",
    "prepare_llm_app_build": "preparing the LLM app build handoff",
    "prepare_learning_brief": "confirming the learning target and preparing the learning brief",
    "prepare_legal_compliance_review": "preparing a legal and compliance review",
    "prepare_support_operations": "preparing support triage and reply guidance",
    "prepare_curriculum_design": "preparing a curriculum design",
    "prepare_localization_review": "preparing a localization review",
    "prepare_sales_development": "preparing a sales development brief",
    "prepare_product_brief": "preparing a product brief",
    "prepare_frontend_handoff": "preparing a frontend implementation handoff",
    "prepare_backend_handoff": "preparing a backend service contract",
    "prepare_rust_handoff": "preparing a Rust change contract",
    "prepare_native_debug_plan": "preparing a native debugging plan",
    "prepare_accessibility_audit": "preparing an accessibility audit",
    "prepare_build_failure_triage": "preparing build failure triage",
    "prepare_browser_operator_card": "preparing a browser operator card",
    "prepare_command_operator_card": "preparing a command operator card",
    "prepare_connector_operator_card": "preparing a connector operator card",
    "prepare_external_connector_readiness": "preparing external connector readiness",
    "prepare_project_terms_context": "preparing project terminology alignment",
    "prepare_prompt_import_readiness": "preparing prompt import readiness",
    "prepare_physical_device_readiness": "preparing physical device readiness",
    "prepare_live_info_operator_card": "preparing a live information card",
    "prepare_content_operator_card": "preparing a content operator card",
    "prepare_media_input_card": "preparing a media input card",
    "prepare_data_analysis_card": "preparing a data analysis card",
    "prepare_workspace_file_operator_card": "preparing a workspace file operator card",
    "prepare_gateway_intent_card": "preparing a gateway intent card",
    "prepare_github_event_ops_card": "preparing a GitHub event operations card",
    "prepare_github_issue_intake": "preparing a GitHub issue intake card",
    "prepare_harness_session_inventory": "preparing a harness session inventory",
    "prepare_instinct_ledger": "preparing an instinct ledger",
    "prepare_material_package": "preparing a materials package",
    "prepare_meeting_brief": "preparing a meeting brief",
    "prepare_memory_new": "preparing a new memory candidate",
    "prepare_memory_sync": "preparing a memory curation review",
    "prepare_provider_profile_posture": "preparing a metadata-only provider profile",
    "prepare_memory_review": "preparing a memory review",
    "prepare_one_cycle_delivery": "preparing a one-cycle delivery path",
    "prepare_operating_record": "preparing an operating record",
    "prepare_operating_workflow": "preparing an operating workflow",
    "prepare_ops_observability_card": "preparing an ops observability card",
    "show_achievements_summary": "showing the achievements summary",
    "prepare_ops_review": "preparing an ops review",
    "prepare_paper_learning": "preparing a paper-learning explainer",
    "prepare_production_audit": "preparing a production readiness audit",
    "prepare_quality_performance_and_usability_review": "preparing a quality and usability review",
    "prepare_ultraperf_loop": "preparing a measured performance loop",
    "prepare_reliability_review": "preparing a reliability review",
    "prepare_report_package": "preparing a report package",
    "prepare_research_department_plan": "preparing a research department plan",
    "prepare_review_or_followup_handoff": "preparing a review or follow-up handoff",
    "prepare_rules_distillation": "preparing rule candidates",
    "prepare_scheduled_ops_blueprint": "preparing a scheduled-ops blueprint",
    "prepare_security_safety_review": "preparing a security safety review",
    "prepare_skill_scout": "preparing a skill candidate scout",
    "prepare_skill_health": "preparing a skill health dashboard",
    "prepare_source_finder_plan": "scoping source candidates",
    "prepare_strategy_brief": "preparing a strategy brief",
    "prepare_handoff": "preparing the coding handoff",
    "prepare_toolbelt_readiness": "checking toolbelt readiness",
    "prepare_verification_gate": "preparing a verification gate",
    "prepare_visual_qa": "preparing visual QA",
    "prepare_visual_prompt_card": "preparing an image prompt card",
    "prepare_voice_operator_card": "preparing a voice-operator card",
    "prepare_workspace_audit": "preparing a workspace audit",
    "present_app_delivery_loop": "preparing the app delivery loop",
    "present_meta_route": "presenting the chosen workflow route",
    "present_plan": "preparing a reviewed plan",
    "refresh_status": "refreshing observed status",
    "record_missed_route": "recording a missed-route improvement candidate",
    "record_external_wait": "recording the external wait",
    "record_verification_evidence": "recording verification evidence",
    "reframe_north_star": "reframing the north-star goal",
    "refresh_agent_ops_status": "refreshing agent operations status",
    "recommend": "recommending the playbook",
    "run_cto_loop": "preparing the CTO loop",
    "run_hermes_research": "starting source-backed Hermes research",
    "run_local_operator_check": "running the local operator check",
    "apply_capability_toggle": "turning an OMH capability family on or off",
    "show_running_work_board": "showing the running work board",
    "run_omh_uninstall": "running omh uninstall",
    "run_setup_guide": "walking the setup guide",
    "send_to_executor": "opening the selected coding agent",
    "show_command_preview": "showing the command preview",
    "show_context_brief": "showing the OMH context brief",
    "show_agent_ops_review": "showing agent-ops status",
    "show_coding_handoff_status": "showing coding-agent progress",
    "surface_executor_cancellation": "surfacing the cancelled coding-agent run",
    "show_prompt_handoff": "showing the prompt handoff",
    "show_rejected_decision_recall": "showing scoped rejected-decision context",
    "show_run_efficiency_report": "showing the supplied local run efficiency report",
    "show_quickstart": "showing the first-use path",
    "show_status": "showing status",
    "show_workflow_guidance": "showing workflow guidance",
    "show_workflow_picker": "opening the workflow picker",
    "choose_permission_profile": "choosing the loop permission profile",
    "report_completion_with_evidence": "reporting completion with evidence",
    "report_merge_ready": "reporting merge readiness",
    "report_merged": "reporting the merge",
    "start_loop_cycle": "starting the loopability-gated cycle",
    "start_loop": "starting the loop",
    "start_delivery_cycle": "preparing the one-cycle delivery process",
    "route_direct_task": "routing the direct task",
    "triage_feedback": "triaging the feedback signal",
    "wait_for_executor_evidence": "waiting for coding-agent evidence",
}


def next_action_label(next_action: str) -> str:
    normalized = next_action.strip()
    if not normalized:
        return ""
    return NEXT_ACTION_LABELS.get(normalized, normalized.replace("_", " "))


def next_action_label_with_id(next_action: str, label: str = "") -> str:
    normalized = next_action.strip()
    if not normalized:
        return ""
    resolved_label = label.strip() or next_action_label(normalized)
    if not resolved_label or resolved_label == normalized:
        return normalized
    return f"{resolved_label} (`{normalized}`)"
