from __future__ import annotations

OFFICE_FILE_MATERIAL_PHRASES = (
    "summarize this word document",
    "summarize this document",
    "word document",
    "word doc",
    "word file",
    "document action items",
    "document into action items",
    "compare these two pdfs",
    "compare pdfs",
    "pdf differences",
    "extract tables from this pdf",
    "extract table from this pdf",
    "extract tables from pdf",
    "pdf into csv",
    "pdf to csv",
    "spreadsheet analysis brief",
    "clean analysis brief",
    "첨부한 엑셀",
    "첨부한 엑셀 파일",
    "엑셀 파일 정리",
    "분석 브리프",
    "엑셀을 월간 보고서",
    "첨부한 워드",
    "워드 문서",
    "워드 문서 요약",
    "액션아이템 뽑",
    "pdf 두 개 비교",
    "pdf 두개 비교",
    "pdf 차이점",
    "pdf 표를 csv",
    "pdf 표 추출",
)

OFFICE_FILE_MATERIAL_CATALOG_TRIGGERS = (
    "word document",
    "word doc",
    "document action items",
    "compare pdfs",
    "pdf differences",
    "extract tables from pdf",
    "pdf to csv",
    "spreadsheet analysis brief",
    "clean analysis brief",
    "첨부한 엑셀",
    "첨부한 워드",
    "워드 문서",
    "PDF 두 개 비교",
    "PDF 표를 CSV",
    "PDF 표 추출",
    "분석 브리프",
    "엑셀을 월간 보고서",
)
