# Generated by omh docs agent-skills; edit the catalog/producer, not this file.
# Source inventory SHA256: bd863797908ba38cc384b7b6c740513b7110118d5488d982d25a9d70508dbe6b
param([switch]$User)
$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
if ($args.Count) { throw 'Usage: install.ps1 [-User]' }
$base = (Get-Location).ProviderPath
if ($User) {
    $base = $env:USERPROFILE
    if (-not $base) { $base = $env:HOME }
    if (-not $base) { throw 'User profile is required for -User' }
    $target = Join-Path $base '.agents/skills'
} else {
    $target = Join-Path $base '.agents/skills'
}
$source = Join-Path (Split-Path -Parent $PSScriptRoot) 'agent-skills'
$checksums = @'
289b853e6a0d311e122625c41e349c11a5240fdbda392ba4c3b02e9bf9bfbf91  omh-accessibility-audit/SKILL.md
cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469  omh-accessibility-audit/references/a11y-rules.md
54af2bd5cf2145624ed5e3c008a2e66de1cfc1556a43494736620e321d35ab0a  omh-adversarial-consensus/SKILL.md
e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89  omh-adversarial-consensus/references/consensus-protocol.md
2da387aca391905adbd89bf57d76160680cf61269a688339fac8c6295e9d937d  omh-agent-debug/SKILL.md
b3201fb1d915bc3a4a75186a78cf4e29b26a0b59a5843aef6752afa6a86b1697  omh-agent-instructions/SKILL.md
cc8f82b67198fa905f1336ea0fb8b50a2451b290ca4678efc41cc2c195828446  omh-agent-instructions/references/instruction-file-method.md
7ca75c0709b83a1b042a15fdbadf19ffc77397d8f58df7c369102fdcc543555b  omh-agent-ops-review/SKILL.md
d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291  omh-agent-ops-review/references/instrumentation-ladder.md
51fa0d8d39f31cde15eb99d44fed95bd5b04ee429524d50af904a44c0c4f1154  omh-ai-slop-cleaner/SKILL.md
d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d  omh-ai-slop-cleaner/references/cleanup-passes.md
efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5  omh-ai-slop-cleaner/references/prose-lexicon.md
e54a74696e88279ddbaf2af0d015d5937a8d73b914b70f1497577c4ebe753fb6  omh-app-debugging/SKILL.md
d9f5490c1ca4bdb421d901f72e4a2839706ff75d842811060d441686135ef9de  omh-app-debugging/references/hypothesis-and-race-method.md
badde9a499244a4630c1f2f950f3318998f895b51fd0d229a97e591c4b0ed582  omh-apple-design/SKILL.md
09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26  omh-apple-design/references/materials-and-accessibility.md
4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0  omh-apple-design/references/platform-foundations.md
835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd  omh-apple-design/references/product-visual-production.md
c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604  omh-apple-design/references/review-playbook.md
81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e  omh-apple-design/references/web-production-libraries.md
028a2bc9d658d96d8987b07c6da9de9e96b1f8646c3667a557b88f84469a036f  omh-application-threat-model/SKILL.md
ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e  omh-application-threat-model/references/threat-model-method.md
e7872e2cffa859a80bfc0aa3c4f8b208736303acb82f3329d8546f225f2ebede  omh-apps/SKILL.md
db0dbeca4f712063ba3155f4f235a88c20a7c7bd78e7c0dd7cfd4774b7331081  omh-ask/SKILL.md
64b5d5a3d80fb7ffbb3062b7c489ffcdd28847c18b233b9f18a22b5500d021a1  omh-award-bar-score/SKILL.md
3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50  omh-award-bar-score/references/award-judging-model.md
10441cdec74a910a76e4f43ee79d07b864236dcf2471d0026e253ade905a8991  omh-backend/SKILL.md
843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9  omh-backend/references/consumer-impact.md
e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054  omh-backend/references/schema-migration.md
25d8cc97c4629504df5a392d66cc9ba1595d9246b1760b0ff0cb4cd4a1398e30  omh-backend/references/service-contract.md
d02513dd1b5b629000cf31f25fd6c974d47c69ba10d0e4c9fc14f570380a2753  omh-build-failure-triage/SKILL.md
735cb62ac316ff6c35a5c54ac9bfdf0d38d81e8d41f651a4c29ca86f9aa7ded8  omh-cancel/SKILL.md
64a62cd6c7e6eece6c65694faf001e08d00531d3069c387abef3ca647f074114  omh-code-review/SKILL.md
6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424  omh-code-review/references/review-dispatch.md
fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f  omh-code-review/references/review-lenses.md
9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db  omh-code-review/references/review-response.md
99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be  omh-code-review/references/smell-baseline.md
109fa20869839ff375fc511125c5baa25a86017c1615112a813c572bf2de4ae8  omh-codebase-onboarding/SKILL.md
612d424800eab5192955d4b2ce728da17b139ff7728dafc02c9f43e6c68d1710  omh-codebase-uml/SKILL.md
7e4cec77b5da5b23bd71a7ae6802f01bf76b6dd12d3c2c7937f224d3ae4d6c8f  omh-codegraph-refresh/SKILL.md
676bb867bed9f6dcfe0e24a8dbbf2d4b2cfe8ad718febc6dfc7ff7e197b00d46  omh-commit-pr-authoring/SKILL.md
1ff3ade943d6d24a90e1ace1e1eefa4ffb9d9e48e41e71856d346b420aac8c99  omh-commit-pr-authoring/references/commit-and-pr-conventions.md
09746bcd5a63c491c6a57d12a70198456d8d18036d00110472fee0827fc74539  omh-content-operator/SKILL.md
bddcba31f474d32a799759a8bcdad6726e2cd2d86f3614b58cf344af2329f57c  omh-context-budget-review/SKILL.md
bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590  omh-context-budget-review/references/cache-placement.md
6093861aebb853d8ce53f475689e5636b6d43cdb2718a33b756201e162e906d8  omh-cto-loop/SKILL.md
2162885d7ea6609874c61aea5528a410335b7237bc816bb69202b73b67efce7e  omh-curriculum-design/SKILL.md
5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b  omh-curriculum-design/references/procedure.md
8188f936fc0dfccf9eb3ac5a79847b0edbce2e8e935342d9a342d364e681dd95  omh-data-analysis/SKILL.md
a0d9bbee334ae8478bf7d86bbcd758fa57a7e42b914ec86e695f39ef23f4cd82  omh-data-pipelines/SKILL.md
9f2dea6059c664a0c1ab4d989545825d3ecc567d22816af00975e79670ef36f0  omh-data-pipelines/references/pipeline-method.md
26fc10f85faf0c0ed7c297dc80d54a8fe5f4e15c43caacc72272b2e87bd09bae  omh-decide/SKILL.md
5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae  omh-decide/references/capacity-planning.md
4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d  omh-decide/references/decision-records.md
cbaa6c7c3692eb16f10b1b68979f990d0f0fd7104c6222137ee986d88e23406b  omh-decision-prototype/SKILL.md
53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88  omh-decision-prototype/references/procedure.md
4ec7f47add585e3a4f5ce4e7e2cf034872c49bc831d512cb30cddfeafd815ec7  omh-decision-recall/SKILL.md
2bfc4e81fe853c57f40fbf4d114fdc74033f5196288f62c278ae89242ef29efa  omh-deliverable-package/SKILL.md
537a2565efa5c560a39ca9902e4c497a92c241ccc7d653b191f785587fc23295  omh-deploy-and-monitor/SKILL.md
13ef1781d9a3fdb6ecf04bbe6af7e9094fb4077c5182e9434f625610216e8782  omh-design-orchestration/SKILL.md
d6ab05fbf9fe63dd64b00c2ef6149ed8c911a9c25352b6ab8181e2b21acbcf1b  omh-design-quality-gate/SKILL.md
7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae  omh-design-quality-gate/references/design-critique-rubric.md
e960791460cad888340874ee77b47d9b831febabf6a50632623164920ad1bbba  omh-docs/SKILL.md
c13314eb561fe95e55f55172808a77582c8683d05b590135d60ae7021d330980  omh-external-connector-readiness/SKILL.md
b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3  omh-external-connector-readiness/references/memory-provider-trial.md
ea34846d980bab8d2878deeaf9b3a284f7b3ec178d228b7af438aad05b2579f4  omh-failure-signal-audit/SKILL.md
00e8008b7cc2b4d0eeca4dd2dde0c4fb1ea5e112c6f167189da5c9c2b9a61262  omh-feedback-triage/SKILL.md
44411ba3c8a1a22e8b7d37c1b4a8fbceb9b4095b25fb4d724ce8687c0a22cb6a  omh-files/SKILL.md
7a2cb00ccd913a82172b58f3be124b2c031d9bbcbba46cd5549ecfa3554fd9c9  omh-finance-analysis/SKILL.md
0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c  omh-finance-analysis/references/procedure.md
347d22b3dd7d7f57524bd2737658d64e65095fa8f3e665ddff528da4043c16f2  omh-frontend-refactor/SKILL.md
ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f  omh-frontend-refactor/references/refactor-passes.md
04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4  omh-frontend-refactor/references/state-discipline.md
91e98db76faae0853a651c6b830a6479baad2087ad7866a4e352601871c1246c  omh-frontend/SKILL.md
60a63a5708c45d1ceae4b788fe3bcca7799ba5155d2a0372848262e8e9a70a8d  omh-frontend/references/chart-styling.md
591ff300492510a50ae7e92904c7e705073c637f7028e2306964a2855f729f62  omh-frontend/references/component-registry-adoption.md
658841bd7b41bfed4fb6be29d6d2db3c257367a202e53f1f02fa3a796e499d3e  omh-frontend/references/design-system-contract.md
b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf  omh-frontend/references/reference-token-extraction.md
ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09  omh-frontend/references/screenshot-loop.md
605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245  omh-frontend/references/scroll-motion-libraries.md
e4f820fcf594021e7915a42eb8a1fff6f139b0d1bd88fe4da28b430959c1ad16  omh-frontend/references/taste-foundations.md
13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e  omh-frontend/references/tui-craft.md
7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b  omh-frontend/references/web-vitals-budgets.md
8c9f2288e21191a39e01480bb5f5e7e27954eb3611de2c0b3f35d848274f2fd6  omh-git-workflow/SKILL.md
7c5b14e1d8972467fc7a59e84bbd7c200106e983d7ef277d147ddb5792b7980e  omh-git-workflow/references/git-repair-method.md
2b9befc9f4dd65ae049c6a10049520cbd97ec2a2bdbdd66946f422fc9b4484db  omh-github-event-ops/SKILL.md
fc8594530bd5b8beb267c960f2aa4ef741539359077183f8a124d43698a0a105  omh-github-issue-intake/SKILL.md
4418cdbd4eaad4229b15d3aed18e7452b85824dd64421ca5698e89685588e238  omh-harness-session-inventory/SKILL.md
01a249db8a2c691712e884ed2fdc663e9b7c5db546b257563b73e6ec8a92b9e9  omh-iac-change/SKILL.md
25c75f8974c19cd74028d093a703facb0c66f7b199ca1dc16e937d93b5dbdb5a  omh-iac-change/references/iac-change-method.md
e39211fa303b984a2900bc807a7534cff08939bbdaf7df4286199b337415d4f8  omh-idea-to-deploy/SKILL.md
dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7  omh-idea-to-deploy/references/project-bootstrap.md
2b548c538eff827c1a1092476ca27b8e28a85bd6e06388403dc4c009e31e58c2  omh-image-cards/SKILL.md
531c14aa88ffbdb7b134942f41ff195ff9d0797d317a2a3b17ebc6eceea6605f  omh-inference-serving/SKILL.md
31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0  omh-inference-serving/references/serving-bench.md
da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e  omh-inference-serving/references/serving-runbooks.md
62231b63f819f2d645ef918b41574b012c067809e710f52f20bdddffe339b1db  omh-instinct-ledger/SKILL.md
da42d3f5cb959db3bf6ed200d1d3c151518bfce619ebe75067a75ce4ebfdf298  omh-internal-audit/SKILL.md
2b651418c2a5bdfbd659ebbff7c08e3670443e198e76ddd9d215d5cee821deaa  omh-internal-audit/references/control-audit-method.md
f5ed94d64a4a39e72fba65a1a5d6cfb93ad267a148da2c63fb7b0b9e29ca051b  omh-jit-learn/SKILL.md
ba4ad680bbc1a2f2debc782a7cc1b5c70e3c8342844428346451a677f01c7a28  omh-legal-compliance-review/SKILL.md
a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1  omh-legal-compliance-review/references/negotiation-preparation.md
670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58  omh-legal-compliance-review/references/procedure.md
cace3be4599dd4d317392d1e99a570871916e675ccf8dcbbdf55c1ef710f4e66  omh-lifecycle-growth/SKILL.md
7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de  omh-lifecycle-growth/references/procedure.md
6b82f165b715ca7ddffa95999442cc680b31fc54571dc299461f8fae21899238  omh-live-incident-response/SKILL.md
8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7  omh-live-incident-response/references/incident-command-method.md
f9e7237b395f625c433ab04d00c5a416d6a631be7dc47b0ea813ee9a9839c327  omh-live-info/SKILL.md
d92836b38345e6c5f9d36e317e22ab248aacaea2a97e831ce3f8136e3098a23e  omh-llm-app-dev/SKILL.md
35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149  omh-llm-app-dev/references/build-rails.md
959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd  omh-llm-app-dev/references/eval-harness.md
e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca  omh-llm-app-dev/references/public-board.md
7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816  omh-llm-app-dev/references/stateful-contracts.md
28af9199ea879b437d0a00e0203075a3fe868c5551c9f6cfed59889137eea5f5  omh-localization-review/SKILL.md
bcc3cd63e2f664bd83a607482670cf2b2fd8f2994833c7c7f749fa4da396f09e  omh-materials-package/SKILL.md
807f2da5a49760d143bbd85914df1ff9bd3b620eb2ec96a61e58537256b7d51f  omh-media-input/SKILL.md
2570eb07ac26b1ed4987795f59ace5349677d5cfc3cfceb9c9305e52d7c4ff2a  omh-meeting-brief/SKILL.md
78d31e1336e91efe91a97486cc228a9c15ec7d77009df17ddef99e952ffd765b  omh-memory-new/SKILL.md
279ecc6a617b687257bc1b1ab4f78609bbb64bfa902596a73f16dc3605e78177  omh-mobile-release/SKILL.md
c28b6bec1569b8971c42b412e054daa8d9efa23a4fad698cd72ce2acc349de82  omh-mobile-release/references/mobile-release-method.md
b1cf221ee30bc07307ab873e7ec6b8ef16164854abacc82706697bcdf2848782  omh-model-finetuning/SKILL.md
10a677fdc07303b3b2b3b0d7759f9b5956e9f00fac94ccad0bac9bdef3d8d797  omh-model-finetuning/references/finetuning-method.md
9653ffeaf097915fcb3c93b9d73ff17fa4676842cab02248190fcb2aa278432d  omh-native-debugging/SKILL.md
3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d  omh-native-debugging/references/native-debug-loop.md
ec66b715e91bcf7cc78cb5f50bdb29ac5b4d96376ab55d2f2e38c52f9a70e3a6  omh-operating-rhythm/SKILL.md
99f500ec4384b06c5949174eda92137ce1669258929470954326ef4874688767  omh-ops-observability-card/SKILL.md
0476e9471cf84d4360591eb8730e9b3d2b3fc78df73b02acce969a53eabf229d  omh-ops-review/SKILL.md
f0db3970f7d6b79eb36f63e6fae2e7e3f1b293c3a041610f62b9bbf09ed84042  omh-paper-learning/SKILL.md
f7eb49c19e0ed7ce96aaebfb423f1b9e5ed1a6ee2e592644a2d418d5f076e140  omh-people-ops/SKILL.md
e9e418d01d6975cff79ac46f8b09e94c346d7a77114a9f4620ba191ed555117d  omh-physical-device-readiness/SKILL.md
af2118b8a42919a7f6998c4e1150a4d8ede386f30a838eeee2de73aa22f36946  omh-plan/SKILL.md
577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da  omh-plan/references/project-constitution.md
85e18adc44db15f9ff177c4a69066eab223e586f85a1a2ded9896bf2a24a5f9b  omh-product-brief/SKILL.md
3f0d9fdc1d1179146d186885a51e74633606e751bd2a1c431966de3e2bf64097  omh-product-discovery-validation/SKILL.md
c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a  omh-product-discovery-validation/references/procedure.md
b356a71f3997bc16b7183698527b6d9909d45c765c99e43185a649418385f6c0  omh-production-audit/SKILL.md
db3f49faa5e27b51a912c4574c8dfa84d802b020d3e054feb0ae48fc46c2b20d  omh-provider-profile-posture/SKILL.md
fb2c648d8497fcf647564adf07f1e5022cea5565eff6087f042e4890797ce4fa  omh-refactor-plan/SKILL.md
97e9b74b117a66171386a0015a0ad60954def8dcf59b1d6c180037919c61bfbf  omh-refactor-plan/references/dependency-upgrade.md
492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035  omh-refactor-plan/references/refactor-phases.md
cadf67ded0fc4a5e80fa8d984b0293cf4d4a3d52e2418ebef975f4041e41f8fc  omh-relational-db/SKILL.md
c5a495fec865b028c18882f3a4102d491610945edd23a109fac49b8f914fb6b4  omh-relational-db/references/engine-lock-tables.md
16f4ef3d1f730554e2a2df6c32f8af632f8506f83661841a8d81d0db7e17dc1c  omh-release-cut/SKILL.md
e97a49d65d6b943fa5bbacc4f8083fcd94e52d864cea97301c9b945180e57cc9  omh-release-cut/references/release-and-rollback-method.md
e3d6f6fef43c4698a83d689730c171de7fac282397a5a6a657ab1606dcc489da  omh-reliability-review/SKILL.md
5ae3f9d3d9dd9d6038f1b4d37f58915361d4e25d12ff2ecea02c27a6b247dabd  omh-report-package/SKILL.md
45adab6737c7358787a70c159033c148bb0d637a2ee56b5509fc26589d3841ea  omh-research-brief/SKILL.md
55a6b64d85db685a531eb53df7f60284ac452a297651fa4dff5a8b068c9bc8e1  omh-rules-distill/SKILL.md
a896b93d5bbe90b9fe138c2637f9df4d167f3861407f9bb2fb8349617d8a53f9  omh-run-efficiency/SKILL.md
0c1c1dd1e1a8efdd05e13e0b000537cef904f88777cad3dfa9a0763c46e13aa0  omh-running-work-board/SKILL.md
6bcaf4508ea2b1e7c57c027b5bf1591cbef2d9877c3c2d08ee6946f8987e75c4  omh-rust/SKILL.md
7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844  omh-rust/references/rust-discipline.md
b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768  omh-rust/references/ub-escalation.md
dbf4d2c99567a98f9c46d620bdfeae6225d0dd0e2e2a16975ad080e86653c631  omh-sales-development/SKILL.md
0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70  omh-sales-development/references/procedure.md
31af567fff32d7640426a90e8f5c2f6bd19963e3b3436b0a4b80625b22c9be63  omh-sales-pipeline-review/SKILL.md
ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138  omh-sales-pipeline-review/references/procedure.md
d76df1d2dfe34847744e4c314a921b2319c161dfcaaeef5ab298f41903291cb7  omh-security-event-response/SKILL.md
2ea0a28b9d22cb0fa3016617e3d52253bb30d82d30c4931437c60f6706213090  omh-security-event-response/references/event-containment-order.md
4e56f5be6b30fde5e13dab8e48eaffc2b919a7d8c4479e743453045183a42cd1  omh-security-safety-review/SKILL.md
2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065  omh-security-safety-review/references/credential-rotation.md
02f843131ffbf582a7659bec55e278505327eeb0cd7dbdd84e34d50bcc7f322b  omh-skill-health/SKILL.md
365c38a051c4e4776cfc4d4459c90db250d79340c219dbd0d1f4d55ffff43b96  omh-skill-scout/SKILL.md
2156a1713a5796bd6f05514d16cbce88fbf0aa49fe0d50009515a8e729b329a4  omh-source-finder/SKILL.md
eaa36e08eb9e91c0dc51ee4d3e22e44fff644dd85a674dc3cf86538aa7c2e505  omh-support-operations/SKILL.md
218fddf9e7be0ebc6c95b59ad4d6ce19eba9239e0f21dbbd6e0d16bef1960bff  omh-tech-debt-audit/SKILL.md
7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75  omh-tech-debt-audit/references/debt-dimensions.md
c6be0ca423cf634593ed4130ec696fc9c501517ed670ac0f3b932829c6d25b8e  omh-terminal/SKILL.md
127705531ef74f4a0b3c70b23b72955d7c2f9b6b6d762b7097d380920905ad7f  omh-toolbelt-readiness/SKILL.md
5d7123e2c6b50805339dcd56ae4c798ba7626cb2b780dfc56d816702568fffe8  omh-verification-gate/SKILL.md
91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad  omh-verification-gate/references/generated-artifact-provenance.md
91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19  omh-verification-gate/references/requirement-coverage-map.md
e57a45f135b4f1224cf65766e9fc851511ddecf4c56482b183205e8f8fb14cfc  omh-visual-qa/SKILL.md
7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759  omh-visual-qa/references/visual-verdict-contract.md
d15fab885fb53df39b45466ab376d983a70a204ecba10a809e442c8ce2f7c283  omh-voice-input/SKILL.md
d52ac78758bf8dd79cf02bc86a1b71138d119de1fc75fdeec47a791886a3507a  omh-web-research/SKILL.md
5d166038d310402a398e81bccbe225b7d5f6843046deb2170dbb87dc39f8bc60  omh-wiki/SKILL.md
6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c  omh-wiki/references/wiki-blueprint.md
656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528  omh-wiki/references/wiki-operations.md
f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e  omh-wiki/references/wiki-patterns.md
1844186a7a9919f935c74e641e13be7e37618dd84b9aa0ad4204e060bfdc51b7  omh-workspace-audit/SKILL.md
c82670b7855de34953b7586b559818b75f62cc966df0045dab4b6f8e558290a8  ulw-context/SKILL.md
122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df  ulw-context/references/decision-frontier.md
0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45  ulw-context/references/project-terms.md
dd48ecd5054055b33052b0664d9741a9962bf4e60ead032426603fc8d74493aa  ulw-interview/SKILL.md
af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a  ulw-interview/references/ambiguity-taxonomy.md
797243a7bc87a30ffdbe6cb7c11fe6e94afbedcbefa3a199709561fa174a3dac  ulw-loop/SKILL.md
e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f  ulw-loop/references/goal-constraint-discipline.md
03305b52330d8f16c67bfdca4f25f1b289bd9d45c18fff7568e2a4c930428a00  ulw-loop/references/loop-design-review.md
1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb  ulw-loop/references/measured-loop-discipline.md
4189814b67cd81e446f42dc0dbb0e91168c065d2833b9dbc895539226bb927ad  ulw-perf/SKILL.md
b4083d2acaca9857391e0212e10f917802a5f77a05a86ecbeb6e3e9f8f08c080  ulw-plan/SKILL.md
11049ec3a49f47c5b0447cb8faa6b36ade31da65219def1a9d5526d9f535479f  ulw-qa/SKILL.md
ca887a0cb672c2418d5d3f959c25d25d50187df964c3219a8d0586888faa0f58  ulw-research/SKILL.md
466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac  ulw-research/references/briefing-format.md
32ca677b6e4ac3c7e54881105bd262f8e8cf03f32dadd6ed66ebd31e7ddb87e8  ulw-work/SKILL.md
b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac  ulw-work/references/dependency-topology.md
'@
$entries = @($checksums.Split("`n") | ForEach-Object {
    $parts = $_.TrimEnd("`r") -split '  ', 2
    [PSCustomObject]@{ Path = $parts[1]; Hash = $parts[0] }
})
function Assert-NoLink([string]$Path, [string]$Boundary) {
    $current = $Path
    while ($current -and $current -ne $Boundary) {
        if (Test-Path -LiteralPath $current) {
            $item = Get-Item -Force -LiteralPath $current
            if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
                throw "Reparse-point path: $current"
            }
        }
        $current = Split-Path -Parent $current
    }
}
Assert-NoLink $source (Split-Path -Parent $source)
$items = @(Get-ChildItem -Force -Recurse -LiteralPath $source)
foreach ($item in $items) {
    if ($item.Attributes -band [IO.FileAttributes]::ReparsePoint) {
        throw "Reparse-point source: $($item.FullName)"
    }
}
$sourceFiles = @($items | Where-Object { -not $_.PSIsContainer })
if ($sourceFiles.Count -ne $entries.Count) { throw 'Source file inventory mismatch' }
function Assert-Digests([string]$Root) {
    foreach ($entry in $entries) {
        $path = Join-Path $Root $entry.Path
        if (-not (Test-Path -LiteralPath $path -PathType Leaf)) { throw "Missing skill: $path" }
        if ((Get-FileHash -LiteralPath $path -Algorithm SHA256).Hash.ToLowerInvariant() -cne $entry.Hash) {
            throw "Skill digest mismatch: $path"
        }
    }
}
Assert-Digests $source
# Preflight the receipt as well as every copied file before any write.
foreach ($relative in (@($entries.Path) + '.omh-agent-skills-manifest.json')) {
    $path = Join-Path $target $relative
    Assert-NoLink $path $base
    if ((Test-Path -LiteralPath $path) -and -not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Not a file: $path"
    }
}
foreach ($entry in $entries) {
    $path = Join-Path $target $entry.Path
    [IO.Directory]::CreateDirectory((Split-Path -Parent $path)) | Out-Null
    [IO.File]::Copy((Join-Path $source $entry.Path), $path, $true)
}
Assert-Digests $target
$receipt = @'
{
  "catalog_revision": "bd30c2e790c6a20266ce93e67ea2a438698d71c7a7eee66b6f6af4badb2ffcee",
  "files": {
    "omh-accessibility-audit/SKILL.md": "289b853e6a0d311e122625c41e349c11a5240fdbda392ba4c3b02e9bf9bfbf91",
    "omh-accessibility-audit/references/a11y-rules.md": "cd7e0404576923cfd3bcec9e055b1de7a78f3fc55971fd033598aac1043e4469",
    "omh-adversarial-consensus/SKILL.md": "54af2bd5cf2145624ed5e3c008a2e66de1cfc1556a43494736620e321d35ab0a",
    "omh-adversarial-consensus/references/consensus-protocol.md": "e2337062d98214abc440d3909d7c076db284c817dc45c9b67a292003a6b51a89",
    "omh-agent-debug/SKILL.md": "2da387aca391905adbd89bf57d76160680cf61269a688339fac8c6295e9d937d",
    "omh-agent-instructions/SKILL.md": "b3201fb1d915bc3a4a75186a78cf4e29b26a0b59a5843aef6752afa6a86b1697",
    "omh-agent-instructions/references/instruction-file-method.md": "cc8f82b67198fa905f1336ea0fb8b50a2451b290ca4678efc41cc2c195828446",
    "omh-agent-ops-review/SKILL.md": "7ca75c0709b83a1b042a15fdbadf19ffc77397d8f58df7c369102fdcc543555b",
    "omh-agent-ops-review/references/instrumentation-ladder.md": "d9dab70027ab489a122df7e5814e9580e6bc1cc1899fa70da680ef54bfd65291",
    "omh-ai-slop-cleaner/SKILL.md": "51fa0d8d39f31cde15eb99d44fed95bd5b04ee429524d50af904a44c0c4f1154",
    "omh-ai-slop-cleaner/references/cleanup-passes.md": "d713b686c3cc076cbba63aa278176581dc09aae94c07697c3413e8d124c5845d",
    "omh-ai-slop-cleaner/references/prose-lexicon.md": "efd209984c3e5823995484dd5b6e38e3161a059db9e841b4599dbbd330417ee5",
    "omh-app-debugging/SKILL.md": "e54a74696e88279ddbaf2af0d015d5937a8d73b914b70f1497577c4ebe753fb6",
    "omh-app-debugging/references/hypothesis-and-race-method.md": "d9f5490c1ca4bdb421d901f72e4a2839706ff75d842811060d441686135ef9de",
    "omh-apple-design/SKILL.md": "badde9a499244a4630c1f2f950f3318998f895b51fd0d229a97e591c4b0ed582",
    "omh-apple-design/references/materials-and-accessibility.md": "09588fbd807e527ed354fc317fc0fc3c654006878da42eb59461e45fb1ad9c26",
    "omh-apple-design/references/platform-foundations.md": "4984a8f9f3eb0b1876be5b4f4bc024b002c8738be53ccaa1dc29467d3aaeffa0",
    "omh-apple-design/references/product-visual-production.md": "835383a0c276a0e5150a9a7ba633bcb798d265eb5fcd96ab082dc5c513ccf5cd",
    "omh-apple-design/references/review-playbook.md": "c021e7c05152b68d746dcea05942fd0215630551a2a419fb9fa6a809f0b6f604",
    "omh-apple-design/references/web-production-libraries.md": "81ac6fd49dc78ea629cc949d9d0aed99eea969629d3606866882988f5ec5e99e",
    "omh-application-threat-model/SKILL.md": "028a2bc9d658d96d8987b07c6da9de9e96b1f8646c3667a557b88f84469a036f",
    "omh-application-threat-model/references/threat-model-method.md": "ed3819fecf9c8d7208a49fbbebc5863dcc9df009a663e0d012431bc3296e5e8e",
    "omh-apps/SKILL.md": "e7872e2cffa859a80bfc0aa3c4f8b208736303acb82f3329d8546f225f2ebede",
    "omh-ask/SKILL.md": "db0dbeca4f712063ba3155f4f235a88c20a7c7bd78e7c0dd7cfd4774b7331081",
    "omh-award-bar-score/SKILL.md": "64b5d5a3d80fb7ffbb3062b7c489ffcdd28847c18b233b9f18a22b5500d021a1",
    "omh-award-bar-score/references/award-judging-model.md": "3eb04c94402da5efaa2d3bc18bb66acd1121b234a8b82a47a878c5d01725be50",
    "omh-backend/SKILL.md": "10441cdec74a910a76e4f43ee79d07b864236dcf2471d0026e253ade905a8991",
    "omh-backend/references/consumer-impact.md": "843ec98391847e3de4e28057ab4aeb95d24a4d8e593b1c812e630723a4f006b9",
    "omh-backend/references/schema-migration.md": "e20aebd284f51d18962e28959b2e35702c9662e4d3d13fb1854c60f1279a6054",
    "omh-backend/references/service-contract.md": "25d8cc97c4629504df5a392d66cc9ba1595d9246b1760b0ff0cb4cd4a1398e30",
    "omh-build-failure-triage/SKILL.md": "d02513dd1b5b629000cf31f25fd6c974d47c69ba10d0e4c9fc14f570380a2753",
    "omh-cancel/SKILL.md": "735cb62ac316ff6c35a5c54ac9bfdf0d38d81e8d41f651a4c29ca86f9aa7ded8",
    "omh-code-review/SKILL.md": "64a62cd6c7e6eece6c65694faf001e08d00531d3069c387abef3ca647f074114",
    "omh-code-review/references/review-dispatch.md": "6a155bc585a17cb85a5bea62c5b834657e308a3958c317d54657ab0f8fcab424",
    "omh-code-review/references/review-lenses.md": "fb2ae13bd37473da0937c715db313142d5f5516fe0b4235038b38b0ad28d7d4f",
    "omh-code-review/references/review-response.md": "9da4fc0d81fb7c7d26ecf6fbcf17f8ee95fc76bfba8a31f70cf689ee296682db",
    "omh-code-review/references/smell-baseline.md": "99afc82c29fee000b31fe6749d3fe6148920de1cc24738df57bf06d0c4d0d2be",
    "omh-codebase-onboarding/SKILL.md": "109fa20869839ff375fc511125c5baa25a86017c1615112a813c572bf2de4ae8",
    "omh-codebase-uml/SKILL.md": "612d424800eab5192955d4b2ce728da17b139ff7728dafc02c9f43e6c68d1710",
    "omh-codegraph-refresh/SKILL.md": "7e4cec77b5da5b23bd71a7ae6802f01bf76b6dd12d3c2c7937f224d3ae4d6c8f",
    "omh-commit-pr-authoring/SKILL.md": "676bb867bed9f6dcfe0e24a8dbbf2d4b2cfe8ad718febc6dfc7ff7e197b00d46",
    "omh-commit-pr-authoring/references/commit-and-pr-conventions.md": "1ff3ade943d6d24a90e1ace1e1eefa4ffb9d9e48e41e71856d346b420aac8c99",
    "omh-content-operator/SKILL.md": "09746bcd5a63c491c6a57d12a70198456d8d18036d00110472fee0827fc74539",
    "omh-context-budget-review/SKILL.md": "bddcba31f474d32a799759a8bcdad6726e2cd2d86f3614b58cf344af2329f57c",
    "omh-context-budget-review/references/cache-placement.md": "bdac27120964aa692bd9b47f107fc9f19105d87f362e787e41c217d7a38d7590",
    "omh-cto-loop/SKILL.md": "6093861aebb853d8ce53f475689e5636b6d43cdb2718a33b756201e162e906d8",
    "omh-curriculum-design/SKILL.md": "2162885d7ea6609874c61aea5528a410335b7237bc816bb69202b73b67efce7e",
    "omh-curriculum-design/references/procedure.md": "5078d35c8cd9cae8257fd14fa8ab7466bff5287500f160787633ec2930d1da1b",
    "omh-data-analysis/SKILL.md": "8188f936fc0dfccf9eb3ac5a79847b0edbce2e8e935342d9a342d364e681dd95",
    "omh-data-pipelines/SKILL.md": "a0d9bbee334ae8478bf7d86bbcd758fa57a7e42b914ec86e695f39ef23f4cd82",
    "omh-data-pipelines/references/pipeline-method.md": "9f2dea6059c664a0c1ab4d989545825d3ecc567d22816af00975e79670ef36f0",
    "omh-decide/SKILL.md": "26fc10f85faf0c0ed7c297dc80d54a8fe5f4e15c43caacc72272b2e87bd09bae",
    "omh-decide/references/capacity-planning.md": "5f017b357b0bfb37279918098b9992c3c793ac8ad4056969bf3e2c0e6d5bb9ae",
    "omh-decide/references/decision-records.md": "4da873d3351a8d7ab96d44860c62d7d18130147abb7aa390078eee6dbe2d4d2d",
    "omh-decision-prototype/SKILL.md": "cbaa6c7c3692eb16f10b1b68979f990d0f0fd7104c6222137ee986d88e23406b",
    "omh-decision-prototype/references/procedure.md": "53334fb4c76acb18a49272bd9dfab9317c0f9d3eb812b7ef9e87550d99762e88",
    "omh-decision-recall/SKILL.md": "4ec7f47add585e3a4f5ce4e7e2cf034872c49bc831d512cb30cddfeafd815ec7",
    "omh-deliverable-package/SKILL.md": "2bfc4e81fe853c57f40fbf4d114fdc74033f5196288f62c278ae89242ef29efa",
    "omh-deploy-and-monitor/SKILL.md": "537a2565efa5c560a39ca9902e4c497a92c241ccc7d653b191f785587fc23295",
    "omh-design-orchestration/SKILL.md": "13ef1781d9a3fdb6ecf04bbe6af7e9094fb4077c5182e9434f625610216e8782",
    "omh-design-quality-gate/SKILL.md": "d6ab05fbf9fe63dd64b00c2ef6149ed8c911a9c25352b6ab8181e2b21acbcf1b",
    "omh-design-quality-gate/references/design-critique-rubric.md": "7b7bde56a390431bd46b1b1d3965723521c722f461d12bdc993407a54595e9ae",
    "omh-docs/SKILL.md": "e960791460cad888340874ee77b47d9b831febabf6a50632623164920ad1bbba",
    "omh-external-connector-readiness/SKILL.md": "c13314eb561fe95e55f55172808a77582c8683d05b590135d60ae7021d330980",
    "omh-external-connector-readiness/references/memory-provider-trial.md": "b6eda7efc3307d8bd6540bec47b2564f3e565da5ad8133bd998b2ebcabdf29a3",
    "omh-failure-signal-audit/SKILL.md": "ea34846d980bab8d2878deeaf9b3a284f7b3ec178d228b7af438aad05b2579f4",
    "omh-feedback-triage/SKILL.md": "00e8008b7cc2b4d0eeca4dd2dde0c4fb1ea5e112c6f167189da5c9c2b9a61262",
    "omh-files/SKILL.md": "44411ba3c8a1a22e8b7d37c1b4a8fbceb9b4095b25fb4d724ce8687c0a22cb6a",
    "omh-finance-analysis/SKILL.md": "7a2cb00ccd913a82172b58f3be124b2c031d9bbcbba46cd5549ecfa3554fd9c9",
    "omh-finance-analysis/references/procedure.md": "0fd8b3ad528d10aebd971c26375de9775e95429d3dbdc3a6f2ee5cc063a9c79c",
    "omh-frontend-refactor/SKILL.md": "347d22b3dd7d7f57524bd2737658d64e65095fa8f3e665ddff528da4043c16f2",
    "omh-frontend-refactor/references/refactor-passes.md": "ce187b2323fda67fb536249193b4cc0bab1f04024986c8313bb7a4c5fd87e54f",
    "omh-frontend-refactor/references/state-discipline.md": "04084cfd8d849f9e0b468d8a30fecc58f8c37ca5d5585afeb1e3bce95719faa4",
    "omh-frontend/SKILL.md": "91e98db76faae0853a651c6b830a6479baad2087ad7866a4e352601871c1246c",
    "omh-frontend/references/chart-styling.md": "60a63a5708c45d1ceae4b788fe3bcca7799ba5155d2a0372848262e8e9a70a8d",
    "omh-frontend/references/component-registry-adoption.md": "591ff300492510a50ae7e92904c7e705073c637f7028e2306964a2855f729f62",
    "omh-frontend/references/design-system-contract.md": "658841bd7b41bfed4fb6be29d6d2db3c257367a202e53f1f02fa3a796e499d3e",
    "omh-frontend/references/reference-token-extraction.md": "b36dedde2f859f83a95563cddab06f4002ce8c0a2c3b4ef64abc8a954c1e12bf",
    "omh-frontend/references/screenshot-loop.md": "ddaaf841a154130222c98945d070f4a8b157a564ef59a3f960a3e48e01113e09",
    "omh-frontend/references/scroll-motion-libraries.md": "605393baaed428e2adab937fdbc1ab3e5db20a6592039d948a2447da80ceb245",
    "omh-frontend/references/taste-foundations.md": "e4f820fcf594021e7915a42eb8a1fff6f139b0d1bd88fe4da28b430959c1ad16",
    "omh-frontend/references/tui-craft.md": "13153858bf9da970915003cb22b42ff714fdfd351458f1a0cac20fd789fb477e",
    "omh-frontend/references/web-vitals-budgets.md": "7905f7913ff835eb84e7b9bd88059d52d7ede370312f2e24df8cb7ebf407a29b",
    "omh-git-workflow/SKILL.md": "8c9f2288e21191a39e01480bb5f5e7e27954eb3611de2c0b3f35d848274f2fd6",
    "omh-git-workflow/references/git-repair-method.md": "7c5b14e1d8972467fc7a59e84bbd7c200106e983d7ef277d147ddb5792b7980e",
    "omh-github-event-ops/SKILL.md": "2b9befc9f4dd65ae049c6a10049520cbd97ec2a2bdbdd66946f422fc9b4484db",
    "omh-github-issue-intake/SKILL.md": "fc8594530bd5b8beb267c960f2aa4ef741539359077183f8a124d43698a0a105",
    "omh-harness-session-inventory/SKILL.md": "4418cdbd4eaad4229b15d3aed18e7452b85824dd64421ca5698e89685588e238",
    "omh-iac-change/SKILL.md": "01a249db8a2c691712e884ed2fdc663e9b7c5db546b257563b73e6ec8a92b9e9",
    "omh-iac-change/references/iac-change-method.md": "25c75f8974c19cd74028d093a703facb0c66f7b199ca1dc16e937d93b5dbdb5a",
    "omh-idea-to-deploy/SKILL.md": "e39211fa303b984a2900bc807a7534cff08939bbdaf7df4286199b337415d4f8",
    "omh-idea-to-deploy/references/project-bootstrap.md": "dc9a474dfc063984b84ae5d1a5d28a9ba1f0bb2b77292245b703b20b0fbe27e7",
    "omh-image-cards/SKILL.md": "2b548c538eff827c1a1092476ca27b8e28a85bd6e06388403dc4c009e31e58c2",
    "omh-inference-serving/SKILL.md": "531c14aa88ffbdb7b134942f41ff195ff9d0797d317a2a3b17ebc6eceea6605f",
    "omh-inference-serving/references/serving-bench.md": "31f452f33561faf2cd90edd1cf30f33bc74c14bc13c81d77a087db5392d56aa0",
    "omh-inference-serving/references/serving-runbooks.md": "da5b5950a621d7eedc5333721de4d23651439d06bdd2d9e9661461d1bef9ac5e",
    "omh-instinct-ledger/SKILL.md": "62231b63f819f2d645ef918b41574b012c067809e710f52f20bdddffe339b1db",
    "omh-internal-audit/SKILL.md": "da42d3f5cb959db3bf6ed200d1d3c151518bfce619ebe75067a75ce4ebfdf298",
    "omh-internal-audit/references/control-audit-method.md": "2b651418c2a5bdfbd659ebbff7c08e3670443e198e76ddd9d215d5cee821deaa",
    "omh-jit-learn/SKILL.md": "f5ed94d64a4a39e72fba65a1a5d6cfb93ad267a148da2c63fb7b0b9e29ca051b",
    "omh-legal-compliance-review/SKILL.md": "ba4ad680bbc1a2f2debc782a7cc1b5c70e3c8342844428346451a677f01c7a28",
    "omh-legal-compliance-review/references/negotiation-preparation.md": "a0952b301dc12976606e979590da1f01c9b71d4cd5892f6b2f453536b2e4b4c1",
    "omh-legal-compliance-review/references/procedure.md": "670f501f3136c0f5456b82149ca24153f1b38d5151f539a9b1ab0df30e2f0b58",
    "omh-lifecycle-growth/SKILL.md": "cace3be4599dd4d317392d1e99a570871916e675ccf8dcbbdf55c1ef710f4e66",
    "omh-lifecycle-growth/references/procedure.md": "7a26968cd2e4d46a536fe28d93dd7adc2f89c01ca59ab042d5d6ff205b5762de",
    "omh-live-incident-response/SKILL.md": "6b82f165b715ca7ddffa95999442cc680b31fc54571dc299461f8fae21899238",
    "omh-live-incident-response/references/incident-command-method.md": "8d5ad3bb15d401cf45300ec3d7df126072fcd20bee40e3bc702bd35027b754b7",
    "omh-live-info/SKILL.md": "f9e7237b395f625c433ab04d00c5a416d6a631be7dc47b0ea813ee9a9839c327",
    "omh-llm-app-dev/SKILL.md": "d92836b38345e6c5f9d36e317e22ab248aacaea2a97e831ce3f8136e3098a23e",
    "omh-llm-app-dev/references/build-rails.md": "35db50a4960ced98fa2ee556e59c5a439188e8b47bebef5073efa9264d8fe149",
    "omh-llm-app-dev/references/eval-harness.md": "959130e28abaabea53cf9ed6fe46268ce27372333d2a6d28b6f0e02928ac2cbd",
    "omh-llm-app-dev/references/public-board.md": "e69b890be7da4d91ce612722b180b229821db714bd72aa28a55db013364e7cca",
    "omh-llm-app-dev/references/stateful-contracts.md": "7bda4e79b8c60f406d3a4e7ea9d3e4f7c69d6ee80a23416678be678d6dd95816",
    "omh-localization-review/SKILL.md": "28af9199ea879b437d0a00e0203075a3fe868c5551c9f6cfed59889137eea5f5",
    "omh-materials-package/SKILL.md": "bcc3cd63e2f664bd83a607482670cf2b2fd8f2994833c7c7f749fa4da396f09e",
    "omh-media-input/SKILL.md": "807f2da5a49760d143bbd85914df1ff9bd3b620eb2ec96a61e58537256b7d51f",
    "omh-meeting-brief/SKILL.md": "2570eb07ac26b1ed4987795f59ace5349677d5cfc3cfceb9c9305e52d7c4ff2a",
    "omh-memory-new/SKILL.md": "78d31e1336e91efe91a97486cc228a9c15ec7d77009df17ddef99e952ffd765b",
    "omh-mobile-release/SKILL.md": "279ecc6a617b687257bc1b1ab4f78609bbb64bfa902596a73f16dc3605e78177",
    "omh-mobile-release/references/mobile-release-method.md": "c28b6bec1569b8971c42b412e054daa8d9efa23a4fad698cd72ce2acc349de82",
    "omh-model-finetuning/SKILL.md": "b1cf221ee30bc07307ab873e7ec6b8ef16164854abacc82706697bcdf2848782",
    "omh-model-finetuning/references/finetuning-method.md": "10a677fdc07303b3b2b3b0d7759f9b5956e9f00fac94ccad0bac9bdef3d8d797",
    "omh-native-debugging/SKILL.md": "9653ffeaf097915fcb3c93b9d73ff17fa4676842cab02248190fcb2aa278432d",
    "omh-native-debugging/references/native-debug-loop.md": "3ce0f29395b8a1c71074ce2808d6d2497bef1ccbecbba179b74950055435430d",
    "omh-operating-rhythm/SKILL.md": "ec66b715e91bcf7cc78cb5f50bdb29ac5b4d96376ab55d2f2e38c52f9a70e3a6",
    "omh-ops-observability-card/SKILL.md": "99f500ec4384b06c5949174eda92137ce1669258929470954326ef4874688767",
    "omh-ops-review/SKILL.md": "0476e9471cf84d4360591eb8730e9b3d2b3fc78df73b02acce969a53eabf229d",
    "omh-paper-learning/SKILL.md": "f0db3970f7d6b79eb36f63e6fae2e7e3f1b293c3a041610f62b9bbf09ed84042",
    "omh-people-ops/SKILL.md": "f7eb49c19e0ed7ce96aaebfb423f1b9e5ed1a6ee2e592644a2d418d5f076e140",
    "omh-physical-device-readiness/SKILL.md": "e9e418d01d6975cff79ac46f8b09e94c346d7a77114a9f4620ba191ed555117d",
    "omh-plan/SKILL.md": "af2118b8a42919a7f6998c4e1150a4d8ede386f30a838eeee2de73aa22f36946",
    "omh-plan/references/project-constitution.md": "577991e718cf3e1d62ce93704d4a734f7e058a3d516b0722c636cc8cf7a519da",
    "omh-product-brief/SKILL.md": "85e18adc44db15f9ff177c4a69066eab223e586f85a1a2ded9896bf2a24a5f9b",
    "omh-product-discovery-validation/SKILL.md": "3f0d9fdc1d1179146d186885a51e74633606e751bd2a1c431966de3e2bf64097",
    "omh-product-discovery-validation/references/procedure.md": "c4b545ab2472299450aa8279f3d15a64afbfada6e14314f083d3f905aa52a19a",
    "omh-production-audit/SKILL.md": "b356a71f3997bc16b7183698527b6d9909d45c765c99e43185a649418385f6c0",
    "omh-provider-profile-posture/SKILL.md": "db3f49faa5e27b51a912c4574c8dfa84d802b020d3e054feb0ae48fc46c2b20d",
    "omh-refactor-plan/SKILL.md": "fb2c648d8497fcf647564adf07f1e5022cea5565eff6087f042e4890797ce4fa",
    "omh-refactor-plan/references/dependency-upgrade.md": "97e9b74b117a66171386a0015a0ad60954def8dcf59b1d6c180037919c61bfbf",
    "omh-refactor-plan/references/refactor-phases.md": "492cfcd81b1b44ffb54bcb16b6dc319549a7ee868d95b21176fa9cc0fa06f035",
    "omh-relational-db/SKILL.md": "cadf67ded0fc4a5e80fa8d984b0293cf4d4a3d52e2418ebef975f4041e41f8fc",
    "omh-relational-db/references/engine-lock-tables.md": "c5a495fec865b028c18882f3a4102d491610945edd23a109fac49b8f914fb6b4",
    "omh-release-cut/SKILL.md": "16f4ef3d1f730554e2a2df6c32f8af632f8506f83661841a8d81d0db7e17dc1c",
    "omh-release-cut/references/release-and-rollback-method.md": "e97a49d65d6b943fa5bbacc4f8083fcd94e52d864cea97301c9b945180e57cc9",
    "omh-reliability-review/SKILL.md": "e3d6f6fef43c4698a83d689730c171de7fac282397a5a6a657ab1606dcc489da",
    "omh-report-package/SKILL.md": "5ae3f9d3d9dd9d6038f1b4d37f58915361d4e25d12ff2ecea02c27a6b247dabd",
    "omh-research-brief/SKILL.md": "45adab6737c7358787a70c159033c148bb0d637a2ee56b5509fc26589d3841ea",
    "omh-rules-distill/SKILL.md": "55a6b64d85db685a531eb53df7f60284ac452a297651fa4dff5a8b068c9bc8e1",
    "omh-run-efficiency/SKILL.md": "a896b93d5bbe90b9fe138c2637f9df4d167f3861407f9bb2fb8349617d8a53f9",
    "omh-running-work-board/SKILL.md": "0c1c1dd1e1a8efdd05e13e0b000537cef904f88777cad3dfa9a0763c46e13aa0",
    "omh-rust/SKILL.md": "6bcaf4508ea2b1e7c57c027b5bf1591cbef2d9877c3c2d08ee6946f8987e75c4",
    "omh-rust/references/rust-discipline.md": "7d9b5005213715f4712dac2371fa63699b8ba963e843f360d75789d576c12844",
    "omh-rust/references/ub-escalation.md": "b39328707a4c3e1cf1d152603f0840255d68db3cfda714d6c33d853ebb087768",
    "omh-sales-development/SKILL.md": "dbf4d2c99567a98f9c46d620bdfeae6225d0dd0e2e2a16975ad080e86653c631",
    "omh-sales-development/references/procedure.md": "0ed747dc7a21bee8931023e4f7d78f65a7a9845ccf40cd6b754eeecc2a6aea70",
    "omh-sales-pipeline-review/SKILL.md": "31af567fff32d7640426a90e8f5c2f6bd19963e3b3436b0a4b80625b22c9be63",
    "omh-sales-pipeline-review/references/procedure.md": "ae092ea4d9363da82d23620f33a2f83e8a3dd42f4a8d69fd08b92cb2989fa138",
    "omh-security-event-response/SKILL.md": "d76df1d2dfe34847744e4c314a921b2319c161dfcaaeef5ab298f41903291cb7",
    "omh-security-event-response/references/event-containment-order.md": "2ea0a28b9d22cb0fa3016617e3d52253bb30d82d30c4931437c60f6706213090",
    "omh-security-safety-review/SKILL.md": "4e56f5be6b30fde5e13dab8e48eaffc2b919a7d8c4479e743453045183a42cd1",
    "omh-security-safety-review/references/credential-rotation.md": "2a4e1cacc2c10141a1aaff437353150696c397f5fec0b41536eb5d946ebff065",
    "omh-skill-health/SKILL.md": "02f843131ffbf582a7659bec55e278505327eeb0cd7dbdd84e34d50bcc7f322b",
    "omh-skill-scout/SKILL.md": "365c38a051c4e4776cfc4d4459c90db250d79340c219dbd0d1f4d55ffff43b96",
    "omh-source-finder/SKILL.md": "2156a1713a5796bd6f05514d16cbce88fbf0aa49fe0d50009515a8e729b329a4",
    "omh-support-operations/SKILL.md": "eaa36e08eb9e91c0dc51ee4d3e22e44fff644dd85a674dc3cf86538aa7c2e505",
    "omh-tech-debt-audit/SKILL.md": "218fddf9e7be0ebc6c95b59ad4d6ce19eba9239e0f21dbbd6e0d16bef1960bff",
    "omh-tech-debt-audit/references/debt-dimensions.md": "7d0d601c1fc8897f0ce433dfa2ae44c2a5c9dd69ded28d7775cb6adbdd2afb75",
    "omh-terminal/SKILL.md": "c6be0ca423cf634593ed4130ec696fc9c501517ed670ac0f3b932829c6d25b8e",
    "omh-toolbelt-readiness/SKILL.md": "127705531ef74f4a0b3c70b23b72955d7c2f9b6b6d762b7097d380920905ad7f",
    "omh-verification-gate/SKILL.md": "5d7123e2c6b50805339dcd56ae4c798ba7626cb2b780dfc56d816702568fffe8",
    "omh-verification-gate/references/generated-artifact-provenance.md": "91a818c86eb8311e39f7e1e0f1dca2bed5066551acff83a656aeb78e947f2fad",
    "omh-verification-gate/references/requirement-coverage-map.md": "91b86c41bdee5e4336c92a15875f8691fb929e75377b3c18187d6bc8eb184a19",
    "omh-visual-qa/SKILL.md": "e57a45f135b4f1224cf65766e9fc851511ddecf4c56482b183205e8f8fb14cfc",
    "omh-visual-qa/references/visual-verdict-contract.md": "7c803a3997dc58be0a4b88f2d7aa081cc5cac49a227d0cc19437cd1aad420759",
    "omh-voice-input/SKILL.md": "d15fab885fb53df39b45466ab376d983a70a204ecba10a809e442c8ce2f7c283",
    "omh-web-research/SKILL.md": "d52ac78758bf8dd79cf02bc86a1b71138d119de1fc75fdeec47a791886a3507a",
    "omh-wiki/SKILL.md": "5d166038d310402a398e81bccbe225b7d5f6843046deb2170dbb87dc39f8bc60",
    "omh-wiki/references/wiki-blueprint.md": "6f99240689395f0b37cf57e09b4c38d1c134820271dc7cd83c6693e2c8693c5c",
    "omh-wiki/references/wiki-operations.md": "656b7873c4d9ad4458244bb376d4808dac9af7a520c35b6f22b58cbbe8434528",
    "omh-wiki/references/wiki-patterns.md": "f13fd0b06dde204c10458cabb5d76b1f21351f7b641a73336eb82342d33ff16e",
    "omh-workspace-audit/SKILL.md": "1844186a7a9919f935c74e641e13be7e37618dd84b9aa0ad4204e060bfdc51b7",
    "ulw-context/SKILL.md": "c82670b7855de34953b7586b559818b75f62cc966df0045dab4b6f8e558290a8",
    "ulw-context/references/decision-frontier.md": "122978a41c0a003f8b7a879b00c9ecc2417e75d5fbb787f24ecb3477403a67df",
    "ulw-context/references/project-terms.md": "0b6baee554fc8fa813d9b4b86aab55a9858441d2c3b2d90ef0d037a8f12afd45",
    "ulw-interview/SKILL.md": "dd48ecd5054055b33052b0664d9741a9962bf4e60ead032426603fc8d74493aa",
    "ulw-interview/references/ambiguity-taxonomy.md": "af4b13bcfe583b138e9b1de47a851e40e227ce30b0404fcb10bfa16abe297d3a",
    "ulw-loop/SKILL.md": "797243a7bc87a30ffdbe6cb7c11fe6e94afbedcbefa3a199709561fa174a3dac",
    "ulw-loop/references/goal-constraint-discipline.md": "e9755a82604a6b9d363716b6bf33bc980406ea40bce813d763eda9703e1a093f",
    "ulw-loop/references/loop-design-review.md": "03305b52330d8f16c67bfdca4f25f1b289bd9d45c18fff7568e2a4c930428a00",
    "ulw-loop/references/measured-loop-discipline.md": "1c3da401271e023ea21cf5aa0a1cee488cdb9bb8ca966251dc0bca767af00dfb",
    "ulw-perf/SKILL.md": "4189814b67cd81e446f42dc0dbb0e91168c065d2833b9dbc895539226bb927ad",
    "ulw-plan/SKILL.md": "b4083d2acaca9857391e0212e10f917802a5f77a05a86ecbeb6e3e9f8f08c080",
    "ulw-qa/SKILL.md": "11049ec3a49f47c5b0447cb8faa6b36ade31da65219def1a9d5526d9f535479f",
    "ulw-research/SKILL.md": "ca887a0cb672c2418d5d3f959c25d25d50187df964c3219a8d0586888faa0f58",
    "ulw-research/references/briefing-format.md": "466c21fb7bedefe1e42dbdb3f8ddaf3321504882140af507a292188678243dac",
    "ulw-work/SKILL.md": "32ca677b6e4ac3c7e54881105bd262f8e8cf03f32dadd6ed66ebd31e7ddb87e8",
    "ulw-work/references/dependency-topology.md": "b35e627344579054a9ec46722ca59cdf9f6bda41a217f0b3775669c1ad764dac"
  },
  "schema_version": "omh_agent_skills_projection/v1",
  "target_dirs": [
    "."
  ]
}
'@
# Match the CLI's UTF-8 without BOM and LF bytes even on Windows PowerShell 5.1.
[IO.File]::WriteAllText((Join-Path $target '.omh-agent-skills-manifest.json'),
    $receipt.Replace("`r`n", "`n") + "`n", [Text.UTF8Encoding]::new($false))
Write-Output "Installed openclaw skills in $target"
@'
omh-accessibility-audit
omh-adversarial-consensus
omh-agent-debug
omh-agent-instructions
omh-agent-ops-review
omh-ai-slop-cleaner
omh-app-debugging
omh-apple-design
omh-application-threat-model
omh-apps
omh-ask
omh-award-bar-score
omh-backend
omh-build-failure-triage
omh-cancel
omh-code-review
omh-codebase-onboarding
omh-codebase-uml
omh-codegraph-refresh
omh-commit-pr-authoring
omh-content-operator
omh-context-budget-review
omh-cto-loop
omh-curriculum-design
omh-data-analysis
omh-data-pipelines
omh-decide
omh-decision-prototype
omh-decision-recall
omh-deliverable-package
omh-deploy-and-monitor
omh-design-orchestration
omh-design-quality-gate
omh-docs
omh-external-connector-readiness
omh-failure-signal-audit
omh-feedback-triage
omh-files
omh-finance-analysis
omh-frontend
omh-frontend-refactor
omh-git-workflow
omh-github-event-ops
omh-github-issue-intake
omh-harness-session-inventory
omh-iac-change
omh-idea-to-deploy
omh-image-cards
omh-inference-serving
omh-instinct-ledger
omh-internal-audit
omh-jit-learn
omh-legal-compliance-review
omh-lifecycle-growth
omh-live-incident-response
omh-live-info
omh-llm-app-dev
omh-localization-review
omh-materials-package
omh-media-input
omh-meeting-brief
omh-memory-new
omh-mobile-release
omh-model-finetuning
omh-native-debugging
omh-operating-rhythm
omh-ops-observability-card
omh-ops-review
omh-paper-learning
omh-people-ops
omh-physical-device-readiness
omh-plan
omh-product-brief
omh-product-discovery-validation
omh-production-audit
omh-provider-profile-posture
omh-refactor-plan
omh-relational-db
omh-release-cut
omh-reliability-review
omh-report-package
omh-research-brief
omh-rules-distill
omh-run-efficiency
omh-running-work-board
omh-rust
omh-sales-development
omh-sales-pipeline-review
omh-security-event-response
omh-security-safety-review
omh-skill-health
omh-skill-scout
omh-source-finder
omh-support-operations
omh-tech-debt-audit
omh-terminal
omh-toolbelt-readiness
omh-verification-gate
omh-visual-qa
omh-voice-input
omh-web-research
omh-wiki
omh-workspace-audit
ulw-context
ulw-interview
ulw-loop
ulw-perf
ulw-plan
ulw-qa
ulw-research
ulw-work
'@ -split "`n"
