from __future__ import annotations


from ..executors import (
    CODING_EXECUTOR_HANDOFF_TARGETS,
    CODING_RUNTIME_HANDOFF_TARGETS,
    CODING_EXECUTOR_TARGETS,
    EXECUTOR_HANDOFF_SCHEMA_VERSION,
    PROMPT_HANDOFF_SCHEMA_VERSION,
    RUNTIME_HANDOFF_SCHEMA_VERSION,
)

TASK_PROMPT_CONTRACT_SCHEMA_VERSION = "executor_task_prompt_contract/v1"
TASK_PROMPT_REQUIRED_SECTIONS = ("Goal", "Do", "Don't", "Expected result", "Test")
CODEX_SESSION_OBSERVATION_CONTRACT_SCHEMA_VERSION = "codex_session_observation_contract/v1"


__all__ = [
    "CODING_EXECUTOR_HANDOFF_TARGETS",
    "CODING_RUNTIME_HANDOFF_TARGETS",
    "CODING_EXECUTOR_TARGETS",
    "EXECUTOR_HANDOFF_SCHEMA_VERSION",
    "PROMPT_HANDOFF_SCHEMA_VERSION",
    "RUNTIME_HANDOFF_SCHEMA_VERSION",
    "TASK_PROMPT_CONTRACT_SCHEMA_VERSION",
    "TASK_PROMPT_REQUIRED_SECTIONS",
    "CODEX_SESSION_OBSERVATION_CONTRACT_SCHEMA_VERSION",
]
